import { createHash } from 'node:crypto';
export const COMPLEXITY_INTERFACE_SIZE_SCHEMA_ID = 'atm.complexityInterfaceSize.v1' as const;
export type ComplexityStatus = 'proven'|'blocked'|'stale'|'contradictory';
export interface ComplexityAuthority { readonly authorityId: string; readonly digest: string; readonly sealed: true; }
export interface ComplexityModule { readonly moduleId: string; readonly cyclomatic: number; readonly crap: number; readonly interfaceSize: number; readonly digest: string; }
export interface ComplexityInput { readonly runId:string; readonly generatedAt:string; readonly authority:ComplexityAuthority; readonly observedAuthorityDigest:string; readonly modules:readonly ComplexityModule[]; readonly maxCyclomatic:number; readonly maxCrap:number; readonly maxInterfaceSize:number; }
export interface ComplexityResult { readonly schemaId:typeof COMPLEXITY_INTERFACE_SIZE_SCHEMA_ID; readonly specVersion:'0.1.0'; readonly runId:string; readonly generatedAt:string; readonly authority:ComplexityAuthority; readonly limits:{readonly maxCyclomatic:number;readonly maxCrap:number;readonly maxInterfaceSize:number}; readonly modules:readonly ComplexityModule[]; readonly projection:{readonly moduleCount:number;readonly violations:readonly string[]}; readonly status:ComplexityStatus; readonly diagnostics:readonly string[]; readonly resultDigest:string; }
export function compileComplexityInterfaceSize(input:ComplexityInput):ComplexityResult { const n=normalize(input),d:string[]=[]; if(!n.authority.digest||n.observedAuthorityDigest!==n.authority.digest)d.push('authority-digest-mismatch'); const seen=new Set<string>(); for(const m of n.modules){if(seen.has(m.moduleId))d.push(`duplicate-module:${m.moduleId}`);seen.add(m.moduleId);if(m.cyclomatic<0||m.crap<0||m.interfaceSize<0)d.push(`invalid-metrics:${m.moduleId}`);} const violations=n.modules.flatMap(m=>[m.cyclomatic>n.maxCyclomatic?`${m.moduleId}:cyclomatic`: '',m.crap>n.maxCrap?`${m.moduleId}:crap`: '',m.interfaceSize>n.maxInterfaceSize?`${m.moduleId}:interface-size`: ''].filter(Boolean)); if(violations.length)d.push('complexity-limit-exceeded'); const status:ComplexityStatus=d.some(x=>x.startsWith('duplicate-')||x.startsWith('invalid-'))?'contradictory':d.some(x=>x.includes('authority'))?'stale':d.length?'blocked':'proven'; const projection={moduleCount:n.modules.length,violations}; const result={schemaId:COMPLEXITY_INTERFACE_SIZE_SCHEMA_ID,specVersion:'0.1.0' as const,runId:n.runId,generatedAt:n.generatedAt,authority:n.authority,limits:{maxCyclomatic:n.maxCyclomatic,maxCrap:n.maxCrap,maxInterfaceSize:n.maxInterfaceSize},modules:n.modules,projection,status,diagnostics:d,resultDigest:digest({n,projection,status,diagnostics:d})};return result; }
export const createComplexityInterfaceSize=compileComplexityInterfaceSize;
export function replayComplexityInterfaceSize(r:ComplexityResult){return compileComplexityInterfaceSize({runId:r.runId,generatedAt:r.generatedAt,authority:r.authority,observedAuthorityDigest:r.authority.digest,modules:r.modules,...r.limits});}
export function validateComplexityInterfaceSize(r:ComplexityResult){const x=replayComplexityInterfaceSize(r),d=[...r.diagnostics];if(x.resultDigest!==r.resultDigest)d.push('result-digest-mismatch');return{ok:d.length===0&&r.status==='proven',diagnostics:[...new Set(d)]};}
function normalize(i:ComplexityInput){return{runId:String(i.runId??'').trim(),generatedAt:String(i.generatedAt??'').trim(),authority:{authorityId:String(i.authority?.authorityId??''),digest:String(i.authority?.digest??''),sealed:true as const},observedAuthorityDigest:String(i.observedAuthorityDigest??''),maxCyclomatic:Number(i.maxCyclomatic),maxCrap:Number(i.maxCrap),maxInterfaceSize:Number(i.maxInterfaceSize),modules:[...(i.modules??[])].map(m=>({...m,moduleId:String(m.moduleId??'').trim(),cyclomatic:Number(m.cyclomatic),crap:Number(m.crap),interfaceSize:Number(m.interfaceSize)})).sort((a,b)=>a.moduleId.localeCompare(b.moduleId))};}
function digest(v:unknown){return`sha256:${createHash('sha256').update(JSON.stringify(v)).digest('hex')}`;}
