import { createHash } from 'node:crypto';

export const FAULT_FINGERPRINT_SCHEMA_ID = 'atm.faultFingerprintResult.v1' as const;
export type FaultFamily = 'shared-index' | 'sealed-commit' | 'cas-queue' | 'foreign-dirty' | 'stale-batch' | 'close-deferral' | 'unknown';
export interface FaultObservation { readonly observationId: string; readonly publicSeam: string; readonly errorClass: string; readonly causalImpact: string; readonly mutationLineage?: string | null; readonly familyHint?: string | null; readonly mutationEvidence?: readonly string[]; }
export interface FaultAuthority { readonly authorityId: string; readonly sealed: boolean; readonly digest: string; }
export interface FaultFingerprintInput { readonly runId: string; readonly authority: FaultAuthority; readonly observations: readonly FaultObservation[]; readonly knownFamilies?: readonly FaultFamily[]; }
export interface FaultDiagnostic { readonly code: string; readonly severity: 'error' | 'warning'; readonly message: string; readonly ref: string | null; readonly repairCommand: string | null; }
export interface FaultFamilyMatch { readonly family: FaultFamily; readonly confidence: number; readonly decision: 'exact-match' | 'new-family-proposal' | 'mapping-review'; readonly evidence: readonly string[]; }
export interface FaultFingerprint { readonly fingerprintId: string; readonly observationId: string; readonly normalized: { readonly publicSeam: string; readonly errorClass: string; readonly causalImpact: string; readonly mutationLineage: string | null }; readonly familyMatch: FaultFamilyMatch; }
export interface FaultFingerprintResult { readonly schemaId: typeof FAULT_FINGERPRINT_SCHEMA_ID; readonly specVersion: '0.1.0'; readonly runId: string; readonly resultId: string; readonly authority: FaultAuthority; readonly status: 'matched' | 'blocked' | 'stale'; readonly fingerprints: readonly FaultFingerprint[]; readonly diagnostics: readonly FaultDiagnostic[]; readonly provenance: { readonly inputDigest: string; readonly observationCount: number; readonly knownFamilies: readonly FaultFamily[] }; }

const FAMILIES = new Set<FaultFamily>(['shared-index', 'sealed-commit', 'cas-queue', 'foreign-dirty', 'stale-batch', 'close-deferral']);
const text = (value: unknown) => String(value ?? '').trim().toLowerCase().replace(/\s+/g, ' ');
const digest = (value: unknown) => `sha256:${createHash('sha256').update(JSON.stringify(value)).digest('hex')}`;
const error = (code: string, message: string, ref: string | null, repairCommand: string | null = null): FaultDiagnostic => ({ code, severity: 'error', message, ref, repairCommand });

export function createFaultFingerprint(input: FaultFingerprintInput): FaultFingerprintResult {
  const normalized = { runId: text(input?.runId), authority: { authorityId: text(input?.authority?.authorityId), sealed: input?.authority?.sealed === true, digest: text(input?.authority?.digest) }, observations: [...(input?.observations ?? [])].map((item) => ({ observationId: text(item.observationId), publicSeam: text(item.publicSeam), errorClass: text(item.errorClass), causalImpact: text(item.causalImpact), mutationLineage: item.mutationLineage == null ? null : text(item.mutationLineage), familyHint: item.familyHint == null ? null : text(item.familyHint), mutationEvidence: [...(item.mutationEvidence ?? [])].map(text).filter(Boolean).sort() })).sort((a, b) => a.observationId.localeCompare(b.observationId)), knownFamilies: [...(input?.knownFamilies ?? [])].map((family) => text(family) as FaultFamily).filter((family) => FAMILIES.has(family)).sort() };
  const diagnostics: FaultDiagnostic[] = [];
  if (!normalized.runId) diagnostics.push(error('ATM_FAULT_FINGERPRINT_RUN_ID_MISSING', 'runId is required.', 'runId'));
  if (!normalized.authority.authorityId || !normalized.authority.digest) diagnostics.push(error('ATM_FAULT_FINGERPRINT_AUTHORITY_INCOMPLETE', 'A sealed authority id and digest are required.', 'authority', 'restore and seal the fault observation authority'));
  if (!normalized.authority.sealed) diagnostics.push(error('ATM_FAULT_FINGERPRINT_AUTHORITY_UNSEALED', 'Fingerprinting requires sealed observations.', 'authority.sealed', 'seal the observation authority before matching'));
  if (!normalized.observations.length) diagnostics.push(error('ATM_FAULT_FINGERPRINT_INPUT_EMPTY', 'At least one fault observation is required.', 'observations', 'restore the deterministic incident fixture'));
  const fingerprints = normalized.observations.map((observation) => {
    if (!observation.observationId || !observation.publicSeam || !observation.errorClass || !observation.causalImpact) diagnostics.push(error('ATM_FAULT_FINGERPRINT_OBSERVATION_INCOMPLETE', 'Observation identity, seam, error class, and causal impact are required.', observation.observationId || null, 'restore the complete sealed observation'));
    const key = { publicSeam: observation.publicSeam, errorClass: observation.errorClass, causalImpact: observation.causalImpact, mutationLineage: observation.mutationLineage };
    const candidates = normalized.knownFamilies.map((family) => ({ family, score: familyScore(family, observation) || directFamilyScore(family, observation) })).filter((candidate) => candidate.score > 0).sort((a, b) => b.score - a.score || a.family.localeCompare(b.family));
    const top = candidates[0]; const second = candidates[1];
    let family: FaultFamily = 'unknown'; let decision: FaultFamilyMatch['decision'] = 'new-family-proposal'; let confidence = 0.35; const evidence = [...(observation.mutationEvidence ?? [])];
    if (top && (!second || top.score > second.score)) { family = top.family; confidence = Math.min(1, 0.65 + top.score * 0.1 + (evidence.length ? 0.05 : 0)); decision = confidence >= 0.8 ? 'exact-match' : 'mapping-review'; }
    if (observation.familyHint && (!FAMILIES.has(observation.familyHint as FaultFamily) || (family !== 'unknown' && observation.familyHint !== family))) { diagnostics.push(error('ATM_FAULT_FINGERPRINT_FAMILY_CONFLICT', 'Family hint conflicts with sealed observation-derived candidates.', observation.observationId, 'run family mapping review from sealed observations')); decision = 'mapping-review'; confidence = Math.min(confidence, 0.49); }
    if (decision === 'mapping-review' || confidence < 0.8) diagnostics.push(error('ATM_FAULT_FINGERPRINT_LOW_CONFIDENCE', `Family match for ${observation.observationId} requires mapping review.`, observation.observationId, 'review public seam, causal impact, and mutation lineage evidence'));
    const fingerprintId = `fault_${digest(key).slice(7, 23)}`;
    return { fingerprintId, observationId: observation.observationId, normalized: key, familyMatch: { family, confidence: Number(confidence.toFixed(3)), decision, evidence: [...new Set(evidence)].sort() } };
  });
  const status = diagnostics.some((entry) => entry.code.includes('AUTHORITY')) ? 'stale' : diagnostics.some((entry) => entry.severity === 'error') ? 'blocked' : 'matched';
  const inputDigest = digest(normalized);
  return { schemaId: FAULT_FINGERPRINT_SCHEMA_ID, specVersion: '0.1.0', runId: normalized.runId, resultId: `fault_fingerprint_${inputDigest.slice(7, 23)}`, authority: normalized.authority, status, fingerprints, diagnostics, provenance: { inputDigest, observationCount: normalized.observations.length, knownFamilies: normalized.knownFamilies } };
}
export const fingerprintFault = createFaultFingerprint;
export function matchSemanticFamily(input: FaultFingerprintInput): FaultFingerprintResult { return createFaultFingerprint(input); }
export function replayFaultFingerprint(input: FaultFingerprintInput, expected: FaultFingerprintResult) { const result = createFaultFingerprint(input); return { deterministic: JSON.stringify(result) === JSON.stringify(expected), result }; }
export function validateFaultFingerprint(result: FaultFingerprintResult) { const diagnostics: FaultDiagnostic[] = []; if (result.schemaId !== FAULT_FINGERPRINT_SCHEMA_ID) diagnostics.push(error('ATM_FAULT_FINGERPRINT_SCHEMA_INVALID', 'Unexpected fingerprint schema id.', 'schemaId')); if (!/^fault_fingerprint_[0-9a-f]{16}$/.test(result.resultId)) diagnostics.push(error('ATM_FAULT_FINGERPRINT_RESULT_ID_INVALID', 'resultId must derive from the input digest.', 'resultId')); if (result.status === 'matched' && result.diagnostics.some((entry) => entry.severity === 'error')) diagnostics.push(error('ATM_FAULT_FINGERPRINT_FALSE_GREEN', 'A matched result cannot contain error diagnostics.', 'status')); return { ok: diagnostics.length === 0, diagnostics }; }
function familyScore(family: FaultFamily, observation: FaultObservation): number { const haystack = `${observation.publicSeam} ${observation.errorClass} ${observation.causalImpact} ${observation.mutationLineage ?? ''}`.toLowerCase(); const terms: Record<FaultFamily, string[]> = { 'shared-index': ['index', 'stage', 'shared'], 'sealed-commit': ['commit', 'sealed', 'delivery'], 'cas-queue': ['cas', 'queue', 'race'], 'foreign-dirty': ['foreign', 'dirty', 'wip'], 'stale-batch': ['stale', 'batch', 'freshness'], 'close-deferral': ['close', 'defer', 'closure'], unknown: [] }; return [...new Set([...(terms[family] ?? []), ...family.split('-')])].filter((term) => haystack.includes(term)).length; }
function directFamilyScore(family: FaultFamily, observation: FaultObservation): number { const haystack = `${observation.publicSeam} ${observation.errorClass} ${observation.causalImpact} ${observation.mutationLineage ?? ''}`.toLowerCase(); const markers: Record<FaultFamily, string[]> = { 'shared-index': ['shared', 'index'], 'sealed-commit': ['sealed', 'commit'], 'cas-queue': ['cas', 'queue'], 'foreign-dirty': ['foreign', 'dirty'], 'stale-batch': ['stale', 'batch'], 'close-deferral': ['close', 'defer'], unknown: [] }; return (markers[family] ?? []).filter((marker) => haystack.includes(marker)).length; }
