import { createHash } from 'node:crypto';
export const QUALITY_AUTHORITY_SCHEMA_ID = 'atm.qualityAuthority.v1' as const;
export type QualityAuthorityStatus = 'proven' | 'stale' | 'blocked' | 'contradictory';
export interface QualityAuthorityInput { readonly authorityId: string; readonly policyEpoch: string; readonly expectedPolicyEpoch: string; readonly policyDigest: string; readonly oracleDigest: string; readonly denominatorDigest: string; readonly verdictDigest: string; readonly protectedSurfaces: readonly string[]; readonly observedProtectedSurfaces: readonly string[]; readonly roleCapabilities: Readonly<Record<string, readonly string[]>>; readonly writerRole: string; }
export interface QualityAuthorityResult { readonly schemaId: typeof QUALITY_AUTHORITY_SCHEMA_ID; readonly specVersion: '0.1.0'; readonly authorityId: string; readonly policyEpoch: string; readonly authority: { readonly policyDigest: string; readonly oracleDigest: string; readonly denominatorDigest: string; readonly verdictDigest: string; readonly sealed: true }; readonly protectedSurfaces: readonly string[]; readonly roleCapabilities: Readonly<Record<string, readonly string[]>>; readonly status: QualityAuthorityStatus; readonly diagnostics: readonly string[]; readonly repairCommand: string | null; readonly authorityDigest: string; }
export function compileQualityAuthority(input: QualityAuthorityInput): QualityAuthorityResult { const n=normalize(input),d:string[]=[]; if(!n.authorityId||!n.policyDigest||!n.oracleDigest||!n.denominatorDigest||!n.verdictDigest)d.push('authority-incomplete'); if(n.policyEpoch!==n.expectedPolicyEpoch)d.push('policy-epoch-drift'); const missing=n.protectedSurfaces.filter(s=>!n.observedProtectedSurfaces.includes(s)); for(const s of missing)d.push(`missing-protected-surface:${s}`); const owned=new Map<string,string>(); for(const [role,caps] of Object.entries(n.roleCapabilities as Record<string,readonly string[]>))for(const cap of caps){if(owned.has(cap)&&owned.get(cap)!==role)d.push(`capability-overlap:${cap}`);owned.set(cap,role);} if((n.roleCapabilities as Record<string,readonly string[]>)[n.writerRole]?.some((cap:string)=>['policy','oracle','denominator','verdict'].includes(cap)))d.push('writer-authority-overlap'); const status:QualityAuthorityStatus=d.some(x=>x.startsWith('capability-overlap')||x==='writer-authority-overlap'||x==='authority-incomplete')?'contradictory':d.some(x=>x==='policy-epoch-drift')?'stale':d.length?'blocked':'proven'; const repairCommand=status==='proven'?null:'restore the sealed prior authority, reconcile policy epoch and protected capabilities, then recompile'; const authority={policyDigest:n.policyDigest,oracleDigest:n.oracleDigest,denominatorDigest:n.denominatorDigest,verdictDigest:n.verdictDigest,sealed:true as const}; return{schemaId:QUALITY_AUTHORITY_SCHEMA_ID,specVersion:'0.1.0',authorityId:n.authorityId,policyEpoch:n.policyEpoch,authority,protectedSurfaces:n.protectedSurfaces,roleCapabilities:n.roleCapabilities,status,diagnostics:d,repairCommand,authorityDigest:digest({authorityId:n.authorityId,policyEpoch:n.policyEpoch,authority,protectedSurfaces:n.protectedSurfaces,roleCapabilities:n.roleCapabilities,status,diagnostics:d})}; }
export const createQualityAuthority=compileQualityAuthority;
export function validateQualityAuthority(r:QualityAuthorityResult){return{ok:r.status==='proven'&&r.repairCommand===null&&r.authority.sealed===true,diagnostics:[...r.diagnostics]};}
function normalize(i:QualityAuthorityInput){const roleCapabilities=Object.fromEntries(Object.entries(i.roleCapabilities??{}).map(([r,c])=>[String(r),[...(c??[])].map(String).sort()] as const).sort((a,b)=>a[0].localeCompare(b[0]))) as Record<string,readonly string[]>;return{authorityId:String(i.authorityId??'').trim(),policyEpoch:String(i.policyEpoch??'').trim(),expectedPolicyEpoch:String(i.expectedPolicyEpoch??'').trim(),policyDigest:String(i.policyDigest??'').trim(),oracleDigest:String(i.oracleDigest??'').trim(),denominatorDigest:String(i.denominatorDigest??'').trim(),verdictDigest:String(i.verdictDigest??'').trim(),protectedSurfaces:[...(i.protectedSurfaces??[])].map(String).sort(),observedProtectedSurfaces:[...(i.observedProtectedSurfaces??[])].map(String).sort(),roleCapabilities,writerRole:String(i.writerRole??'').trim()};}
function digest(v:unknown){return`sha256:${createHash('sha256').update(JSON.stringify(v)).digest('hex')}`;}
