import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { inspectAutoGeneratedResidue, type AutoGeneratedResidueFinding } from './framework-development/closure-packet-schema.ts';
import { makeResult, message, parseOptions, relativePathFrom } from './shared.ts';

type ResidueOwnerState = 'active' | 'released' | 'unknown';

type ResidueEntry = AutoGeneratedResidueFinding & {
  readonly gitStatus: string;
  readonly ownerState: ResidueOwnerState;
  readonly ownerActorId: string | null;
  readonly recommendedAction: 'keep-active-owner' | 'safe-auto-clean' | 'block-and-reconcile' | 'manual-review';
  readonly requiredCommand: string | null;
};

function normalizeRelativePath(value: string): string {
  return value.replace(/\\/g, '/').replace(/^\.\//, '').trim();
}

function readGitStatus(cwd: string): readonly { status: string; path: string }[] {
  const result = spawnSync('git', ['status', '--porcelain=v1', '--untracked-files=all'], {
    cwd,
    encoding: 'utf8'
  });
  if (result.status !== 0) {
    return [];
  }
  return String(result.stdout ?? '')
    .split(/\r?\n/)
    .map((line) => line.trimEnd())
    .filter(Boolean)
    .map((line) => {
      const status = line.slice(0, 2);
      const rawPath = line.slice(3).replace(/^"|"$/g, '');
      return { status, path: normalizeRelativePath(rawPath) };
    });
}

function ownerTaskIdFromPath(filePath: string): string | null {
  const normalized = normalizeRelativePath(filePath);
  const match = normalized.match(/^\.atm\/(?:history\/(?:evidence|tasks|task-events|handoff)|task-plans)\/([^/.\/]+)(?:[/.]|$)/i);
  if (match?.[1]) {
    return match[1].toUpperCase();
  }
  const runtimeMatch = normalized.match(/^\.atm\/runtime\/(?:broker-intents|tmp-[^/]+)\/?([^/.\/]+)?/i);
  return runtimeMatch?.[1] ? runtimeMatch[1].toUpperCase() : null;
}

function readLockOwner(cwd: string, taskId: string | null): { state: ResidueOwnerState; actorId: string | null } {
  if (!taskId) {
    return { state: 'unknown', actorId: null };
  }
  const lockPath = path.join(cwd, '.atm', 'runtime', 'locks', `${taskId}.lock.json`);
  if (!existsSync(lockPath)) {
    return { state: 'unknown', actorId: null };
  }
  try {
    const record = JSON.parse(readFileSync(lockPath, 'utf8')) as Record<string, unknown>;
    const status = typeof record.status === 'string' ? record.status : 'active';
    const actorId = typeof record.actorId === 'string'
      ? record.actorId
      : typeof record.lockedBy === 'string'
        ? record.lockedBy
        : null;
    return {
      state: status === 'active' ? 'active' : status === 'released' ? 'released' : 'unknown',
      actorId
    };
  } catch {
    return { state: 'unknown', actorId: null };
  }
}

function classifyRecommendation(entry: AutoGeneratedResidueFinding, ownerState: ResidueOwnerState): Pick<ResidueEntry, 'recommendedAction' | 'requiredCommand'> {
  if (ownerState === 'active') {
    return {
      recommendedAction: 'keep-active-owner',
      requiredCommand: 'node atm.mjs status --json'
    };
  }
  if (entry.verdict === 'auto-clean-safe') {
    return {
      recommendedAction: 'safe-auto-clean',
      requiredCommand: 'node atm.mjs residue status --json'
    };
  }
  if (entry.verdict === 'block-and-explain') {
    return {
      recommendedAction: 'block-and-reconcile',
      requiredCommand: 'node atm.mjs tasks status --task <owner-task-id> --residue --json'
    };
  }
  return {
    recommendedAction: 'manual-review',
    requiredCommand: null
  };
}

function normalizeWorkspaceResidueFinding(filePath: string, finding: AutoGeneratedResidueFinding): AutoGeneratedResidueFinding {
  const normalized = normalizeRelativePath(filePath);
  if (/^\.atm\/runtime\/tmp-[^/]+\.(?:json|txt)$/i.test(normalized)) {
    return {
      path: normalized,
      verdict: 'auto-clean-safe',
      reason: 'ATM runtime tmp output is a command transcript/cache artifact and is disposable after the originating command completes.',
      ownerTaskId: ownerTaskIdFromPath(normalized),
      cleanupAction: 'remove'
    };
  }
  return finding;
}

function listKnownRuntimeFiles(cwd: string): string[] {
  const roots = [
    path.join(cwd, '.atm', 'runtime', 'broker-conflict-resolutions'),
    path.join(cwd, '.atm', 'runtime', 'git-push-attempts'),
    path.join(cwd, '.atm', 'runtime', 'incidents')
  ];
  const files: string[] = [];
  for (const root of roots) {
    if (!existsSync(root)) continue;
    for (const entry of readdirSync(root, { recursive: true, withFileTypes: true })) {
      if (!entry.isFile()) continue;
      files.push(relativePathFrom(cwd, path.join(entry.parentPath, entry.name)));
    }
  }
  return files.map(normalizeRelativePath);
}

export function buildResidueStatusReport(cwd: string) {
  const gitEntries = readGitStatus(cwd);
  const candidatePaths = [...new Set([
    ...gitEntries.map((entry) => entry.path).filter((filePath) => filePath.startsWith('.atm/')),
    ...listKnownRuntimeFiles(cwd)
  ])].sort((left, right) => left.localeCompare(right));
  const residueReport = inspectAutoGeneratedResidue(null, candidatePaths);
  const byPath = new Map([
    ...residueReport.autoCleanSafe,
    ...residueReport.blockAndExplain,
    ...residueReport.manualReview
  ].map((entry) => [normalizeRelativePath(entry.path), entry]));
  const gitStatusByPath = new Map(gitEntries.map((entry) => [entry.path, entry.status.trim() || 'dirty']));
  const entries: ResidueEntry[] = [];
  for (const filePath of candidatePaths) {
    const finding = byPath.get(filePath);
    if (!finding) continue;
    const normalizedFinding = normalizeWorkspaceResidueFinding(filePath, finding);
    const ownerTaskId = normalizedFinding.ownerTaskId ?? ownerTaskIdFromPath(filePath);
    const owner = readLockOwner(cwd, ownerTaskId);
    const recommendation = classifyRecommendation(normalizedFinding, owner.state);
    entries.push({
      ...normalizedFinding,
      ownerTaskId,
      gitStatus: gitStatusByPath.get(filePath) ?? 'runtime',
      ownerState: owner.state,
      ownerActorId: owner.actorId,
      ...recommendation
    });
  }
  const buckets = {
    activeOwner: entries.filter((entry) => entry.ownerState === 'active').length,
    autoCleanSafe: entries.filter((entry) => entry.recommendedAction === 'safe-auto-clean').length,
    blockAndReconcile: entries.filter((entry) => entry.recommendedAction === 'block-and-reconcile').length,
    manualReview: entries.filter((entry) => entry.recommendedAction === 'manual-review').length
  };
  return {
    schemaId: 'atm.residueStatusReport.v1',
    generatedAt: new Date().toISOString(),
    dryRun: true,
    totalCount: entries.length,
    buckets,
    entries
  };
}

export function runResidue(argv: string[]) {
  const { positional, options } = parseOptions(argv, 'residue');
  const action = positional[0] ?? 'status';
  if (action !== 'status') {
    return makeResult({
      ok: false,
      command: 'residue',
      cwd: options.cwd,
      messages: [message('error', 'ATM_RESIDUE_UNKNOWN_ACTION', `Unknown residue action: ${action}`)],
      evidence: {
        allowedActions: ['status']
      }
    });
  }
  const report = buildResidueStatusReport(options.cwd);
  return makeResult({
    ok: true,
    command: 'residue',
    cwd: options.cwd,
    messages: [message('info', 'ATM_RESIDUE_STATUS_READY', 'Residue status is ready. This command is read-only and does not delete files.', {
      totalCount: report.totalCount,
      buckets: report.buckets
    })],
    evidence: {
      action,
      report
    }
  });
}
