import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, rmSync, rmdirSync, statSync } from 'node:fs';
import path from 'node:path';
import { inspectAutoGeneratedResidue, type AutoGeneratedResidueFinding } from './framework-development/closure-packet-schema.ts';
import { makeResult, message, parseOptions, relativePathFrom } from './shared.ts';

type ResidueOwnerState = 'active' | 'released' | 'expired' | 'unknown';
type ResidueIndexState = 'staged' | 'unstaged' | 'untracked' | 'runtime';
type ResidueOwnerLockKind = 'governance-lock' | 'close-commit-window' | null;

type ResidueEntry = AutoGeneratedResidueFinding & {
  readonly gitStatus: string;
  readonly indexState: ResidueIndexState;
  readonly sharedIndexRisk: boolean;
  readonly ownerState: ResidueOwnerState;
  readonly ownerActorId: string | null;
  readonly ownerLockKind: ResidueOwnerLockKind;
  readonly ownerLockPath: string | null;
  readonly recommendedAction: 'keep-active-owner' | 'safe-auto-clean' | 'block-and-reconcile' | 'manual-review';
  readonly requiredCommand: string | null;
};

type ResidueReconcileAction = {
  readonly path: string;
  readonly action: 'remove';
  readonly applied: boolean;
  readonly reason: string;
};

function normalizeRelativePath(value: string): string {
  return value.replace(/\\/g, '/').replace(/^\.\//, '').trim();
}

function readGitStatus(cwd: string): readonly { status: string; path: string }[] {
  const result = spawnSync('git', ['status', '--porcelain=v1', '--untracked-files=all'], {
    cwd,
    encoding: 'utf8'
  });
  if (result.status !== 0) {
    return [];
  }
  return String(result.stdout ?? '')
    .split(/\r?\n/)
    .map((line) => line.trimEnd())
    .filter(Boolean)
    .map((line) => {
      const status = line.slice(0, 2);
      const rawPath = line.slice(3).replace(/^"|"$/g, '');
      return { status, path: normalizeRelativePath(rawPath) };
    });
}

function ownerTaskIdFromPath(filePath: string): string | null {
  const normalized = normalizeRelativePath(filePath);
  const match = normalized.match(/^\.atm\/(?:history\/(?:evidence|tasks|task-events|handoff)|task-plans)\/([^/.\/]+)(?:[/.]|$)/i);
  if (match?.[1]) {
    return match[1].toUpperCase();
  }
  const runtimeMatch = normalized.match(/^\.atm\/runtime\/(?:broker-intents|tmp-[^/]+)\/?([^/.\/]+)?/i);
  return runtimeMatch?.[1] ? runtimeMatch[1].toUpperCase() : null;
}

function readTaskStatus(cwd: string, taskId: string | null): string | null {
  if (!taskId) return null;
  const taskPath = path.join(cwd, '.atm', 'history', 'tasks', `${taskId}.json`);
  if (!existsSync(taskPath)) return null;
  try {
    const parsed = JSON.parse(readFileSync(taskPath, 'utf8')) as Record<string, unknown>;
    return typeof parsed.status === 'string' ? parsed.status.toLowerCase() : null;
  } catch {
    return null;
  }
}

function classifyIndexState(gitStatus: string): ResidueIndexState {
  if (gitStatus === 'runtime') return 'runtime';
  if (gitStatus === '??') return 'untracked';
  if (gitStatus[0] && gitStatus[0] !== ' ') return 'staged';
  return 'unstaged';
}

function readCloseCommitWindowOwner(
  cwd: string,
  taskId: string | null,
  filePath: string
): { state: ResidueOwnerState; actorId: string | null; lockKind: ResidueOwnerLockKind; lockPath: string | null } | null {
  if (!taskId) return null;
  const lockPath = path.join(cwd, '.atm', 'runtime', 'locks', `close-commit-window-${taskId}.lock.json`);
  if (!existsSync(lockPath)) return null;
  try {
    const record = JSON.parse(readFileSync(lockPath, 'utf8')) as Record<string, unknown>;
    if (record.schemaId !== 'atm.closeCommitWindow.v1') return null;
    const allowedFiles = Array.isArray(record.allowedFiles)
      ? record.allowedFiles.map((entry) => typeof entry === 'string' ? normalizeRelativePath(entry) : '').filter(Boolean)
      : [];
    if (allowedFiles.length > 0 && !allowedFiles.includes(normalizeRelativePath(filePath))) return null;
    const expiresAt = new Date(String(record.expiresAt ?? ''));
    const expired = Number.isNaN(expiresAt.getTime()) || expiresAt.getTime() <= Date.now();
    return {
      state: expired ? 'expired' : 'active',
      actorId: typeof record.actorId === 'string' ? record.actorId : null,
      lockKind: 'close-commit-window',
      lockPath: relativePathFrom(cwd, lockPath)
    };
  } catch {
    return null;
  }
}

function readLockOwner(
  cwd: string,
  taskId: string | null,
  filePath: string
): { state: ResidueOwnerState; actorId: string | null; lockKind: ResidueOwnerLockKind; lockPath: string | null } {
  const closeWindow = readCloseCommitWindowOwner(cwd, taskId, filePath);
  if (closeWindow) return closeWindow;
  if (!taskId) {
    return { state: 'unknown', actorId: null, lockKind: null, lockPath: null };
  }
  const lockPath = path.join(cwd, '.atm', 'runtime', 'locks', `${taskId}.lock.json`);
  if (!existsSync(lockPath)) {
    return { state: 'unknown', actorId: null, lockKind: null, lockPath: null };
  }
  try {
    const record = JSON.parse(readFileSync(lockPath, 'utf8')) as Record<string, unknown>;
    const status = typeof record.status === 'string' ? record.status : 'active';
    const actorId = typeof record.actorId === 'string'
      ? record.actorId
      : typeof record.lockedBy === 'string'
        ? record.lockedBy
        : null;
    return {
      state: status === 'active' ? 'active' : status === 'released' ? 'released' : 'unknown',
      actorId,
      lockKind: 'governance-lock',
      lockPath: relativePathFrom(cwd, lockPath)
    };
  } catch {
    return { state: 'unknown', actorId: null, lockKind: null, lockPath: null };
  }
}

function classifyRecommendation(
  entry: AutoGeneratedResidueFinding,
  ownerState: ResidueOwnerState,
  indexState: ResidueIndexState
): Pick<ResidueEntry, 'recommendedAction' | 'requiredCommand'> {
  if (ownerState === 'active') {
    return {
      recommendedAction: 'keep-active-owner',
      requiredCommand: 'node atm.mjs status --json'
    };
  }
  if (indexState === 'staged' && entry.ownerTaskId) {
    return {
      recommendedAction: 'manual-review',
      requiredCommand: `node atm.mjs tasks status --task ${entry.ownerTaskId} --json`
    };
  }
  if (entry.verdict === 'auto-clean-safe') {
    return {
      recommendedAction: 'safe-auto-clean',
      requiredCommand: 'node atm.mjs residue status --json'
    };
  }
  if (entry.verdict === 'block-and-explain') {
    return {
      recommendedAction: 'block-and-reconcile',
      requiredCommand: 'node atm.mjs tasks status --task <owner-task-id> --residue --json'
    };
  }
  return {
    recommendedAction: 'manual-review',
    requiredCommand: null
  };
}

function normalizeWorkspaceResidueFinding(cwd: string, filePath: string, finding: AutoGeneratedResidueFinding): AutoGeneratedResidueFinding {
  const normalized = normalizeRelativePath(filePath);
  if (/^\.atm\/runtime\/tmp-[^/]+\.(?:json|txt)$/i.test(normalized)) {
    return {
      path: normalized,
      verdict: 'auto-clean-safe',
      reason: 'ATM runtime tmp output is a command transcript/cache artifact and is disposable after the originating command completes.',
      ownerTaskId: ownerTaskIdFromPath(normalized),
      cleanupAction: 'remove'
    };
  }
  if (/^\.atm\/runtime\/(?:git-push-attempts|broker-conflict-resolutions|broker-intents)\//i.test(normalized)
    || /^\.atm\/runtime\/(?:broker-shared-surface-freezes\.json|framework-lock-auto-reconcile\.jsonl)$/i.test(normalized)) {
    return {
      path: normalized,
      verdict: 'auto-clean-safe',
      reason: 'ATM runtime reconciliation artifact is disposable after the originating governance command has completed and no active owner lock protects it.',
      ownerTaskId: ownerTaskIdFromPath(normalized),
      cleanupAction: 'remove'
    };
  }
  const ownerTaskId = finding.ownerTaskId ?? ownerTaskIdFromPath(normalized);
  if (readTaskStatus(cwd, ownerTaskId) === 'abandoned'
    && /^\.atm\/(?:history\/(?:evidence|tasks|task-events|handoff)|task-plans)\//i.test(normalized)) {
    return {
      path: normalized,
      verdict: 'auto-clean-safe',
      reason: 'Artifact belongs to an abandoned ATM task and has no active owner lock; it is disposable governance residue.',
      ownerTaskId,
      cleanupAction: 'remove'
    };
  }
  return finding;
}

function listKnownRuntimeFiles(cwd: string): string[] {
  const roots = [
    path.join(cwd, '.atm', 'runtime', 'broker-conflict-resolutions'),
    path.join(cwd, '.atm', 'runtime', 'git-push-attempts'),
    path.join(cwd, '.atm', 'runtime', 'incidents')
  ];
  const files: string[] = [];
  for (const root of roots) {
    if (!existsSync(root)) continue;
    for (const entry of readdirSync(root, { recursive: true, withFileTypes: true })) {
      if (!entry.isFile()) continue;
      files.push(relativePathFrom(cwd, path.join(entry.parentPath, entry.name)));
    }
  }
  for (const filePath of [
    path.join(cwd, '.atm', 'runtime', 'broker-shared-surface-freezes.json'),
    path.join(cwd, '.atm', 'runtime', 'framework-lock-auto-reconcile.jsonl')
  ]) {
    if (existsSync(filePath)) {
      files.push(relativePathFrom(cwd, filePath));
    }
  }
  return files.map(normalizeRelativePath);
}

export function buildResidueStatusReport(cwd: string) {
  const gitEntries = readGitStatus(cwd);
  const candidatePaths = [...new Set([
    ...gitEntries.map((entry) => entry.path).filter((filePath) => filePath.startsWith('.atm/')),
    ...listKnownRuntimeFiles(cwd)
  ])].sort((left, right) => left.localeCompare(right));
  const residueReport = inspectAutoGeneratedResidue(null, candidatePaths);
  const byPath = new Map([
    ...residueReport.autoCleanSafe,
    ...residueReport.blockAndExplain,
    ...residueReport.manualReview
  ].map((entry) => [normalizeRelativePath(entry.path), entry]));
  const gitStatusByPath = new Map(gitEntries.map((entry) => [entry.path, entry.status]));
  const entries: ResidueEntry[] = [];
  for (const filePath of candidatePaths) {
    const finding = byPath.get(filePath);
    if (!finding) continue;
    const normalizedFinding = normalizeWorkspaceResidueFinding(cwd, filePath, finding);
    const ownerTaskId = normalizedFinding.ownerTaskId ?? ownerTaskIdFromPath(filePath);
    const rawGitStatus = gitStatusByPath.get(filePath) ?? 'runtime';
    const gitStatus = rawGitStatus === 'runtime' ? rawGitStatus : rawGitStatus.trim() || 'dirty';
    const indexState = classifyIndexState(rawGitStatus);
    const owner = readLockOwner(cwd, ownerTaskId, filePath);
    const normalizedFindingWithOwner = { ...normalizedFinding, ownerTaskId };
    const recommendation = classifyRecommendation(normalizedFindingWithOwner, owner.state, indexState);
    entries.push({
      ...normalizedFinding,
      ownerTaskId,
      gitStatus,
      indexState,
      sharedIndexRisk: indexState === 'staged',
      ownerState: owner.state,
      ownerActorId: owner.actorId,
      ownerLockKind: owner.lockKind,
      ownerLockPath: owner.lockPath,
      ...recommendation
    });
  }
  const buckets = {
    activeOwner: entries.filter((entry) => entry.ownerState === 'active').length,
    autoCleanSafe: entries.filter((entry) => entry.recommendedAction === 'safe-auto-clean').length,
    blockAndReconcile: entries.filter((entry) => entry.recommendedAction === 'block-and-reconcile').length,
    manualReview: entries.filter((entry) => entry.recommendedAction === 'manual-review').length
  };
  return {
    schemaId: 'atm.residueStatusReport.v1',
    generatedAt: new Date().toISOString(),
    dryRun: true,
    totalCount: entries.length,
    buckets,
    entries
  };
}

function isSafeReconcileEntry(entry: ResidueEntry): boolean {
  return entry.recommendedAction === 'safe-auto-clean'
    && entry.cleanupAction === 'remove'
    && entry.ownerState !== 'active'
    && !entry.sharedIndexRisk;
}

function assertWorkspacePath(cwd: string, relativePath: string): string {
  const root = path.resolve(cwd);
  const resolved = path.resolve(root, normalizeRelativePath(relativePath));
  if (resolved !== root && !resolved.startsWith(`${root}${path.sep}`)) {
    throw new Error(`Refusing to reconcile path outside workspace: ${relativePath}`);
  }
  return resolved;
}

function removeEmptyParents(cwd: string, absolutePath: string): void {
  const root = path.resolve(cwd, '.atm');
  let current = path.dirname(absolutePath);
  while (current.startsWith(root) && current !== root) {
    try {
      rmdirSync(current);
      current = path.dirname(current);
    } catch {
      break;
    }
  }
}

export function buildResidueReconcileReport(cwd: string, apply: boolean) {
  const statusReport = buildResidueStatusReport(cwd);
  const actions: ResidueReconcileAction[] = [];
  const deferred = statusReport.entries.filter((entry) => !isSafeReconcileEntry(entry));
  for (const entry of statusReport.entries.filter(isSafeReconcileEntry)) {
    const absolutePath = assertWorkspacePath(cwd, entry.path);
    const exists = existsSync(absolutePath);
    if (apply && exists) {
      const stat = statSync(absolutePath);
      rmSync(absolutePath, { recursive: stat.isDirectory(), force: true });
      removeEmptyParents(cwd, absolutePath);
    }
    actions.push({
      path: entry.path,
      action: 'remove',
      applied: apply && exists,
      reason: entry.reason
    });
  }
  return {
    schemaId: 'atm.residueReconcileReport.v1',
    generatedAt: new Date().toISOString(),
    dryRun: !apply,
    statusReport,
    actionCount: actions.length,
    appliedCount: actions.filter((action) => action.applied).length,
    deferredCount: deferred.length,
    actions,
    deferred
  };
}

export function runResidue(argv: string[]) {
  const { positional, options } = parseOptions(argv, 'residue');
  const action = positional[0] ?? 'status';
  if (!['status', 'reconcile'].includes(action)) {
    return makeResult({
      ok: false,
      command: 'residue',
      cwd: options.cwd,
      messages: [message('error', 'ATM_RESIDUE_UNKNOWN_ACTION', `Unknown residue action: ${action}`)],
      evidence: {
        allowedActions: ['status', 'reconcile']
      }
    });
  }
  if (action === 'reconcile') {
    const report = buildResidueReconcileReport(options.cwd, options.apply);
    return makeResult({
      ok: true,
      command: 'residue',
      cwd: options.cwd,
      messages: [message('info', options.apply ? 'ATM_RESIDUE_RECONCILE_APPLIED' : 'ATM_RESIDUE_RECONCILE_READY', options.apply
        ? 'Residue reconcile applied safe owner-aware cleanup actions.'
        : 'Residue reconcile dry-run is ready. Re-run with --apply to remove safe disposable residue.', {
        actionCount: report.actionCount,
        appliedCount: report.appliedCount,
        deferredCount: report.deferredCount
      })],
      evidence: {
        action,
        report
      }
    });
  }
  const report = buildResidueStatusReport(options.cwd);
  return makeResult({
    ok: true,
    command: 'residue',
    cwd: options.cwd,
    messages: [message('info', 'ATM_RESIDUE_STATUS_READY', 'Residue status is ready. This command is read-only and does not delete files.', {
      totalCount: report.totalCount,
      buckets: report.buckets
    })],
    evidence: {
      action,
      report
    }
  });
}
