// ATM-BUG-2026-07-07-052 (OPT-14) regression test.
//
// `.atm/history/protected-override-audit/*.json` events are the durable
// record of an emergency/hook-bypass lane (what was authorized, by whom, and
// whether it succeeded). They were previously classified as disposable
// "auto-clean-safe" residue by `classifyAutoGeneratedResidue()` and
// physically deleted by `cleanupAutoGeneratedResidue()` the next time any
// task ran `git commit` -- so `emergency audit --task <id>` could report the
// eventPath at authorization time, then find nothing once the first
// unrelated commit swept the worktree clean. Confirm:
//   1. A this-task-owned audit event survives `resolveTaskScopedCommitBundle`
//      and is staged into the commit bundle (not deleted, not left as
//      unexplained external residue).
//   2. A different task's pending audit event is left untouched (not
//      deleted, not swept into this commit) so it can't trip a governance
//      bundle task-mismatch on an unrelated commit.
//
// Runnable directly via:
//   node --strip-types tests/cli/protected-override-audit-staging.test.ts

import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { resolveTaskScopedCommitBundle } from '../../packages/cli/src/commands/git-governance.ts';
import { recordProtectedOverrideAuditEvent } from '../../packages/cli/src/commands/emergency/protected-override-audit.ts';

function runGit(cwd: string, args: string[]) {
  return execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
}

const repo = mkdtempSync(path.join(os.tmpdir(), 'atm-protected-override-audit-staging-'));

runGit(repo, ['init']);
runGit(repo, ['config', 'user.name', 'ATM Validator']);
runGit(repo, ['config', 'user.email', 'validator@example.invalid']);
runGit(repo, ['commit', '--allow-empty', '-m', 'bootstrap']);

const taskId = 'TASK-OPT14-TEST';

mkdirSync(path.join(repo, 'src'), { recursive: true });
writeFileSync(path.join(repo, 'src/app.ts'), 'export const value = 1;\n', 'utf8');

const ownedAudit = recordProtectedOverrideAuditEvent({
  cwd: repo,
  actorId: 'opt14-actor',
  taskId,
  surface: 'tasks.close',
  command: 'node atm.mjs tasks close --task TASK-OPT14-TEST',
  flags: ['--no-verify'],
  permission: 'backend.tasks.close',
  leaseId: 'lease-opt14-test',
  reason: 'regression fixture',
  outcome: 'authorized'
});
const ownedAuditAbsolutePath = path.join(repo, ownedAudit.eventPath);
assert.ok(existsSync(ownedAuditAbsolutePath), 'fixture must actually write the this-task audit event to disk');

const foreignAudit = recordProtectedOverrideAuditEvent({
  cwd: repo,
  actorId: 'other-actor',
  taskId: 'TASK-FOREIGN-9999',
  surface: 'tasks.close',
  command: 'node atm.mjs tasks close --task TASK-FOREIGN-9999',
  flags: ['--no-verify'],
  permission: 'backend.tasks.close',
  leaseId: 'lease-foreign-9999',
  reason: 'regression fixture (foreign task)',
  outcome: 'authorized'
});
const foreignAuditAbsolutePath = path.join(repo, foreignAudit.eventPath);
assert.ok(existsSync(foreignAuditAbsolutePath), 'fixture must actually write the foreign-task audit event to disk');

const taskDocument = {
  taskDirectionLock: { allowedFiles: ['src/app.ts'] }
};

const report = resolveTaskScopedCommitBundle({
  cwd: repo,
  taskId,
  taskDocument,
  apply: true,
  autoStage: true,
  deferForeignStaged: false,
  message: 'feat: opt-14 fixture commit',
  actorId: 'opt14-actor',
  trailers: []
});

assert.equal(report.ok, true, `commit bundle resolution must not be blocked: ${JSON.stringify({ blockedCode: report.blockedCode, blockedSummary: report.blockedSummary })}`);

// --- This-task-owned audit event: must survive and be staged.
assert.ok(existsSync(ownedAuditAbsolutePath), 'this-task audit event must not be deleted by residue cleanup');
assert.ok(
  report.autoCleanedResidue.every((entry) => entry.path !== ownedAudit.eventPath),
  `this-task audit event must not be classified as auto-clean-safe residue: ${JSON.stringify(report.autoCleanedResidue)}`
);
assert.ok(
  report.stageFiles.includes(ownedAudit.eventPath) || report.commitFiles.includes(ownedAudit.eventPath),
  `this-task audit event must be staged into the commit bundle: stageFiles=${JSON.stringify(report.stageFiles)} commitFiles=${JSON.stringify(report.commitFiles)}`
);
assert.ok(
  !report.skippedExternalDirtyFiles.includes(ownedAudit.eventPath),
  'this-task audit event must not be reported as an unexplained skipped external file'
);

// --- Foreign-task audit event: must survive but stay untouched by this commit.
assert.ok(existsSync(foreignAuditAbsolutePath), 'foreign-task audit event must not be deleted by residue cleanup');
assert.ok(
  report.autoCleanedResidue.every((entry) => entry.path !== foreignAudit.eventPath),
  `foreign-task audit event must not be classified as auto-clean-safe residue either: ${JSON.stringify(report.autoCleanedResidue)}`
);
assert.ok(
  !report.stageFiles.includes(foreignAudit.eventPath) && !report.commitFiles.includes(foreignAudit.eventPath),
  `foreign-task audit event must not be swept into an unrelated task's commit: stageFiles=${JSON.stringify(report.stageFiles)} commitFiles=${JSON.stringify(report.commitFiles)}`
);
assert.ok(
  report.blockedResidue.every((entry) => entry.path !== foreignAudit.eventPath),
  'foreign-task audit event must not block this commit either (it should simply be left alone)'
);

// `resolveTaskScopedCommitBundle` only stages files (git add); finish the
// commit itself to prove the staged audit event actually lands in history.
runGit(repo, ['commit', '-m', 'feat: opt-14 fixture commit']);
const committedFiles = runGit(repo, ['show', '--stat', '--name-only', 'HEAD']).trim().split(/\r?\n/);
assert.ok(
  committedFiles.includes(ownedAudit.eventPath.replace(/\\/g, '/')),
  `this-task audit event must actually land in the commit: ${JSON.stringify(committedFiles)}`
);
assert.ok(
  !committedFiles.includes(foreignAudit.eventPath.replace(/\\/g, '/')),
  `foreign-task audit event must not land in this commit: ${JSON.stringify(committedFiles)}`
);

console.log('[protected-override-audit-staging:test] ok');
