// Candidate publication must re-download exact public bytes, run the existing
// full lifecycle, then promote. These checks complement injected failure tests;
// they never access npm or perform a registry mutation.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const read = (file: string) => readFileSync(path.join(root, file), 'utf8');
const workflow = read('.github/workflows/release-npm.yml');
const candidate = read('scripts/release-candidate.ts');
const publicProof = read('scripts/validate-public-npm-install.ts');
const starter = read('scripts/validate-public-starter.sh');
assert.match(workflow, /scripts\/release-candidate\.ts/);
assert.match(workflow, /--manifest release\/npm-artifacts\/manifest\.json/);
assert.match(workflow, /--target-tag "\$NPM_DIST_TAG"/);
assert.match(workflow, /RELEASE_DRY_RUN.*true.*dry_run=\(--dry-run\)/);
assert.match(candidate, /process\.argv\.includes\('--dry-run'\)[\s\S]*?publicRegistryVerified: false[\s\S]*?return;/);
assert.doesNotMatch(candidate, /--record-blocked|--require-default-tag/);
assert.match(candidate, /scripts\/validate-public-npm-install\.ts', '--version', manifest\.version/);
assert.match(candidate, /'--artifact-manifest', manifestPath, '--expected-tag', candidateTag/);
assert.match(candidate, /verifyArtifact\(manifest, artifact, downloaded\)/);
assert.match(candidate, /'--cache', cache, '--prefer-online'/);
assert.match(candidate, /attempt < 40/);
assert.match(candidate, /attempt === 39 \|\| Date.now\(\) >= registryDeadline\) throw error/);
assert.ok(candidate.indexOf('io.publish(artifact, candidateTag)') < candidate.indexOf('io.lifecycle(candidateTag)'));
assert.ok(candidate.indexOf('io.lifecycle(candidateTag)') < candidate.indexOf('io.setTag(artifact.name, artifact.version, targetTag)'));
assert.match(candidate, /scripts\/validate-public-starter\.sh/);
for (const operation of ['taskflow open', 'next --claim', 'evidence run', 'taskflow close']) assert.ok(starter.includes(operation));
assert.match(publicProof, /expectedTag && distTags\?\.\[args\.expectedTag\] !== args\.version/);
assert.match(publicProof, /runtime\.sourceCommit !== candidateManifest\.sourceCommit/);
assert.match(workflow, /name: Attach immutable artifacts and promotion proof[\s\S]*?actions\/upload-artifact@v4[\s\S]*?path: release\/npm-artifacts/);
assert.match(candidate, /promotion-attempt-/);
assert.match(candidate, /flag: 'a'/);
assert.match(workflow, /npm@11\.21\.0/);
assert.match(candidate, /io\.preflight\(candidateTag\)/);
console.log('[release-public-registry-gate.test] ok');
