import { execFileSync } from 'node:child_process'; import { createHash } from 'node:crypto'; import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import { buildTaskflowCommitMessage } from './commit-messages.ts'; import { withCloseTransactionMutex } from './close-transaction-mutex.ts';
import { expandDirectoryDeliverableDeclarations } from '../tasks/historical-delivery.ts'; import { loadTaskDocumentOrThrow } from '../tasks/public-surface.ts'; import { assertCloseWindowStagingAllowed } from '../tasks/close-window-lock.ts'; import { validateStrictPathHeuristic } from '../tasks/task-import-validators.ts'; import { listOptionalEvidenceBundleGovernanceArtifacts } from './closeback-orchestration.ts';
import { resolveTaskflowDeclaredFiles, resolveTaskflowEffectiveDeliverables } from './task-scope.ts'; import { listTaskOwnedProtectedOverrideAuditFiles, resolveActorGitIdentityForCommit, runAtmGit } from '../git-governance.ts'; import { resolveCommitLaneSessionId } from '../git-governance/implementation.ts'; import { resolveActorWorkSession } from '../actor-session.ts'; import { resolvePlanningPathFromStored } from '../planning-repo-root.ts'; import { CliError, quoteCliValue } from '../shared.ts'; import { isPathAllowedByScope } from '../work-channels.ts';
import { normalizeMarkdownPathDeclaration } from './markdown-paths.ts'; import type { TeamContributionCompositionResult } from '../team/composer.ts'; import { buildGitIndexLeaseParkPlan, inspectGitIndexOwnership, parkGitIndexLease, restoreGitIndexLease, type GitIndexLeaseParkPlan } from '../git-index-ownership.ts'; export type TaskflowCommitMode = 'auto-commit' | 'stage-only' | 'dry-run';
export interface TaskflowIndexIsolation { verified: boolean; expectedStageFiles: string[]; preStagedFiles: string[]; unexpectedStagedFiles: string[]; indexLease: GitIndexLeaseParkPlan; } export interface TaskflowCommitRepoBundle { repoRoot: string | null; stageFiles: string[]; commitMessage: string; commitCommand: string; commitSha: string | null;
status: 'preview' | 'staged' | 'committed' | 'skipped' | 'failed' | 'uncomputed'; reason?: string | null; indexIsolation?: TaskflowIndexIsolation; } export interface TaskflowSealAndCommitReceipt { schemaId: 'atm.taskflowSealAndCommitReceipt.v1'; taskId: string; actorId: string | null; createdAt: string; targetHeadBeforeCommit: string | null; planningHeadBeforeCommit: string | null; historicalDeliveryRefs: string[];
historicalBatchRef: string | null; manifestPath: string; targetPayloadDigest: string; targetEvidenceDigest: string; planningPayloadDigest: string; planningEvidenceDigest: string; sealDigest: string; } export interface TaskflowScopeAmendmentProposal { required: boolean; candidateFiles: string[]; reason: string | null; remediationCommand: string | null; humanReviewRequired: boolean; notes: string[]; }
export interface TaskflowGovernedCommitBundle { schemaId: 'atm.taskflowGovernedCommitBundle.v1'; taskId: string; actorId: string | null; targetRepo: TaskflowCommitRepoBundle; planningRepo: TaskflowCommitRepoBundle; commitMode: TaskflowCommitMode; failClosed: boolean; recoveryCommand: string | null; targetDeliveryFiles: string[]; targetGovernanceFiles: string[]; planningFiles: string[]; excludedDirtyFiles: string[];
excludedReasons: Record<string, string>; scopeAmendment: TaskflowScopeAmendmentProposal; sealAndCommitReceipt: TaskflowSealAndCommitReceipt; } export interface TaskflowDeliveryCommit { repoRoot: string; stageFiles: string[]; commitMessage: string; commitSha: string | null; status: 'committed'; } export interface DeferredGovernanceDirtyFile { file: string; snapshotPath: string; originalSha256: string;
restoredAt: string | null; skipReason?: 'snapshot-missing' | null; } export interface DeferredGovernanceDirtyReport { schemaId: 'atm.deferredGovernanceDirty.v1'; requested: boolean; files: DeferredGovernanceDirtyFile[]; restored: boolean; skippedMissingSnapshots?: readonly string[]; } function uniqueSorted(values: readonly string[]): string[] {
return [...new Set(values.map((value) => value.replace(/\\/g, '/')).filter(Boolean))].sort((a, b) => a.localeCompare(b)); } function normalizeTaskflowRelativePath(filePath: string): string { return normalizeMarkdownPathDeclaration(filePath).replace(/^\.\//, ''); } function normalizeRepoRelativePath(repoRoot: string, filePath: string): string {
const resolved = path.isAbsolute(filePath) ? filePath : path.resolve(repoRoot, filePath); return path.relative(repoRoot, resolved).replace(/\\/g, '/'); } function listExistingFilesRecursively(root: string, relativeDirectory: string): string[] { const directory = path.join(root, relativeDirectory); if (!existsSync(directory)) return []; const files: string[] = [];
for (const entry of readdirSync(directory, { withFileTypes: true })) { const relativePath = path.posix.join(relativeDirectory.replace(/\\/g, '/'), entry.name); const absolutePath = path.join(root, relativePath); if (entry.isDirectory()) { files.push(...listExistingFilesRecursively(root, relativePath)); } else if (entry.isFile()) { files.push(normalizeRepoRelativePath(root, absolutePath)); } } return files; }
function listCurrentTaskGovernanceFiles(root: string, taskId: string): string[] { const taskFiles = [ `.atm/history/tasks/${taskId}.json`, `.atm/history/evidence/${taskId}.json`, `.atm/history/evidence/${taskId}.closure-packet.json` ].filter((filePath) => existsSync(path.join(root, filePath))); const taskEvents = listExistingFilesRecursively(root, `.atm/history/task-events/${taskId}`);
const handoffHistory = listExistingFilesRecursively(root, `.atm/history/handoff/${taskId}`); return uniqueSorted([...taskFiles, ...taskEvents, ...handoffHistory]); } function tryGitScalar(cwd: string, args: readonly string[]): string | null { try { return execFileSync('git', [...args], { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim() || null; } catch { return null; } }
function runGitOrThrow(cwd: string, args: readonly string[]) { execFileSync('git', [...args], { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }); } function runGitWithEnv(cwd: string, args: readonly string[], env: NodeJS.ProcessEnv) { execFileSync('git', [...args], { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], env }); } function resolveTaskflowCommitLaneSessionId(input: { repoRoot: string; actorId?: string | null; taskId?: string | null; }): string | null { const session = input.actorId && input.taskId ? resolveActorWorkSession(input.repoRoot, { actorId: input.actorId, taskId: input.taskId, includeNonActive: true }) : null; return resolveCommitLaneSessionId({ session }); } function readGitRoot(startPath: string): string | null {
const probe = existsSync(startPath) && statSync(startPath).isDirectory() ? startPath : path.dirname(startPath); const root = tryGitScalar(probe, ['rev-parse', '--show-toplevel']); return root ? path.resolve(root) : null; } function sha256Text(value: string): string { return createHash('sha256').update(value).digest('hex'); } function sha256Json(value: unknown): string {
return `sha256:${sha256Text(`${JSON.stringify(value, null, 2)}\n`)}`; } function taskflowSealManifestPath(taskId: string): string { return `.atm/history/evidence/${taskId}.seal-and-commit.json`; } function readPayloadEntries(repoRoot: string | null, stageFiles: readonly string[], excludeFiles: readonly string[] = []) { if (!repoRoot) return [];
const excluded = new Set(excludeFiles.map((entry) => entry.replace(/\\/g, '/'))); return uniqueSorted(stageFiles) .filter((file) => !excluded.has(file)) .filter((file) => existsSync(path.resolve(repoRoot, file))) .map((file) => { const absolutePath = path.resolve(repoRoot, file); return { path: file, sha256: `sha256:${sha256Text(readFileSync(absolutePath, 'utf8'))}` }; }); }
function payloadDigest(repoRoot: string | null, stageFiles: readonly string[], excludeFiles: readonly string[] = []): string { return sha256Json(readPayloadEntries(repoRoot, stageFiles, excludeFiles)); } function evidenceDigest(repoRoot: string | null, stageFiles: readonly string[], excludeFiles: readonly string[] = []): string { return payloadDigest( repoRoot,
stageFiles.filter((file) => file.startsWith('.atm/history/evidence/')), excludeFiles ); } function buildSealAndCommitReceipt(input: { taskId: string; actorId: string | null; targetRepoRoot: string | null; targetStageFiles: readonly string[]; planningRepoRoot: string | null; planningStageFiles: readonly string[]; historicalDeliveryRefs: readonly string[]; historicalBatchRef?: string | null; createdAt?: string;
}): TaskflowSealAndCommitReceipt { const manifestPath = taskflowSealManifestPath(input.taskId); const targetStageFiles = uniqueSorted(input.targetStageFiles); const planningStageFiles = uniqueSorted(input.planningStageFiles); const targetPayload = payloadDigest(input.targetRepoRoot, targetStageFiles, [manifestPath]); const targetEvidence = evidenceDigest(input.targetRepoRoot, targetStageFiles, [manifestPath]);
const planningPayload = payloadDigest(input.planningRepoRoot, planningStageFiles); const planningEvidence = evidenceDigest(input.planningRepoRoot, planningStageFiles); const withoutSeal = { schemaId: 'atm.taskflowSealAndCommitReceipt.v1' as const, taskId: input.taskId, actorId: input.actorId, createdAt: input.createdAt ?? new Date().toISOString(),
targetHeadBeforeCommit: input.targetRepoRoot ? tryGitScalar(input.targetRepoRoot, ['rev-parse', '--verify', 'HEAD']) : null, planningHeadBeforeCommit: input.planningRepoRoot ? tryGitScalar(input.planningRepoRoot, ['rev-parse', '--verify', 'HEAD']) : null, historicalDeliveryRefs: uniqueSorted(input.historicalDeliveryRefs), historicalBatchRef: input.historicalBatchRef ?? null, manifestPath,
targetPayloadDigest: targetPayload, targetEvidenceDigest: targetEvidence, planningPayloadDigest: planningPayload, planningEvidenceDigest: planningEvidence }; return { ...withoutSeal, sealDigest: sha256Json(withoutSeal) }; } function writeSealAndCommitReceipt(repoRoot: string | null, receipt: TaskflowSealAndCommitReceipt): TaskflowSealAndCommitReceipt { if (!repoRoot) return receipt;
const receiptPath = path.resolve(repoRoot, receipt.manifestPath); mkdirSync(path.dirname(receiptPath), { recursive: true }); writeFileSync(receiptPath, `${JSON.stringify(receipt, null, 2)}\n`, 'utf8'); return receipt; } function appendSealTrailers(messageText: string, receipt: TaskflowSealAndCommitReceipt, surface: 'target' | 'planning' | 'shared', laneSessionId: string | null = null): string { return [ messageText, '',
`ATM-Seal-Digest: ${receipt.sealDigest}`, `ATM-Payload-Digest: ${surface === 'planning' ? receipt.planningPayloadDigest : receipt.targetPayloadDigest}`, `ATM-Evidence-Digest: ${surface === 'planning' ? receipt.planningEvidenceDigest : receipt.targetEvidenceDigest}`, `ATM-Seal-Manifest: ${receipt.manifestPath}`, `ATM-Target-Head-Before: ${receipt.targetHeadBeforeCommit ?? '<none>'}`,
`ATM-Planning-Head-Before: ${receipt.planningHeadBeforeCommit ?? '<none>'}`, ...(laneSessionId ? [`ATM-Lane-Session: ${laneSessionId}`] : []) ].join('\n'); } function extractTaskStringList(taskDocument: Record<string, unknown>, key: string): string[] { const value = taskDocument[key]; return Array.isArray(value) ? value.map((entry) => typeof entry === 'string' ? normalizeMarkdownPathDeclaration(entry) : '').filter(Boolean) : []; }
function isCanonicalTaskflowDeliverableCandidate(value: string): boolean { const normalized = normalizeMarkdownPathDeclaration(value); if (!normalized) return false; if (normalized.startsWith('.atm/')) return false; if (/[\\/]$/.test(normalized)) return false; if (validateStrictPathHeuristic(normalized)) return false; return true; }
function extractTaskflowDeliverables(taskDocument: Record<string, unknown>): string[] { const explicit = uniqueSorted(extractTaskStringList(taskDocument, 'deliverables').filter(isCanonicalTaskflowDeliverableCandidate)); if (explicit.length > 0) return explicit; const scopePaths = extractTaskStringList(taskDocument, 'scopePaths'); return uniqueSorted(scopePaths.filter(isCanonicalTaskflowDeliverableCandidate)); }
function sourcePlanPathOf(taskDocument: Record<string, unknown>): string | null { const source = taskDocument.source; if (!source || typeof source !== 'object' || Array.isArray(source)) return null; const planPath = (source as Record<string, unknown>).planPath; return typeof planPath === 'string' && planPath.trim() ? planPath.trim() : null; }
function taskflowPathMatches(filePath: string, declaredPath: string): boolean { return isPathAllowedByScope(filePath, [declaredPath]); } function buildScopeAmendmentProposal(input: { taskId: string; actorId: string | null; taskDocument: Record<string, unknown>; candidateFiles: string[]; reason: string | null; }): TaskflowScopeAmendmentProposal { const candidateFiles = uniqueSorted(input.candidateFiles);
if (candidateFiles.length === 0) { return { required: false, candidateFiles, reason: null, remediationCommand: null, humanReviewRequired: false, notes: [] }; } const planPath = sourcePlanPathOf(input.taskDocument); const remediationCommand = planPath ? `node atm.mjs tasks import --from ${quoteCliValue(planPath)} --write --force --json`
: `node atm.mjs tasks scope add --task ${input.taskId} --actor ${input.actorId ?? '<actor>'} --add ${candidateFiles.join(',')} --json`; return { required: true, candidateFiles, reason: input.reason ?? 'Dirty files overlap the task scope but are not justified by deliverables and targetAllowedFiles.', remediationCommand, humanReviewRequired: true, notes: [
'Do not restore, checkout, clean, or delete another agent active work to satisfy closeout.', 'Repair the governed task metadata or direction lock, rerun taskflow close --dry-run, then close through taskflow close --write.', 'The CLI-computed bundle remains authoritative; LLM review may flag omissions but must not append files ad hoc.' ] }; } function getDirtyFiles(cwd: string): string[] {
const output = tryGitScalar(cwd, ['status', '--porcelain', '-uall']) ?? ''; const files: string[] = []; for (const line of output.split(/\r?\n/)) { if (!line.trim()) continue; let filePart = line.slice(2).trim(); if (filePart.startsWith('"') && filePart.endsWith('"')) { try { filePart = JSON.parse(filePart); } catch { filePart = filePart.slice(1, -1); } } if (line.startsWith('R ')) {
const parts = filePart.split(' -> '); if (parts[1]) filePart = parts[1].trim(); } files.push(filePart.replace(/\\/g, '/')); } return [...new Set(files.filter(Boolean))].sort((a, b) => a.localeCompare(b)); } function getHistoricalCommittedFiles(cwd: string, refs: string[]): string[] { const files: string[] = []; for (const ref of refs) { if (!ref) continue;
const commitSha = tryGitScalar(cwd, ['rev-parse', '--verify', `${ref}^{commit}`]); if (!commitSha) continue; const output = tryGitScalar(cwd, ['show', '--pretty=format:', '--name-only', commitSha, '--']) ?? ''; for (const line of output.split(/\r?\n/)) { const trimmed = line.trim(); if (trimmed) files.push(trimmed.replace(/\\/g, '/')); } } return [...new Set(files)]; }
export function readStagedFiles(repoRoot: string): string[] { const output = tryGitScalar(repoRoot, ['diff', '--cached', '--name-only']) ?? ''; return uniqueSorted(output.split(/\r?\n/).map((line) => line.trim()).filter(Boolean)); } function existingBundleFiles(repo: TaskflowCommitRepoBundle): string[] { if (!repo.repoRoot) return [];
return uniqueSorted(repo.stageFiles.filter((file) => existsSync(path.resolve(repo.repoRoot ?? '', file)))); } function isSameRepoBundle(bundle: TaskflowGovernedCommitBundle): boolean { if (!bundle.targetRepo.repoRoot || !bundle.planningRepo.repoRoot) return false; return path.resolve(bundle.targetRepo.repoRoot) === path.resolve(bundle.planningRepo.repoRoot); }
function buildSharedRepoBundle(repoRoot: string, stageFiles: readonly string[]): TaskflowCommitRepoBundle { return { repoRoot, stageFiles: uniqueSorted(stageFiles), commitMessage: '', commitCommand: '', commitSha: null, status: 'uncomputed' }; } function buildIndexIsolation(repo: TaskflowCommitRepoBundle, stagedFiles: string[], taskId?: string | null): TaskflowIndexIsolation {
const expectedStageFiles = existingBundleFiles(repo); const expected = new Set(expectedStageFiles); const preStagedFiles = uniqueSorted(stagedFiles); const unexpectedStagedFiles = preStagedFiles.filter((file) => !expected.has(file)); const ownership = repo.repoRoot ? inspectGitIndexOwnership({ cwd: repo.repoRoot, taskId: taskId ?? null, stagedFiles: preStagedFiles })
: inspectGitIndexOwnership({ cwd: process.cwd(), taskId: taskId ?? null, stagedFiles: preStagedFiles }); return { verified: unexpectedStagedFiles.length === 0, expectedStageFiles, preStagedFiles, unexpectedStagedFiles, indexLease: buildGitIndexLeaseParkPlan({ report: ownership, expectedStageFiles, leaseId: taskId ? `close-index-${taskId}` : null }) }; } function verifyRepoIndexIsolation(
repo: TaskflowCommitRepoBundle, phase: 'pre-stage' | 'post-stage', strict = true, taskId?: string | null ): TaskflowCommitRepoBundle { if (!repo.repoRoot) return repo; const isolation = buildIndexIsolation(repo, readStagedFiles(repo.repoRoot), taskId); const nextRepo = { ...repo, indexIsolation: isolation }; if (strict && !isolation.verified) { const restoreCommand = isolation.unexpectedStagedFiles.length > 0
? `node atm.mjs git lease stage-override --task <task-id> --actor <actor-id> --paths ${isolation.unexpectedStagedFiles.map((entry) => JSON.stringify(entry)).join(',')} --reason "<human-approved reason>" --json` : null; throw new CliError('ATM_TASKFLOW_CLOSE_INDEX_NOT_ISOLATED', `taskflow close ${phase} index isolation failed; unexpected staged files would be included in the governed commit.`, { exitCode: 1,
details: { repoRoot: repo.repoRoot, phase, indexIsolation: isolation, restoreCommand, remediation: restoreCommand ? `Unstage unrelated files, then rerun taskflow close: ${restoreCommand}` : 'Unstage unrelated files or commit them separately, then rerun taskflow close.' } }); } return nextRepo; } function commitCommandFor(input: { repoRoot: string | null; taskId: string; actorId: string | null; commitMessage: string;
repoKind: 'target' | 'planning'; }): string { if (!input.repoRoot) return ''; if (input.repoKind === 'target') { return `node atm.mjs git commit --cwd ${quoteCliValue(input.repoRoot)} --actor ${quoteCliValue(input.actorId ?? '<actor>')} --task ${input.taskId} --message ${quoteCliValue(input.commitMessage)} --auto-stage --json`; } const messageParts = [ input.commitMessage, '',
`ATM-Actor: ${input.actorId ?? '<actor>'}`, `ATM-Task: ${input.taskId}`, 'ATM-Surface: taskflow-close-planning-bundle' ]; return `git -C ${quoteCliValue(input.repoRoot)} commit -m ${quoteCliValue(messageParts.join('\n'))}`; } function extractBackendStageFiles(backendResult: Record<string, unknown> | null): string[] { const evidence = backendResult?.evidence as Record<string, unknown> | undefined;
if (!evidence) return []; const files: string[] = []; for (const key of ['taskPath', 'closurePacketPath', 'transitionPath']) { const value = evidence[key]; if (typeof value === 'string' && value.trim()) files.push(value); } const allowedFiles = evidence.closeCommitWindowAllowedFiles; if (Array.isArray(allowedFiles)) { files.push(...allowedFiles.filter((value): value is string => typeof value === 'string')); }
return files; } function resolveHistoricalBatchPath(cwd: string, batchRef: string) { const trimmed = batchRef.trim(); if (!trimmed) return null; if (path.isAbsolute(trimmed)) return trimmed; if (trimmed.includes('/') || trimmed.includes('\\')) return path.resolve(cwd, trimmed); return path.join(cwd, '.atm', 'history', 'evidence', 'historical-batches', trimmed.endsWith('.json') ? trimmed : `${trimmed}.json`); }
function resolveExistingHistoricalBatchStageFile(cwd: string, batchRef?: string | null): string | null { if (!batchRef) return null; const batchPath = resolveHistoricalBatchPath(cwd, batchRef); if (!batchPath || !existsSync(batchPath)) return null; return normalizeRepoRelativePath(cwd, batchPath); }
function resolvePlanningPath(cwd: string, planningMirrorPath: string | null): { repoRoot: string | null; relativePath: string | null; reason: string | null } { return resolvePlanningPathFromStored(cwd, planningMirrorPath); } export function isDeferrableGovernanceDirtyFile(filePath: string, taskId?: string | null): boolean { const normalized = filePath.replace(/\\/g, '/').toLowerCase();
if (normalized === '.atm/history/evidence/git-head.jsonl') return true; if (!taskId) return false; const taskLower = taskId.trim().toLowerCase(); if (!taskLower) return false; return normalized === `.atm/history/evidence/${taskLower}.bundle-manifest.json`; } function listUnstagedDirtyFiles(repoRoot: string): string[] { const output = tryGitScalar(repoRoot, ['diff', '--name-only']) ?? '';
return uniqueSorted(output.split(/\r?\n/).map((line) => line.trim()).filter(Boolean)); } export function deferGovernanceDirtyFiles( repoRoot: string, requested: boolean, taskId?: string | null ): DeferredGovernanceDirtyReport { const report: DeferredGovernanceDirtyReport = { schemaId: 'atm.deferredGovernanceDirty.v1', requested, files: [], restored: false, skippedMissingSnapshots: [] }; if (!requested) return report;
const candidates = listUnstagedDirtyFiles(repoRoot).filter((file) => isDeferrableGovernanceDirtyFile(file, taskId)); if (candidates.length === 0) { report.restored = true; return report; } const snapshotRoot = path.join(repoRoot, '.atm', 'runtime', 'snapshots'); mkdirSync(snapshotRoot, { recursive: true }); const timestamp = new Date().toISOString().replace(/[:.]/g, '-'); for (const file of candidates) {
const absolutePath = path.join(repoRoot, file); const content = existsSync(absolutePath) ? readFileSync(absolutePath, 'utf8') : ''; const snapshotPath = path.join(snapshotRoot, `close-window-governance-dirty-${timestamp}-${file.replace(/[\\/]/g, '__')}.json`); writeFileSync(snapshotPath, `${JSON.stringify({ schemaId: 'atm.closeWindowGovernanceDirtySnapshot.v1', file, originalSha256: sha256Text(content), content,
createdAt: new Date().toISOString(), restoredAt: null }, null, 2)}\n`, 'utf8'); runGitOrThrow(repoRoot, ['restore', '--worktree', '--', file]); report.files.push({ file, snapshotPath: normalizeRepoRelativePath(repoRoot, snapshotPath), originalSha256: sha256Text(content), restoredAt: null }); } return report; }
export function restoreDeferredGovernanceDirtyFiles(repoRoot: string, report: DeferredGovernanceDirtyReport): DeferredGovernanceDirtyReport { if (report.restored || report.files.length === 0) { return { ...report, restored: true, skippedMissingSnapshots: report.skippedMissingSnapshots ?? [] }; } const restoredAt = new Date().toISOString(); const skippedMissingSnapshots: string[] = [];
const files = report.files.map((entry) => { const snapshotPath = path.join(repoRoot, entry.snapshotPath); if (!existsSync(snapshotPath)) { skippedMissingSnapshots.push(entry.snapshotPath); return { ...entry, skipReason: 'snapshot-missing' as const }; } const snapshot = JSON.parse(readFileSync(snapshotPath, 'utf8')) as Record<string, unknown>;
const file = typeof snapshot.file === 'string' ? snapshot.file : entry.file; const content = typeof snapshot.content === 'string' ? snapshot.content : ''; const absolutePath = path.join(repoRoot, file); mkdirSync(path.dirname(absolutePath), { recursive: true }); writeFileSync(absolutePath, content, 'utf8'); writeFileSync(snapshotPath, `${JSON.stringify({ ...snapshot, restoredAt }, null, 2)}\n`, 'utf8');
return { ...entry, restoredAt, skipReason: null }; }); return { ...report, files, restored: true, skippedMissingSnapshots }; } export function buildTaskflowCommitBundle(input: { cwd: string; taskId: string; actorId: string | null; commitMode: TaskflowCommitMode; planningMirrorPath: string | null; rosterIndexPath: string | null; extraPlanningStageFiles?: readonly string[];
backendResult?: Record<string, unknown> | null; historicalDeliveryRefs?: string[]; historicalBatchRef?: string | null; planningAuthorityDeliveryOk?: boolean; }): TaskflowGovernedCommitBundle { const targetRepoRoot = path.resolve(input.cwd); let taskDocument: Record<string, unknown> = {}; try { const loaded = loadTaskDocumentOrThrow(targetRepoRoot, input.taskId); taskDocument = loaded.taskDocument; } catch { }
const deliverables = extractTaskflowDeliverables(taskDocument); const scopePaths = extractTaskStringList(taskDocument, 'scopePaths'); const targetAllowedFiles = extractTaskStringList(taskDocument, 'targetAllowedFiles'); const effectiveRuntimeDeliverables = [...resolveTaskflowEffectiveDeliverables(targetRepoRoot, input.taskId, taskDocument)]; const dirtyFiles = getDirtyFiles(targetRepoRoot);
const historicalCommitted = getHistoricalCommittedFiles(targetRepoRoot, input.historicalDeliveryRefs ?? []); const historicalCloseback = historicalCommitted.length > 0; let allowed = uniqueSorted([ ...targetAllowedFiles, ...resolveTaskflowDeclaredFiles(targetRepoRoot, input.taskId, taskDocument) .filter((entry) => !entry.startsWith('.atm/')) ]); if (allowed.length === 0) { allowed = scopePaths; }
const targetDeliveryFiles: string[] = []; const historicalBatchStageFile = resolveExistingHistoricalBatchStageFile(targetRepoRoot, input.historicalBatchRef); const backendGovernanceFiles = [ ...listCurrentTaskGovernanceFiles(targetRepoRoot, input.taskId), ...listOptionalEvidenceBundleGovernanceArtifacts(targetRepoRoot, input.taskId), ...(input.backendResult ? extractBackendStageFiles(input.backendResult) : []),
...listTaskOwnedProtectedOverrideAuditFiles(targetRepoRoot, input.taskId) ]; const targetGovernanceFiles = uniqueSorted([ ...(historicalBatchStageFile ? [historicalBatchStageFile] : []), ...backendGovernanceFiles, taskflowSealManifestPath(input.taskId) ]); const excludedDirtyFiles: string[] = []; const excludedReasons: Record<string, string> = {}; const scopeAmendmentCandidateFiles: string[] = [];
let metadataFailClosed = false; let failClosedReason: string | null = null; if (deliverables.length === 0) { metadataFailClosed = true; failClosedReason = 'Task metadata error: "deliverables" list is empty or missing.'; } const directoryExpansion = expandDirectoryDeliverableDeclarations(targetRepoRoot, deliverables); if (!directoryExpansion.ok) { metadataFailClosed = true;
failClosedReason = directoryExpansion.failClosedReason; } const effectiveDeliverables = uniqueSorted([ ...(directoryExpansion.ok ? directoryExpansion.effectiveDeliverables : deliverables), ...effectiveRuntimeDeliverables ]); for (const del of effectiveDeliverables) { const isAllowed = allowed.some((all) => taskflowPathMatches(del, all)); if (!isAllowed) { metadataFailClosed = true;
failClosedReason = `Task metadata error: declared deliverable "${del}" falls outside active direction lock / targetAllowedFiles.`; } } const hasPlanningFile = effectiveDeliverables.some((del) => del.startsWith('docs/tasks/') || del.endsWith('.task.md')); const hasTargetFile = effectiveDeliverables.some((del) => !del.startsWith('docs/tasks/') && !del.endsWith('.task.md'));
if (!input.planningAuthorityDeliveryOk && hasPlanningFile && hasTargetFile) { metadataFailClosed = true; failClosedReason = 'Task metadata error: deliverables contain mixed planning-path and target-path declarations.'; } for (const file of dirtyFiles) { if (file.startsWith('.atm/')) continue; const inScope = scopePaths.some((sp) => taskflowPathMatches(file, sp));
const isDeclared = effectiveDeliverables.some((del) => taskflowPathMatches(file, del)); const isExplicitlyDeclaredFile = effectiveDeliverables.some((del) => normalizeTaskflowRelativePath(del) === file); const isAllowed = allowed.some((all) => taskflowPathMatches(file, all)); if (historicalCloseback && isTaskflowScratchBackupFile(file) && !isExplicitlyDeclaredFile) { excludedDirtyFiles.push(file);
excludedReasons[file] = inScope ? 'scratch/backup file inside broad scope; excluded as advisory residue during historical closeback' : 'scratch/backup file outside task scope; excluded from governed bundle and must be left untouched'; } else if (isDeclared && isAllowed) { targetDeliveryFiles.push(file); } else { excludedDirtyFiles.push(file); if (inScope) { if (historicalCloseback) {
excludedReasons[file] = 'inside scope but outside declared deliverables; excluded as advisory residue during historical closeback'; } else { scopeAmendmentCandidateFiles.push(file); metadataFailClosed = true; failClosedReason = `Scope amendment required: dirty file "${file}" is inside task scope but is not declared in deliverables and targetAllowedFiles.`;
excludedReasons[file] = 'inside scope but not declared/allowed (fail-closed trigger)'; } } else { excludedReasons[file] = 'outside task scope; excluded from governed bundle and must be left untouched'; } } } const scopeAmendment = buildScopeAmendmentProposal({ taskId: input.taskId, actorId: input.actorId, taskDocument, candidateFiles: scopeAmendmentCandidateFiles, reason: failClosedReason });
const finalDeliveryFiles = targetDeliveryFiles.filter( (file) => !historicalCommitted.some((h) => taskflowPathMatches(file, h)) ); const targetStageFiles = uniqueSorted([ ...finalDeliveryFiles, ...targetGovernanceFiles ]); const planning = resolvePlanningPath(targetRepoRoot, input.planningMirrorPath); const planningStageFiles = planning.repoRoot && planning.relativePath ? uniqueSorted([ planning.relativePath,
...(input.extraPlanningStageFiles ?? []), ...(input.rosterIndexPath ? [normalizeRepoRelativePath(planning.repoRoot, path.isAbsolute(input.rosterIndexPath) ? input.rosterIndexPath : path.resolve(planning.repoRoot, input.rosterIndexPath))] : []) ]) : []; const targetMessage = buildTaskflowCommitMessage('target', { taskId: input.taskId });
const planningMessage = buildTaskflowCommitMessage('planning', { taskId: input.taskId }); const failClosed = metadataFailClosed || targetStageFiles.length === 0 || !planning.repoRoot || planningStageFiles.length === 0; const sealAndCommitReceipt = buildSealAndCommitReceipt({ taskId: input.taskId, actorId: input.actorId, targetRepoRoot, targetStageFiles, planningRepoRoot: planning.repoRoot, planningStageFiles,
historicalDeliveryRefs: input.historicalDeliveryRefs ?? [], historicalBatchRef: input.historicalBatchRef ?? null }); return { schemaId: 'atm.taskflowGovernedCommitBundle.v1', taskId: input.taskId, actorId: input.actorId, targetRepo: { repoRoot: targetRepoRoot, stageFiles: targetStageFiles, commitMessage: targetMessage, commitCommand: commitCommandFor({ repoRoot: targetRepoRoot, taskId: input.taskId,
actorId: input.actorId, commitMessage: targetMessage, repoKind: 'target' }), commitSha: null, status: input.commitMode === 'dry-run' ? 'preview' : 'uncomputed', reason: failClosedReason || (targetStageFiles.length > 0 ? null : 'target close artifact paths could not be computed') }, planningRepo: { repoRoot: planning.repoRoot, stageFiles: planningStageFiles, commitMessage: planningMessage,
commitCommand: commitCommandFor({ repoRoot: planning.repoRoot, taskId: input.taskId, actorId: input.actorId, commitMessage: planningMessage, repoKind: 'planning' }), commitSha: null, status: input.commitMode === 'dry-run' ? 'preview' : 'uncomputed', reason: planning.reason }, commitMode: input.commitMode, failClosed, recoveryCommand: null, targetDeliveryFiles: finalDeliveryFiles, targetGovernanceFiles,
planningFiles: planningStageFiles, excludedDirtyFiles, excludedReasons, scopeAmendment, sealAndCommitReceipt }; } function isTaskflowScratchBackupFile(file: string): boolean { const normalized = normalizeTaskflowRelativePath(file).toLowerCase(); return normalized.endsWith('.bak') || normalized.endsWith('.backup') || normalized.endsWith('.orig') || normalized.endsWith('.tmp') || normalized.includes('/.tmp/')
|| normalized.includes('/tmp/'); } export function assertCommitBundleReady(bundle: TaskflowGovernedCommitBundle) { if (bundle.failClosed || !bundle.targetRepo.repoRoot || !bundle.planningRepo.repoRoot) { throw new CliError('ATM_TASKFLOW_CLOSE_COMMIT_BUNDLE_INCOMPLETE', 'taskflow close cannot compute the dual-repo governed commit bundle.', { exitCode: 1, details: { governedCommitBundle: bundle } }); } }
export function reconcileTeamContributionCompositionWithCommitBundle( bundle: TaskflowGovernedCommitBundle, composition: TeamContributionCompositionResult ): TaskflowGovernedCommitBundle { const finalTreeFiles = composition.finalTree.files.map((file) => file.path); const targetDeliveryFiles = uniqueSorted([...bundle.targetDeliveryFiles, ...finalTreeFiles]); const targetStageFiles = uniqueSorted([
...bundle.targetRepo.stageFiles, ...targetDeliveryFiles, ...bundle.targetGovernanceFiles ]); const scopeAmendment = composition.scopeExpansion.required ? { ...bundle.scopeAmendment, required: true, candidateFiles: uniqueSorted([ ...bundle.scopeAmendment.candidateFiles, ...composition.scopeExpansion.candidateFiles ]), reason: composition.scopeExpansion.reason, humanReviewRequired: true, notes: uniqueSorted([
...bundle.scopeAmendment.notes, 'Team contribution composer owns scope expansion reconciliation; worker manifests do not transfer file ownership in flight.' ]) } : bundle.scopeAmendment; const reason = composition.conflicts.length > 0 ? `Team contribution conflict: ${composition.conflicts.map((conflict) => conflict.path).join(', ')}` : composition.scopeExpansion.reason ?? bundle.targetRepo.reason ?? null; return {
...bundle, failClosed: bundle.failClosed || composition.failClosed, targetDeliveryFiles, targetRepo: { ...bundle.targetRepo, stageFiles: targetStageFiles, reason }, scopeAmendment }; } function refreshSealAndCommitReceipt(bundle: TaskflowGovernedCommitBundle): TaskflowGovernedCommitBundle { const receipt = buildSealAndCommitReceipt({ taskId: bundle.taskId, actorId: bundle.actorId,
targetRepoRoot: bundle.targetRepo.repoRoot, targetStageFiles: bundle.targetRepo.stageFiles, planningRepoRoot: bundle.planningRepo.repoRoot, planningStageFiles: bundle.planningRepo.stageFiles, historicalDeliveryRefs: bundle.sealAndCommitReceipt.historicalDeliveryRefs, historicalBatchRef: bundle.sealAndCommitReceipt.historicalBatchRef }); return { ...bundle,
sealAndCommitReceipt: writeSealAndCommitReceipt(bundle.targetRepo.repoRoot, receipt) }; } function stageRepoBundle(repo: TaskflowCommitRepoBundle, taskId?: string): TaskflowCommitRepoBundle { if (repo.repoRoot && taskId) { assertCloseWindowStagingAllowed({ cwd: repo.repoRoot, taskId, operation: 'taskflow close bundle staging' }); } if (!repo.repoRoot || repo.stageFiles.length === 0) {
return { ...repo, status: 'uncomputed' }; } const existingFiles = existingBundleFiles(repo); if (existingFiles.length === 0) { return { ...repo, stageFiles: existingFiles, status: 'skipped', reason: 'no existing bundle files to stage', indexIsolation: buildIndexIsolation(repo, readStagedFiles(repo.repoRoot), taskId) }; } runGitOrThrow(repo.repoRoot, ['add', '-A', '-f', '--', ...existingFiles]);
return { ...repo, stageFiles: existingFiles, status: 'staged' }; } async function commitTaskflowBundle(input: { bundle: TaskflowGovernedCommitBundle; actorId: string; taskId: string; }): Promise<TaskflowGovernedCommitBundle> { const targetStageFiles = existingBundleFiles(input.bundle.targetRepo); const targetPreStagedFiles = input.bundle.targetRepo.repoRoot ? readStagedFiles(input.bundle.targetRepo.repoRoot) : [];
const targetPreflight = input.bundle.targetRepo.repoRoot ? buildIndexIsolation(input.bundle.targetRepo, targetPreStagedFiles, input.taskId) : null; const laneSessionId = input.bundle.targetRepo.repoRoot ? resolveTaskflowCommitLaneSessionId({ repoRoot: input.bundle.targetRepo.repoRoot, actorId: input.actorId, taskId: input.taskId }) : null; if (input.bundle.targetRepo.repoRoot && targetPreflight) { parkGitIndexLease(input.bundle.targetRepo.repoRoot, targetPreflight.indexLease); } try { commitRepoWithTemporaryIndex({ repoRoot: input.bundle.targetRepo.repoRoot ?? '', stageFiles: targetStageFiles,
args: ['commit', '-m', appendSealTrailers(input.bundle.targetRepo.commitMessage, input.bundle.sealAndCommitReceipt, 'target', laneSessionId)], actorId: input.actorId, taskId: input.taskId, laneSessionId }); } finally { if (input.bundle.targetRepo.repoRoot && targetPreflight) { restoreGitIndexLease(input.bundle.targetRepo.repoRoot, targetPreflight.indexLease); } } const targetCommitSha = input.bundle.targetRepo.repoRoot
? tryGitScalar(input.bundle.targetRepo.repoRoot, ['rev-parse', '--verify', 'HEAD']) : null; let targetRepo: TaskflowCommitRepoBundle = { ...input.bundle.targetRepo, commitSha: targetCommitSha, status: 'committed', indexIsolation: targetPreflight ?? input.bundle.targetRepo.indexIsolation }; let planningRepo: TaskflowCommitRepoBundle = input.bundle.planningRepo; try { if (!planningRepo.repoRoot) {
throw new Error('planning repo root missing'); } const planningStageFiles = existingBundleFiles(planningRepo); const planningPreStagedFiles = readStagedFiles(planningRepo.repoRoot); const planningPreflight = buildIndexIsolation(planningRepo, planningPreStagedFiles, input.taskId); parkGitIndexLease(planningRepo.repoRoot, planningPreflight.indexLease); const planningMessage = [
appendSealTrailers(planningRepo.commitMessage, input.bundle.sealAndCommitReceipt, 'planning', laneSessionId), '', `ATM-Actor: ${input.actorId}`, `ATM-Task: ${input.taskId}`, 'ATM-Surface: taskflow-close-planning-bundle' ].join('\n'); try { commitRepoWithTemporaryIndex({ repoRoot: planningRepo.repoRoot, stageFiles: planningStageFiles, args: ['commit', '-m', planningMessage], actorId: input.actorId, taskId: input.taskId, laneSessionId });
} finally { restoreGitIndexLease(planningRepo.repoRoot, planningPreflight.indexLease); } planningRepo = { ...planningRepo, commitSha: tryGitScalar(planningRepo.repoRoot, ['rev-parse', '--verify', 'HEAD']), status: 'committed', indexIsolation: planningPreflight }; } catch (error) { planningRepo = { ...planningRepo, status: 'failed', reason: error instanceof Error ? error.message : String(error) };
targetRepo = { ...targetRepo, status: 'committed' }; return { ...input.bundle, targetRepo, planningRepo, failClosed: true, recoveryCommand: 'Planning repo commit failed after target repo governance commit succeeded. Inspect planning repo status and reconcile manually.' }; } return { ...input.bundle, targetRepo, planningRepo, failClosed: false, recoveryCommand: null }; } function commitRepoWithTemporaryIndex(input: {
repoRoot: string; stageFiles: readonly string[]; args: readonly string[]; actorId?: string | null; taskId?: string | null; laneSessionId?: string | null; }) { const tempDir = mkdtempSync(path.join(os.tmpdir(), 'atm-taskflow-commit-index-')); const tempIndexFile = path.join(tempDir, 'index'); const identity = input.actorId ? resolveActorGitIdentityForCommit(input.repoRoot, input.actorId) : null; const laneSessionId = input.laneSessionId ?? resolveTaskflowCommitLaneSessionId({ repoRoot: input.repoRoot, actorId: input.actorId, taskId: input.taskId }); const env = { ...process.env,
GIT_INDEX_FILE: tempIndexFile, ...(input.actorId ? { ATM_COMMIT_ACTOR_ID: input.actorId } : {}), ...(input.taskId ? { ATM_COMMIT_TASK_ID: input.taskId } : {}), ...(laneSessionId ? { ATM_COMMIT_LANE_SESSION_ID: laneSessionId } : {}), ...(identity?.gitName ? { GIT_AUTHOR_NAME: identity.gitName, GIT_COMMITTER_NAME: identity.gitName } : {}), ...(identity?.gitEmail ? { GIT_AUTHOR_EMAIL: identity.gitEmail, GIT_COMMITTER_EMAIL: identity.gitEmail } : {}) }; try {
runGitWithEnv(input.repoRoot, ['read-tree', 'HEAD'], env); if (input.stageFiles.length > 0) { runGitWithEnv(input.repoRoot, ['add', '-A', '-f', '--', ...input.stageFiles], env); } runGitWithEnv(input.repoRoot, input.args, env); if (input.stageFiles.length > 0) { runGitOrThrow(input.repoRoot, ['reset', '--quiet', '--', ...input.stageFiles]); } } finally { rmSync(tempDir, { recursive: true, force: true }); } }
export async function commitTaskflowDeliveryFiles(input: { bundle: TaskflowGovernedCommitBundle; actorId: string; taskId: string; deferForeignStaged?: boolean; }): Promise<TaskflowDeliveryCommit | null> { const repoRoot = input.bundle.targetRepo.repoRoot; const stageFiles = uniqueSorted(input.bundle.targetDeliveryFiles); if (!repoRoot || stageFiles.length === 0) { return null; }
const deliveryBundle: TaskflowCommitRepoBundle = { repoRoot, stageFiles, commitMessage: `chore(taskflow): deliver ${input.taskId} source bundle`, commitCommand: commitCommandFor({ repoRoot, actorId: input.actorId, taskId: input.taskId, commitMessage: `chore(taskflow): deliver ${input.taskId} source bundle`, repoKind: 'target' }), commitSha: null, status: 'uncomputed' };
const preflight = verifyRepoIndexIsolation(deliveryBundle, 'pre-stage', true, input.taskId); const staged = verifyRepoIndexIsolation(stageRepoBundle(preflight, input.taskId), 'post-stage', true, input.taskId); if (staged.status !== 'staged') { return null; } const targetResult = await runAtmGit([ 'commit', '--cwd', repoRoot, '--actor', input.actorId, '--task', input.taskId, '--message', deliveryBundle.commitMessage,
...(input.deferForeignStaged ? ['--defer-foreign-staged'] : []), '--json' ]); const commitSha = String((targetResult.evidence as Record<string, unknown>)?.commitSha ?? '') || null; return { repoRoot, stageFiles: staged.stageFiles, commitMessage: deliveryBundle.commitMessage, commitSha, status: 'committed' }; } export async function finalizeTaskflowCommitBundle(input: { bundle: TaskflowGovernedCommitBundle;
actorId: string; taskId: string; }): Promise<TaskflowGovernedCommitBundle> { assertCommitBundleReady(input.bundle); const sealedInputBundle = input.bundle.commitMode === 'dry-run' ? input.bundle : refreshSealAndCommitReceipt(input.bundle); const mutexRepoRoot = sealedInputBundle.targetRepo.repoRoot ?? sealedInputBundle.planningRepo.repoRoot; const strictIsolation = sealedInputBundle.commitMode === 'stage-only';
const sharedRepoMode = isSameRepoBundle(sealedInputBundle); if (sealedInputBundle.commitMode === 'auto-commit' && mutexRepoRoot) { return withCloseTransactionMutex({ repoRoot: mutexRepoRoot, taskId: input.taskId, actorId: input.actorId }, () => finalizeTaskflowCommitBundleWithSeal({ bundle: sealedInputBundle, actorId: input.actorId, taskId: input.taskId, strictIsolation, sharedRepoMode })); }
return finalizeTaskflowCommitBundleWithSeal({ bundle: sealedInputBundle, actorId: input.actorId, taskId: input.taskId, strictIsolation, sharedRepoMode }); } async function finalizeTaskflowCommitBundleWithSeal(input: { bundle: TaskflowGovernedCommitBundle; actorId: string; taskId: string; strictIsolation: boolean; sharedRepoMode: boolean; }): Promise<TaskflowGovernedCommitBundle> {
const sealedInputBundle = input.bundle; const strictIsolation = input.strictIsolation; const sharedRepoMode = input.sharedRepoMode; if (sharedRepoMode) { const repoRoot = sealedInputBundle.targetRepo.repoRoot!; const sharedRepo = buildSharedRepoBundle(repoRoot, [ ...sealedInputBundle.targetRepo.stageFiles, ...sealedInputBundle.planningRepo.stageFiles ]);
const preflightShared = verifyRepoIndexIsolation(sharedRepo, 'pre-stage', strictIsolation, input.taskId); if (sealedInputBundle.commitMode === 'stage-only') { const stagedShared = verifyRepoIndexIsolation(stageRepoBundle(preflightShared, input.taskId), 'post-stage', true, input.taskId); return { ...sealedInputBundle, targetRepo: { ...sealedInputBundle.targetRepo, status: stagedShared.status,
indexIsolation: stagedShared.indexIsolation }, planningRepo: { ...sealedInputBundle.planningRepo, status: stagedShared.status, indexIsolation: stagedShared.indexIsolation } }; } const sharedStageFiles = existingBundleFiles(preflightShared); const laneSessionId = resolveTaskflowCommitLaneSessionId({ repoRoot, actorId: input.actorId, taskId: input.taskId }); const preStagedFiles = readStagedFiles(repoRoot); const sharedIndexIsolation = buildIndexIsolation(preflightShared, preStagedFiles, input.taskId);
parkGitIndexLease(repoRoot, sharedIndexIsolation.indexLease); const sharedMessage = [ appendSealTrailers(sealedInputBundle.targetRepo.commitMessage, sealedInputBundle.sealAndCommitReceipt, 'shared', laneSessionId), '', `ATM-Actor: ${input.actorId}`, `ATM-Task: ${input.taskId}`, 'ATM-Surface: taskflow-close-shared-repo-bundle', `ATM-Planning-Commit-Message: ${sealedInputBundle.planningRepo.commitMessage}` ].join('\n'); try {
commitRepoWithTemporaryIndex({ repoRoot, stageFiles: sharedStageFiles, args: ['commit', '-m', sharedMessage], actorId: input.actorId, taskId: input.taskId, laneSessionId }); } finally { restoreGitIndexLease(repoRoot, sharedIndexIsolation.indexLease); } const commitSha = tryGitScalar(repoRoot, ['rev-parse', '--verify', 'HEAD']); return { ...sealedInputBundle, targetRepo: { ...sealedInputBundle.targetRepo, commitSha,
status: 'committed', indexIsolation: sharedIndexIsolation }, planningRepo: { ...sealedInputBundle.planningRepo, commitSha, status: 'committed', indexIsolation: sharedIndexIsolation }, failClosed: false, recoveryCommand: null }; } const preflightTarget = verifyRepoIndexIsolation(sealedInputBundle.targetRepo, 'pre-stage', strictIsolation, input.taskId);
const preflightPlanning = verifyRepoIndexIsolation(sealedInputBundle.planningRepo, 'pre-stage', strictIsolation, input.taskId); if (sealedInputBundle.commitMode === 'stage-only') { const stagedTarget = verifyRepoIndexIsolation(stageRepoBundle(preflightTarget, input.taskId), 'post-stage', true, input.taskId);
const stagedPlanning = verifyRepoIndexIsolation(stageRepoBundle(preflightPlanning, input.taskId), 'post-stage', true, input.taskId); return { ...sealedInputBundle, targetRepo: stagedTarget, planningRepo: stagedPlanning }; } const bundle: TaskflowGovernedCommitBundle = { ...sealedInputBundle, targetRepo: preflightTarget, planningRepo: preflightPlanning }; return commitTaskflowBundle({ bundle, actorId: input.actorId,
taskId: input.taskId }); }
