import type { AtomCatalogEntry } from './types.ts';
import { atmReadableRefContractVersion } from '../atom-runtime.ts';

export function renderFrameworkGeneratedRefs(catalog: readonly AtomCatalogEntry[]): string {
  const sourceExtension = 't' + 's';
  return [
    `import { defineAtmAtomRef, defineAtmMapRef } from './atom-runtime.${sourceExtension}';`,
    '',
    '// Generated by `atm atom-ref sweep`; edit registry/workbench metadata, then regenerate.',
    ...catalog.map(renderFrameworkRef),
    ''
  ].join('\n');
}

export function renderAdopterAtomRefs(atoms: readonly AtomCatalogEntry[]): string {
  return [
    `export const atmReadableRefContractVersion = '${atmReadableRefContractVersion}';`,
    '',
    'export function defineAtmAtomRef(ref) {',
    "  return Object.freeze({ ...ref, kind: 'atom', readabilityContractVersion: atmReadableRefContractVersion, sourcePaths: [...(ref.sourcePaths ?? [])] });",
    '}',
    '',
    '// Generated by `atm atom-ref sweep`; edit registry/workbench metadata, then regenerate.',
    ...atoms.map(renderAdopterAtomRef),
    ''
  ].join('\n');
}

export function renderAdopterMapRefs(maps: readonly AtomCatalogEntry[]): string {
  return [
    `export const atmReadableRefContractVersion = '${atmReadableRefContractVersion}';`,
    '',
    'export function defineAtmMapRef(ref) {',
    "  return Object.freeze({ ...ref, kind: 'map', readabilityContractVersion: atmReadableRefContractVersion, sourcePaths: [...(ref.sourcePaths ?? [])], members: [...(ref.members ?? [])], entrypoints: [...(ref.entrypoints ?? [])] });",
    '}',
    '',
    '// Generated by `atm atom-ref sweep`; edit registry/workbench metadata, then regenerate.',
    ...maps.map(renderAdopterMapRef),
    ''
  ].join('\n');
}

function renderFrameworkRef(entry: AtomCatalogEntry): string {
  const defineName = entry.kind === 'atom' ? 'defineAtmAtomRef' : 'defineAtmMapRef';
  const idField = entry.kind === 'atom' ? 'atomId' : 'mapId';
  return [
    '',
    `export const ${entry.refName} = ${defineName}({`,
    `  ${idField}: '${entry.id}',`,
    `  logicalName: '${escapeSingle(entry.logicalName)}',`,
    `  purpose: '${escapeSingle(entry.purpose)}',`,
    `  sourcePaths: ${renderStringArray(entry.sourcePaths)},`,
    ...(entry.kind === 'map' ? [
      `  members: ${renderStringArray(entry.members)},`,
      `  entrypoints: ${renderStringArray(entry.entrypoints)}`
    ] : []),
    '});'
  ].join('\n');
}

function renderAdopterAtomRef(entry: AtomCatalogEntry): string {
  return [
    '',
    `export const ${entry.refName} = defineAtmAtomRef({`,
    `  atomId: '${entry.id}',`,
    `  logicalName: '${escapeSingle(entry.logicalName)}',`,
    `  purpose: '${escapeSingle(entry.purpose)}',`,
    `  sourcePaths: ${renderStringArray(entry.sourcePaths)}`,
    '});'
  ].join('\n');
}

function renderAdopterMapRef(entry: AtomCatalogEntry): string {
  return [
    '',
    `export const ${entry.refName} = defineAtmMapRef({`,
    `  mapId: '${entry.id}',`,
    `  logicalName: '${escapeSingle(entry.logicalName)}',`,
    `  purpose: '${escapeSingle(entry.purpose)}',`,
    `  sourcePaths: ${renderStringArray(entry.sourcePaths)},`,
    `  members: ${renderStringArray(entry.members)},`,
    `  entrypoints: ${renderStringArray(entry.entrypoints)}`,
    '});'
  ].join('\n');
}

function renderStringArray(values: readonly string[]): string {
  return `[${values.map((value) => `'${escapeSingle(value)}'`).join(', ')}]`;
}

function escapeSingle(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
