import crypto from 'node:crypto'; import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'; import path from 'node:path'; import { spawn, spawnSync } from 'node:child_process'; import { fileURLToPath } from 'node:url'; import { applyBaselineFailureSnapshot, collectBaselineFindingFingerprints, createValidatorFailureEnvelope, firstRequiredCommand, summarizeBlockingFindings
} from '../lib/validator-envelope.ts'; import { findDuplicateDedupeKeys, normalizeTier, readTestCatalog, selectTestEntries, type TestCatalogEntry, type TestTier } from '../lib/test-catalog.ts'; import { buildValidationReceiptInput, readReusableValidationReceipt, writeValidationReceipt, type ValidationReceiptStatus } from '../../packages/core/src/evidence/validation-receipt.ts'; import { buildValidatorLifecycleSummary } from '../../packages/core/src/evidence/validator-lifecycle.ts'; import { createSealedCommitCanaryPlan,
resolveValidationObligations } from '../../packages/cli/src/commands/validation-obligations.ts'; const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..'); const configPath = path.join(root, 'scripts', 'validators.config.json'); if (!existsSync(configPath)) { throw new Error(`validators config missing: ${path.relative(root, configPath)}`); }
const config: any = JSON.parse(readFileSync(configPath, 'utf8')); const validatorMap = new Map(config.validators.map((entry: any) => [entry.name, entry])); const selectionFamilies = Array.isArray(config.selectionFamilies) ? config.selectionFamilies : []; const DEFAULT_FAST_VALIDATOR_BUDGET_MS = 10_000; const DEFAULT_SLOW_VALIDATOR_BUDGET_MS = 90_000;
const VALIDATOR_RUNS_ROOT = path.join(root, '.atm', 'runtime', 'validator-runs'); const runningValidatorChildren = new Set<ReturnType<typeof spawn>>(); function killChild(child: ReturnType<typeof spawn>, signal: NodeJS.Signals | number | string = 'SIGTERM'): void { if (process.platform === 'win32') { if (child.pid) { const result = spawnSync('taskkill', ['/F', '/T', '/PID', String(child.pid)], { stdio: 'ignore' });
if (result.status === 0) { return; } } } try { child.kill(signal as NodeJS.Signals); } catch {} } function killAllRunningValidatorChildren(signal: NodeJS.Signals): void { for (const runningChild of runningValidatorChildren) { killChild(runningChild, signal); } } process.on('SIGINT', () => { killAllRunningValidatorChildren('SIGTERM'); process.exit(130); }); process.on('SIGTERM', () => {
killAllRunningValidatorChildren('SIGTERM'); process.exit(143); }); process.on('exit', () => { for (const runningChild of runningValidatorChildren) { killChild(runningChild, 'SIGTERM'); } }); export async function runValidatorsCli(argv: string[] = process.argv.slice(2)): Promise<number> { const parsedCli = parseCliArgs(argv); if (parsedCli.status) { runStatusQueryAndExit(parsedCli); }
const profileConfig = resolveProfileConfig(parsedCli.profile); const parallel = resolveParallelSetting(parsedCli, profileConfig); const resolvedFocusPaths = resolveFocusPaths(parsedCli.focusPaths, parsedCli.focusChanged); const testCatalog = readTestCatalog(root, { validatorsConfig: config }); const baseCatalogSelection = resolveCatalogValidatorSelection(parsedCli.profile, []);
const focusedCatalogSelection = resolveCatalogValidatorSelection(parsedCli.profile, resolvedFocusPaths); const focusedValidationObligations = resolveValidationObligations(resolvedFocusPaths); const baseProfileValidatorNames = baseCatalogSelection.names; const focusedProfileValidatorNames = focusedCatalogSelection.names; const selectedNames = applyFilters(focusedProfileValidatorNames, parsedCli.filters);
const selectedCatalogEntryByValidatorName = new Map( [...baseCatalogSelection.entries, ...focusedCatalogSelection.entries] .filter((entry) => entry.validatorName) .map((entry) => [String(entry.validatorName), entry]) ); const selectedCatalogEntries = selectedNames .map((name: string) => selectedCatalogEntryByValidatorName.get(name)) .filter(Boolean) as TestCatalogEntry[];
const duplicateDedupeKeys = findDuplicateDedupeKeys(selectedCatalogEntries); const baselineSummary = parsedCli.baselinePath ? readBaselineSummary(parsedCli.baselinePath) : null; const performanceBaselineSummary = parsedCli.performanceBaselinePath ? readBaselineSummary(parsedCli.performanceBaselinePath) : null; const baselineFingerprints = collectBaselineFindingFingerprints(baselineSummary);
const selectedValidators = selectedNames.map((name: any) => { const validator = validatorMap.get(name); if (!validator) { throw new Error(`Unknown validator in profile "${parsedCli.profile}": ${name}`); } const catalogEntry = selectedCatalogEntryByValidatorName.get(String(name)); return catalogEntry ? { ...validator, catalogKey: catalogEntry.key, capability: catalogEntry.capability, family: catalogEntry.family,
scope: catalogEntry.scope, dedupeKeys: catalogEntry.dedupeKeys ?? [], catalogCostBudgetMs: catalogEntry.costBudgetMs } : validator; }).filter((validator: any) => parsedCli.skipSlow ? validator.slow !== true : true); const runContext = initializeRunContext({ parsedCli, profileConfig, selectedValidators, focusPaths: resolvedFocusPaths, baseValidatorCount: baseProfileValidatorNames.length,
focusReducedValidatorCount: focusedProfileValidatorNames.length }); if (selectedValidators.length === 0) { const summary = createSummary({ profile: parsedCli.profile, mode: profileConfig.mode, filters: parsedCli.filters, focusPaths: resolvedFocusPaths, focusMode: parsedCli.focusChanged ? 'changed' : (resolvedFocusPaths.length > 0 ? 'paths' : 'none'), baseValidatorCount: baseProfileValidatorNames.length,
focusReducedValidatorCount: focusedProfileValidatorNames.length, parallel, legacy: parsedCli.legacy, cache: parsedCli.cache, skipSlow: parsedCli.skipSlow, baselinePath: parsedCli.baselinePath, performanceBaselinePath: parsedCli.performanceBaselinePath, performanceBaselineSummary, performanceBudgetOverrides: { fastValidatorBudgetMs: parsedCli.fastValidatorBudgetMs,
slowValidatorBudgetMs: parsedCli.slowValidatorBudgetMs }, catalog: { schemaId: testCatalog.schemaId, sourcePath: testCatalog.sourcePath, capability: 'validator', duplicateDedupeKeys }, baselineFingerprintCount: baselineFingerprints.size, startedAt: Date.now(), results: [], runContext, dag: createValidatorDagReport([]) }); persistRunSummary(runContext, summary, 'completed'); writePerformanceOutputIfRequested(summary, parsedCli.performanceOutputPath);
emitSummary(summary, parsedCli.json); process.exitCode = 0; process.exit(); } const scheduledValidators = orderValidatorsByDependencies(selectedValidators); const dag = createValidatorDagReport(scheduledValidators); const startedAt = Date.now(); const results = parallel && dag.hasDependencies !== true ? await Promise.all(scheduledValidators.map((validator: any) => runValidator(validator, profileConfig.mode, { json: parsedCli.json, cache: parsedCli.cache, runContext, validatorTimeoutMs: parsedCli.validatorTimeoutMs })))
.then((items) => items.map((item) => markResultAgainstBaseline(item, baselineFingerprints))) : await runValidatorsSequential(scheduledValidators, profileConfig.mode, { json: parsedCli.json, cache: parsedCli.cache, stopOnFailure: parsedCli.legacy, baselineFingerprints, runContext, validatorTimeoutMs: parsedCli.validatorTimeoutMs, summaryInput: { profile: parsedCli.profile, mode: profileConfig.mode,
filters: parsedCli.filters, focusPaths: resolvedFocusPaths, focusMode: parsedCli.focusChanged ? 'changed' : (resolvedFocusPaths.length > 0 ? 'paths' : 'none'), baseValidatorCount: baseProfileValidatorNames.length, focusReducedValidatorCount: focusedProfileValidatorNames.length, parallel, legacy: parsedCli.legacy, cache: parsedCli.cache, skipSlow: parsedCli.skipSlow, baselinePath: parsedCli.baselinePath,
performanceBaselinePath: parsedCli.performanceBaselinePath, performanceBaselineSummary, performanceBudgetOverrides: { fastValidatorBudgetMs: parsedCli.fastValidatorBudgetMs, slowValidatorBudgetMs: parsedCli.slowValidatorBudgetMs }, catalog: { schemaId: testCatalog.schemaId, sourcePath: testCatalog.sourcePath, capability: 'validator', duplicateDedupeKeys, obligationMap: focusedValidationObligations },
baselineFingerprintCount: baselineFingerprints.size, startedAt, dag } }); const summary = createSummary({ profile: parsedCli.profile, mode: profileConfig.mode, filters: parsedCli.filters, focusPaths: resolvedFocusPaths, focusMode: parsedCli.focusChanged ? 'changed' : (resolvedFocusPaths.length > 0 ? 'paths' : 'none'), baseValidatorCount: baseProfileValidatorNames.length,
focusReducedValidatorCount: focusedProfileValidatorNames.length, parallel, legacy: parsedCli.legacy, cache: parsedCli.cache, skipSlow: parsedCli.skipSlow, baselinePath: parsedCli.baselinePath, performanceBaselinePath: parsedCli.performanceBaselinePath, performanceBaselineSummary, performanceBudgetOverrides: { fastValidatorBudgetMs: parsedCli.fastValidatorBudgetMs,
slowValidatorBudgetMs: parsedCli.slowValidatorBudgetMs }, catalog: { schemaId: testCatalog.schemaId, sourcePath: testCatalog.sourcePath, capability: 'validator', duplicateDedupeKeys, obligationMap: focusedValidationObligations }, baselineFingerprintCount: baselineFingerprints.size, startedAt, results, runContext, dag }); persistRunSummary(runContext, summary, 'completed');
writePerformanceOutputIfRequested(summary, parsedCli.performanceOutputPath); emitSummary(summary, parsedCli.json); return summary.failed > 0 ? 1 : 0; function parseCliArgs(argv: any) { const positional: string[] = []; const options: { filters: string[]; parallel: boolean; json: boolean; legacy: boolean; cache: boolean; skipSlow: boolean; baselinePath: string | null; performanceBaselinePath: string | null;
performanceOutputPath: string | null; fastValidatorBudgetMs: number | null; slowValidatorBudgetMs: number | null; serial: boolean; focusPaths: string[]; focusChanged: boolean; runId: string | null; resume: string | null; status: boolean; validatorTimeoutMs: number | null; } = { filters: [], parallel: false, json: false, legacy: false, cache: false, skipSlow: false, baselinePath: null, performanceBaselinePath: null,
performanceOutputPath: null, fastValidatorBudgetMs: null, slowValidatorBudgetMs: null, serial: false, focusPaths: [], focusChanged: false, runId: null, resume: null, status: false, validatorTimeoutMs: null }; for (let index = 0; index < argv.length; index += 1) { const arg = argv[index]; if (arg === '--profile') { const valueText = String(argv[index + 1] ?? '').trim(); if (!valueText || valueText.startsWith('--')) { throw new Error('--profile requires a value'); } positional.unshift(valueText); index += 1; continue; } if (arg === '--filter') { const value = argv[index + 1]; const valueText = String(value ?? '');
if (!valueText || valueText.startsWith('--')) { throw new Error('--filter requires a value'); } options.filters.push(...valueText.split(',').map((entry: any) => entry.trim()).filter(Boolean)); index += 1; continue; } if (arg === '--grep' || arg.startsWith('--grep=')) { const valueText = arg.includes('=') ? arg.slice('--grep='.length) : String(argv[index + 1] ?? '');
const hintValue = valueText && !valueText.startsWith('--') ? valueText : '<name-or-tag>'; throw new Error(`Unsupported option: ${arg}. This validator facade uses --filter ${JSON.stringify(hintValue)} for validator names/tags, or --focus-path <path> for path-scoped selection.`); } if (arg === '--focus-path') { const value = argv[index + 1]; const valueText = String(value ?? '');
if (!valueText || valueText.startsWith('--')) { throw new Error('--focus-path requires a value'); } options.focusPaths.push(valueText); index += 1; continue; } if (arg === '--focus-paths') { const value = argv[index + 1]; const valueText = String(value ?? ''); if (!valueText || valueText.startsWith('--')) { throw new Error('--focus-paths requires a value'); }
options.focusPaths.push(...valueText.split(',').map((entry: string) => entry.trim()).filter(Boolean)); index += 1; continue; } if (arg === '--focus-changed') { options.focusChanged = true; continue; } if (arg === '--parallel') { options.parallel = true; continue; } if (arg === '--serial') { options.serial = true; continue; } if (arg === '--json') { options.json = true; continue; } if (arg === '--legacy') {
options.legacy = true; continue; } if (arg === '--cache') { options.cache = true; continue; } if (arg === '--skip-slow') { options.skipSlow = true; continue; } if (arg === '--baseline') { const value = argv[index + 1]; const valueText = String(value ?? ''); if (!valueText || valueText.startsWith('--')) { throw new Error('--baseline requires a validator summary JSON path'); } options.baselinePath = valueText;
index += 1; continue; } if (arg === '--performance-baseline') { const value = argv[index + 1]; const valueText = String(value ?? ''); if (!valueText || valueText.startsWith('--')) { throw new Error('--performance-baseline requires a validator summary JSON path'); } options.performanceBaselinePath = valueText; index += 1; continue; } if (arg === '--performance-output') { const value = argv[index + 1];
const valueText = String(value ?? ''); if (!valueText || valueText.startsWith('--')) { throw new Error('--performance-output requires an output JSON path'); } options.performanceOutputPath = valueText; index += 1; continue; } if (arg === '--fast-validator-budget-ms') { options.fastValidatorBudgetMs = parsePositiveIntegerOption(argv[index + 1], '--fast-validator-budget-ms'); index += 1; continue; }
if (arg === '--slow-validator-budget-ms') { options.slowValidatorBudgetMs = parsePositiveIntegerOption(argv[index + 1], '--slow-validator-budget-ms'); index += 1; continue; } if (arg === '--run-id') { const valueText = String(argv[index + 1] ?? '').trim(); if (!valueText || valueText.startsWith('--')) { throw new Error('--run-id requires a value'); } options.runId = valueText; index += 1; continue; }
if (arg === '--resume') { const valueText = String(argv[index + 1] ?? '').trim(); if (!valueText || valueText.startsWith('--')) { throw new Error('--resume requires a run id'); } options.resume = valueText; index += 1; continue; } if (arg === '--status') { options.status = true; continue; } if (arg === '--validator-timeout-ms') {
options.validatorTimeoutMs = parsePositiveIntegerOption(argv[index + 1], '--validator-timeout-ms'); index += 1; continue; } if (arg.startsWith('--')) { throw new Error(`Unsupported option: ${arg}`); } positional.push(arg); } return { profile: positional[0] ?? 'standard', ...options }; } function resolveProfileConfig(profileName: any) { const profile = config.profiles[profileName]; if (!profile) {
throw new Error(`Unknown validator profile: ${profileName}`); } return profile; } function resolveParallelSetting(parsedCli: any, profileConfig: any): boolean { if (parsedCli.legacy) { return false; } if (parsedCli.serial) { return false; } return parsedCli.parallel || profileConfig.parallelByDefault === true; } function parsePositiveIntegerOption(value: unknown, flag: string): number {
const valueText = String(value ?? ''); if (!valueText || valueText.startsWith('--')) { throw new Error(`${flag} requires a positive integer value`); } const parsed = Number(valueText); if (!Number.isInteger(parsed) || parsed <= 0) { throw new Error(`${flag} requires a positive integer value`); } return parsed; } function resolveProfileValidatorNames(profileName: any): string[] {
const profile = resolveProfileConfig(profileName); const inherited: string[] = profile.extends ? resolveProfileValidatorNames(profile.extends) : []; return [...new Set([...inherited, ...(profile.validators ?? [])])]; } function resolveFocusPaths(focusPaths: string[], focusChanged: boolean): string[] { const explicit = Array.isArray(focusPaths) ? focusPaths.map(normalizeFocusPath).filter(Boolean) : [];
if (!focusChanged) { return [...new Set(explicit)]; } return [...new Set([...explicit, ...readChangedPaths()])]; } function applyFocusRules(validatorNames: string[], focusPaths: string[]): string[] { if (!Array.isArray(focusPaths) || focusPaths.length === 0) { return validatorNames; } const normalizedPaths = focusPaths.map(normalizeFocusPath); const matchedValidatorNames = new Set<string>();
for (const rule of config.focusRules ?? []) { const patterns = Array.isArray(rule.patterns) ? rule.patterns : []; const validators = Array.isArray(rule.validators) ? rule.validators : []; if (patterns.some((pattern: string) => normalizedPaths.some((candidatePath) => focusPatternMatches(pattern, candidatePath)))) { for (const validatorName of validators) { matchedValidatorNames.add(String(validatorName)); } } }
if (matchedValidatorNames.size === 0) { return validatorNames; } return validatorNames.filter((name) => matchedValidatorNames.has(name)); } function resolveCatalogValidatorSelection(profileName: string, focusPaths: string[]): { names: string[]; entries: TestCatalogEntry[]; duplicateDedupeKeys: string[] } { const tier = profileToCatalogTier(profileName);
const obligationNames = resolveExecutableObligationValidatorNames(focusPaths); if (!tier) { const names = applyFocusRules(resolveProfileValidatorNames(profileName), focusPaths); return { names: mergeValidatorNames(names, obligationNames), entries: [], duplicateDedupeKeys: [] }; } const selection = selectTestEntries({ catalog: testCatalog, capability: 'validator', tier, changedFiles: focusPaths });
const executableEntries = selection.entries.filter((entry) => entry.validatorName && validatorMap.has(entry.validatorName)); if (focusPaths.length > 0 && executableEntries.length === 0) { const fallbackNames = applyFocusRules(resolveProfileValidatorNames(profileName), focusPaths); return { names: mergeValidatorNames(fallbackNames, obligationNames), entries: [], duplicateDedupeKeys: [] }; }
const names = mergeValidatorNames(executableEntries.map((entry) => String(entry.validatorName)), obligationNames); return { names, entries: executableEntries, duplicateDedupeKeys: selection.duplicateDedupeKeys }; } function resolveExecutableObligationValidatorNames(focusPaths: string[]): string[] { if (!Array.isArray(focusPaths) || focusPaths.length === 0) { return []; }
return resolveValidationObligations(focusPaths).validators .filter((name) => name !== 'typecheck') .filter((name) => validatorMap.has(name)); } function mergeValidatorNames(primary: string[], required: string[]): string[] { return [...new Set([...primary, ...required])]; } function profileToCatalogTier(profileName: string): TestTier | null { return normalizeTier(profileName); }
function applyFilters(validatorNames: any, filters: any) { if (!filters || filters.length === 0) { return validatorNames; } return validatorNames.filter((name: any) => { const entry: any = validatorMap.get(name); if (!entry) { return false; } return filters.some((filter: any) => { if (filter.startsWith('tag:')) { const tag = filter.slice(4).toLowerCase();
return (entry.tags ?? []).some((candidate: any) => String(candidate).toLowerCase() === tag); } const needle = filter.toLowerCase(); const byName = name.toLowerCase().includes(needle); const byTag = (entry.tags ?? []).some((candidate: any) => String(candidate).toLowerCase().includes(needle)); return byName || byTag; }); }); }
function orderValidatorsByDependencies(validators: any[]): any[] { const byName = new Map(validators.map((validator: any) => [String(validator.name), validator])); const visiting = new Set<string>(); const visited = new Set<string>(); const ordered: any[] = []; const visit = (validator: any) => { const name = String(validator.name); if (visited.has(name)) return; if (visiting.has(name)) { throw new Error(`Validator dependency cycle includes ${name}`); } visiting.add(name); for (const dependencyName of Array.isArray(validator.dependsOn) ? validator.dependsOn.map(String) : []) { const dependency = byName.get(dependencyName); if (dependency) visit(dependency); } visiting.delete(name); visited.add(name); ordered.push(validator); }; for (const validator of validators) visit(validator); return ordered; } function createValidatorDagReport(validators: any[]) { const nodes = validators.map((validator: any, index: number) => ({ name: validator.name, index, dependsOn: Array.isArray(validator.dependsOn) ? validator.dependsOn.map(String) : [], cacheSharingKey: validator.cacheSharingKey ?? validator.catalogKey ?? null, tier: validator.slow === true ? 'full' : 'default' })); const edges = nodes.flatMap((node: any) => node.dependsOn.map((dependency: string) => ({ from: dependency, to: node.name }))); const cacheSharingGroups = [...nodes.reduce((groups: Map<string, any[]>, node: any) => { if (!node.cacheSharingKey) return groups; const group = groups.get(node.cacheSharingKey) ?? []; group.push(node.name); groups.set(node.cacheSharingKey, group); return groups; }, new Map<string, any[]>()).entries()].map(([cacheSharingKey, validatorNames]) => ({ cacheSharingKey, validatorNames, fanOutEligible: validatorNames.length > 1 })); return { schemaId: 'atm.validatorDag.v1', nodeCount: nodes.length, edgeCount: edges.length, hasDependencies: edges.length > 0, nodes, edges, cacheSharingGroups }; }
function initializeRunContext({ parsedCli, profileConfig, selectedValidators, focusPaths, baseValidatorCount, focusReducedValidatorCount }: any) { if (!parsedCli.runId && !parsedCli.resume) { return null; } const runId = parsedCli.resume ?? parsedCli.runId ?? createValidatorRunId(); const runDir = path.join(VALIDATOR_RUNS_ROOT, runId); mkdirSync(runDir, { recursive: true });
const manifestPath = path.join(runDir, 'manifest.json'); const summaryPath = path.join(runDir, 'summary.partial.json'); const receiptsDir = path.join(runDir, 'receipts'); mkdirSync(receiptsDir, { recursive: true }); const previousManifest = existsSync(manifestPath) ? readJsonFile(manifestPath) : null; const previousAttempts = Array.isArray(previousManifest?.attempts) ? previousManifest.attempts : [];
const attempt = previousAttempts.length + 1; const headCommit = readGitHead(); const selectionFingerprint = buildSelectionFingerprint({ profile: parsedCli.profile, mode: profileConfig.mode, filters: parsedCli.filters, focusPaths, validatorNames: selectedValidators.map((entry: any) => String(entry.name)) }); const validatorFingerprints = Object.fromEntries(selectedValidators.map((validator: any) => {
const validatorPath = path.join(root, validator.entry); const command = `node --strip-types ${normalizeCommandPath(validator.entry)} --mode ${profileConfig.mode}`; return [validator.name, buildValidatorRunFingerprint({ validator, mode: profileConfig.mode, command, validatorPath, profile: parsedCli.profile, selectionFingerprint, headCommit })]; })); const receiptReuseAllowed = parsedCli.resume
? isResumeCompatible(previousManifest, { profile: parsedCli.profile, mode: profileConfig.mode, selectionFingerprint, headCommit }) : false; const manifest = { schemaId: 'atm.validatorRunManifest.v1', runId, profile: parsedCli.profile, mode: profileConfig.mode, parallel: resolveParallelSetting(parsedCli, profileConfig), cache: parsedCli.cache, focusPaths, filters: parsedCli.filters,
focusMode: parsedCli.focusChanged ? 'changed' : (focusPaths.length > 0 ? 'paths' : 'none'), baseValidatorCount, focusReducedValidatorCount, startedAt: previousManifest?.startedAt ?? new Date().toISOString(), updatedAt: new Date().toISOString(), selectionFingerprint, headCommit, receiptReuseAllowed, attempt, attempts: [ ...previousAttempts, { attempt, startedAt: new Date().toISOString(),
resumedFrom: parsedCli.resume ?? null } ], validators: selectedValidators.map((validator: any) => ({ name: validator.name, entry: validator.entry, fingerprint: validatorFingerprints[validator.name] })) }; writeJsonFile(manifestPath, manifest); for (const validator of selectedValidators) { ensureValidatorReceipt({ receiptsDir, validatorName: validator.name, fingerprint: validatorFingerprints[validator.name], attempt
}); } return { enabled: true, runId, resumed: Boolean(parsedCli.resume), attempt, runDir, manifestPath, summaryPath, receiptsDir, selectionFingerprint, headCommit, validatorFingerprints, receiptReuseAllowed }; } function createValidatorRunId(): string { return `run-${new Date().toISOString().replace(/[:.]/g, '-').replace('Z', 'Z')}-${process.pid}`; } function runStatusQueryAndExit(parsedCli: any): never {
const runId = String(parsedCli.runId ?? parsedCli.resume ?? '').trim(); if (!runId) { process.stderr.write('--status requires --run-id <id> or --resume <id>.\n'); process.exitCode = 2; process.exit(2); } const runDir = path.join(VALIDATOR_RUNS_ROOT, runId); const manifestPath = path.join(runDir, 'manifest.json'); if (!existsSync(manifestPath)) { const notFound = { schemaId: 'atm.validatorRunStatus.v1', runId,
found: false }; process.stdout.write(`${JSON.stringify(notFound, null, 2)}\n`); process.exitCode = 1; process.exit(1); } const manifest = readJsonFile(manifestPath); const receiptsDir = path.join(runDir, 'receipts'); const receiptFiles = existsSync(receiptsDir) ? readdirSync(receiptsDir).filter((entry: string) => entry.endsWith('.json')) : []; const validators = receiptFiles.map((fileName: string) => {
const receipt = readJsonFile(path.join(receiptsDir, fileName)); return { name: receipt.validatorName ?? path.basename(fileName, '.json'), status: receipt.status ?? 'unknown', lastAttempt: receipt.lastAttempt ?? null, updatedAt: receipt.updatedAt ?? null }; }); const counts = validators.reduce((acc: Record<string, number>, entry: any) => { acc[entry.status] = (acc[entry.status] ?? 0) + 1;
acc.total = (acc.total ?? 0) + 1; return acc; }, {} as Record<string, number>); const outstanding = validators.filter((entry: any) => entry.status !== 'passed' && entry.status !== 'failed' && entry.status !== 'timeout'); const summaryPath = path.join(runDir, 'summary.partial.json'); const lastSummary = existsSync(summaryPath) ? readJsonFile(summaryPath) : null; const status = { schemaId: 'atm.validatorRunStatus.v1',
runId, found: true, profile: manifest.profile ?? null, mode: manifest.mode ?? null, attempt: manifest.attempt ?? null, startedAt: manifest.startedAt ?? null, updatedAt: manifest.updatedAt ?? null, latestPhase: manifest.latestPhase ?? null, completed: outstanding.length === 0 && validators.length > 0, outstandingValidators: outstanding.map((entry: any) => entry.name), counts, validators,
lastSummaryPhase: lastSummary?.phase ?? null, lastSummaryTotals: lastSummary ? { total: lastSummary.total, passed: lastSummary.passed, failed: lastSummary.failed } : null, resumeCommand: outstanding.length > 0 ? `node --strip-types scripts/run-validators.ts ${manifest.profile ?? 'standard'} --resume ${runId} --json` : null }; process.stdout.write(`${JSON.stringify(status, null, 2)}\n`); process.exitCode = 0;
process.exit(0); } function buildSelectionFingerprint({ profile, mode, filters, focusPaths, validatorNames }: any): string { const fingerprint = { schemaId: 'atm.validatorSelectionFingerprint.v1', profile, mode, filters: Array.isArray(filters) ? [...filters] : [], focusPaths: Array.isArray(focusPaths) ? [...focusPaths] : [], validatorNames: Array.isArray(validatorNames) ? [...validatorNames] : [] };
return sha256Json(fingerprint); } function buildValidatorRunFingerprint({ validator, mode, command, validatorPath, profile, selectionFingerprint, headCommit }: any): string { const fingerprint = { schemaId: 'atm.validatorRunFingerprint.v2', validator: validator.name, entry: validator.entry, mode, profile, command, selectionFingerprint, headCommit, sourceDigest: safeFileSha256(validatorPath) };
return sha256Json(fingerprint); } function isResumeCompatible(previousManifest: any, current: any): boolean { if (!previousManifest) { return false; } return previousManifest.profile === current.profile && previousManifest.mode === current.mode && previousManifest.selectionFingerprint === current.selectionFingerprint && previousManifest.headCommit === current.headCommit; }
function ensureValidatorReceipt({ receiptsDir, validatorName, fingerprint, attempt }: any): void { const receiptPath = path.join(receiptsDir, `${validatorName}.json`); if (existsSync(receiptPath)) { return; } writeJsonFile(receiptPath, { schemaId: 'atm.validatorRunReceipt.v1', validatorName, status: 'pending', fingerprint, attempts: [], lastAttempt: attempt, updatedAt: new Date().toISOString() }); }
function readValidatorReceipt(runContext: any, validatorName: string): any | null { if (!runContext) return null; const receiptPath = path.join(runContext.receiptsDir, `${validatorName}.json`); return existsSync(receiptPath) ? readJsonFile(receiptPath) : null; } function writeValidatorReceipt(runContext: any, validatorName: string, receipt: any): void { if (!runContext) return;
const receiptPath = path.join(runContext.receiptsDir, `${validatorName}.json`); writeJsonFile(receiptPath, receipt); } function shouldReuseReceipt({ runContext, validator, allowCanonicalReuse = true }: any): any | null { const command = `node --strip-types ${normalizeCommandPath(validator.entry)} --mode ${runContext?.mode ?? ''}`.trim(); if (runContext?.resumed && runContext.receiptReuseAllowed === true) {
const receipt = readValidatorReceipt(runContext, validator.name); if (receipt?.status === 'passed' && receipt.result?.ok === true) { return markReceiptReuseResult(receipt.result, 'run-local'); } } if (!allowCanonicalReuse) return null; const canonical = readReusableValidationReceipt({ cwd: root, validatorName: validator.name, command: command || `node --strip-types ${normalizeCommandPath(validator.entry)}`,
gitHead: readGitHead(), scopePaths: resolveValidationReceiptScopePaths(validator) }); if (!canonical.reusable || !canonical.receipt?.result) return null; return markReceiptReuseResult(canonical.receipt.result, 'canonical'); } async function runValidatorsSequential(validators: any, mode: any, options: any) { const results: any[] = []; for (const validator of validators) {
const rawResult = await runValidator(validator, mode, options); const result = markResultAgainstBaseline(rawResult, options.baselineFingerprints ?? new Set()); results.push(result); persistPartialSummary(options, results, 'running'); if (options.stopOnFailure && result.ok !== true) { break; } } return results; } function runValidator(validator: any, mode: any, options: any): Promise<any> {
return new Promise<any>((resolve) => { const startedAt = Date.now(); const validatorPath = path.join(root, validator.entry); const command = `node --strip-types ${normalizeCommandPath(validator.entry)} --mode ${mode}`; const cacheKey = buildValidatorCacheKey(validator, mode, command, validatorPath); const resumed = shouldReuseReceipt({ runContext: options.runContext ? { ...options.runContext, mode } : { mode },
validator, allowCanonicalReuse: !Number.isFinite(options.validatorTimeoutMs) }); if (resumed) { if (options.runContext) { persistValidatorReceiptResult({ runContext: options.runContext, validatorName: validator.name, fingerprint: options.runContext?.validatorFingerprints?.[validator.name] ?? null, result: { ...resumed, cacheDecision: resumed.cached === true ? 'cache-hit' : 'receipt-reuse' }, status: 'passed' }); } resolve({ ...resumed, cacheDecision: resumed.cached === true ? 'cache-hit' : 'receipt-reuse' }); return; }
const runFingerprint = options.runContext?.validatorFingerprints?.[validator.name] ?? null; const cacheEnabled = options.cache === true; if (options.runContext) { const receipt = readValidatorReceipt(options.runContext, validator.name) ?? { schemaId: 'atm.validatorRunReceipt.v1', validatorName: validator.name, attempts: [] }; writeValidatorReceipt(options.runContext, validator.name, { ...receipt, validatorName: validator.name, fingerprint: runFingerprint,
status: 'running', lastAttempt: options.runContext.attempt, updatedAt: new Date().toISOString(), attempts: [ ...(Array.isArray(receipt.attempts) ? receipt.attempts : []), { attempt: options.runContext.attempt, startedAt: new Date().toISOString(), status: 'running' } ] }); } if (cacheEnabled) { const cached = readValidatorCache(cacheKey); if (cached) { const cachedResult = { ...cached, cached: true, cacheDecision: 'cache-hit', durationMs: 0,
envelope: { ...cached.envelope, durationMs: 0 } }; if (options.runContext) { persistValidatorReceiptResult({ runContext: options.runContext, validatorName: validator.name, fingerprint: runFingerprint, result: cachedResult, status: 'passed' }); } persistCanonicalValidationReceipt({ validator, command, result: cachedResult, status: 'passed' }); resolve(cachedResult); return; } } let stdout = ''; let stderr = '';
let spawnError: string | null = null; let settled = false; let timedOut = false; let child: ReturnType<typeof spawn>; try { child = spawn(process.execPath, ['--strip-types', validatorPath, '--mode', mode], { cwd: root, stdio: ['ignore', 'pipe', 'pipe'] }); } catch (error) { finalize(1, formatSpawnError(error)); return; } runningValidatorChildren.add(child);
const timeoutMs = Number.isFinite(options.validatorTimeoutMs) ? Number(options.validatorTimeoutMs) : null; const timeoutHandle = timeoutMs !== null ? setTimeout(() => { if (settled) return; timedOut = true; killChild(child, 'SIGTERM'); }, timeoutMs) : null; child.stdout?.on('data', (chunk) => { stdout += String(chunk); }); child.stderr?.on('data', (chunk) => { stderr += String(chunk); });
child.on('error', (error) => { finalize(1, `${error.name}: ${error.message}`); }); child.on('close', (code) => { finalize(timedOut ? 124 : (code ?? 1)); }); function finalize(exitCode: number, immediateSpawnError: string | null = null) { if (settled) return; settled = true; runningValidatorChildren.delete(child); if (timeoutHandle) { clearTimeout(timeoutHandle); }
spawnError = immediateSpawnError ?? (timedOut ? `Validator exceeded --validator-timeout-ms budget of ${timeoutMs}ms and was killed.` : spawnError); const durationMs = Date.now() - startedAt; const envelope = createValidatorFailureEnvelope({ validatorName: validator.name, command, entry: validator.entry, mode, ok: exitCode === 0, exitCode, durationMs, stdout, stderr, spawnError }); if (!options.json) { if (stdout) {
process.stdout.write(stdout); } if (stderr) { process.stderr.write(stderr); } if (!envelope.ok) { process.stderr.write(`[validator-envelope:${validator.name}] ${JSON.stringify({ requiredCommand: envelope.requiredCommand, blockingFindings: envelope.blockingFindings, repairHints: envelope.repairHints }, null, 2)}\n`); } } const result = { name: validator.name, entry: validator.entry, tags: validator.tags ?? [],
slow: validator.slow === true, performanceBudgetMs: Number.isFinite(validator.performanceBudgetMs) ? Number(validator.performanceBudgetMs) : null, catalogKey: validator.catalogKey ?? null, capability: validator.capability ?? 'validator', family: validator.family ?? null, scope: validator.scope ?? null, dedupeKeys: validator.dedupeKeys ?? [],
catalogCostBudgetMs: Number.isFinite(validator.catalogCostBudgetMs) ? Number(validator.catalogCostBudgetMs) : null, mode, ok: exitCode === 0, exitCode, durationMs, command, cacheKey, cached: false, cacheDecision: cacheEnabled ? 'cache-miss' : 'cache-bypass', timedOut, requiredCommand: envelope.requiredCommand, blockingFindings: envelope.blockingFindings, envelope }; if (options.runContext) { persistValidatorReceiptResult({ runContext: options.runContext,
validatorName: validator.name, fingerprint: runFingerprint, result, status: timedOut ? 'timeout' : (result.ok === true ? 'passed' : 'failed') }); } persistCanonicalValidationReceipt({ validator, command, result, status: timedOut ? 'timeout' : (result.ok === true ? 'passed' : 'failed') }); if (options.cache && result.ok === true) { writeValidatorCache(cacheKey, result); } resolve(result); } }); }
function markReceiptReuseResult(result: any, source: 'run-local' | 'canonical') { return { ...result, resumedFromReceipt: source === 'run-local', reusedFromCanonicalReceipt: source === 'canonical', durationMs: 0, cached: result.cached === true, envelope: { ...result.envelope, durationMs: 0 } }; } function persistCanonicalValidationReceipt({ validator, command, result, status }: { validator: any; command: string;
result: Record<string, unknown>; status: ValidationReceiptStatus; }) { const receipt = buildValidationReceiptInput({ cwd: root, validatorName: validator.name, command, status, ok: result.ok === true, gitHead: readGitHead(), result, scopePaths: resolveValidationReceiptScopePaths(validator) }); writeValidationReceipt(root, receipt); } function resolveValidationReceiptScopePaths(validator: any): string[] {
const paths = new Set<string>(); if (typeof validator.entry === 'string' && validator.entry.trim()) { paths.add(normalizeFocusPath(validator.entry)); } paths.add('scripts/run-validators.ts'); paths.add('scripts/validators.config.json'); for (const entry of Array.isArray(validator.scope) ? validator.scope : []) { if (typeof entry === 'string' && entry.trim()) { paths.add(normalizeFocusPath(entry)); } }
for (const key of Array.isArray(validator.dedupeKeys) ? validator.dedupeKeys : []) { if (typeof key === 'string' && key.includes('/')) { paths.add(normalizeFocusPath(key)); } } return [...paths].filter(Boolean); }
function createValidatorUsageTelemetry({ results, dag, profile, mode }: any) { const dagNodes = new Map<string, any>((dag?.nodes ?? []).map((node: any) => [String(node.name), node])); const cacheGroups = new Map<string, number>(); for (const node of dag?.nodes ?? []) { if (node.cacheSharingKey) cacheGroups.set(String(node.cacheSharingKey), (cacheGroups.get(String(node.cacheSharingKey)) ?? 0) + 1); } const validators = results.map((result: any) => { const node: any = dagNodes.get(String(result.name)) ?? {}; const cacheDecision = result.cacheDecision ?? (result.cached === true ? 'cache-hit' : result.ok === true && result.cacheKey ? 'cache-miss' : 'cache-bypass'); const fanOutConsumerCount = node.cacheSharingKey ? Math.max(0, (cacheGroups.get(String(node.cacheSharingKey)) ?? 1) - 1) : 0; const blockingCount = Array.isArray(result.blockingFindings) ? result.blockingFindings.length : 0; return { schemaId: 'atm.validatorUsageCounter.v1', validatorId: result.name, validatorVersion: result.cacheKey ?? result.entry ?? null, tier: result.slow === true ? 'full' : 'default', invocationCount: cacheDecision === 'cache-hit' || cacheDecision === 'receipt-reuse' ? 0 : 1, skippedCount: cacheDecision === 'cache-hit' || cacheDecision === 'receipt-reuse' ? 1 : 0, durationMs: Number(result.durationMs ?? 0), failureCount: result.ok === true ? 0 : 1, blockingCount, cacheHit: cacheDecision === 'cache-hit' ? 1 : 0, cacheMiss: cacheDecision === 'cache-miss' ? 1 : 0, cacheBypass: cacheDecision === 'cache-bypass' || cacheDecision === 'receipt-reuse' ? 1 : 0, cacheDecision, fanOutConsumerCount, downstreamIncidentRef: null, usedForDecision: blockingCount > 0 || cacheDecision === 'cache-hit' || fanOutConsumerCount > 0 }; }); const archiveCandidates = validators.filter((entry: any) => entry.invocationCount === 0 && entry.blockingCount === 0 && entry.fanOutConsumerCount === 0).map((entry: any) => entry.validatorId); return { schemaId: 'atm.validatorUsageTelemetry.v1', profile, mode, validatorCount: validators.length, invocationCount: validators.reduce((sum: number, entry: any) => sum + entry.invocationCount, 0), skippedCount: validators.reduce((sum: number, entry: any) => sum + entry.skippedCount, 0), cacheHits: validators.reduce((sum: number, entry: any) => sum + entry.cacheHit, 0), cacheMisses: validators.reduce((sum: number, entry: any) => sum + entry.cacheMiss, 0), cacheBypasses: validators.reduce((sum: number, entry: any) => sum + entry.cacheBypass, 0), fanOutCoverage: validators.filter((entry: any) => entry.fanOutConsumerCount > 0).length, archiveCandidates, dataDrivenDecision: validators.length > 0 ? 'm1-baseline-captured' : 'observability-missing', validators }; }
function createSummary({ profile, mode, filters, focusPaths, focusMode, baseValidatorCount, focusReducedValidatorCount, parallel, legacy, cache, skipSlow, baselinePath, performanceBaselinePath, performanceBaselineSummary, performanceBudgetOverrides, catalog, baselineFingerprintCount, startedAt, results, runContext, dag }: any) { const durationMs = Date.now() - startedAt;
const passed = results.filter((entry: any) => entry.ok === true).length; const failed = results.length - passed; const envelopes = results.map((entry: any) => entry.envelope).filter(Boolean); const blockingFindings = summarizeBlockingFindings(envelopes); const baselineFailures = dedupeFindings(envelopes.flatMap((envelope: any) => envelope.baselineFailures ?? []));
const currentTaskFailures = dedupeFindings(envelopes.flatMap((envelope: any) => envelope.currentTaskFailures ?? [])); const environmentFindings = blockingFindings.filter(isEnvironmentFinding); const currentTaskFindings = currentTaskFailures.length > 0 ? currentTaskFailures : blockingFindings.filter((finding: any) => !isEnvironmentFinding(finding) && !isBaselineFinding(finding));
const performance = createPerformanceReport({ profile, durationMs, results, profileConfig, performanceBudgetOverrides, performanceBaselineSummary, duplicateDedupeKeys: catalog?.duplicateDedupeKeys ?? [] }); const selection = createSelectionReport({ profile, baseValidatorCount: baseValidatorCount ?? results.length, focusReducedValidatorCount: focusReducedValidatorCount ?? results.length, focusMode, results, catalog
}); const resolvedDag = dag ?? createValidatorDagReport(results); const usageTelemetry = createValidatorUsageTelemetry({ results, dag: resolvedDag, profile, mode }); const lifecycleTelemetry = buildValidatorLifecycleSummary({ profile, mode, durationMs, validators: results, usageTelemetry, dag: resolvedDag, config
}); return { schemaId: 'atm.validatorRunSummary.v1', profile, mode, total: results.length, passed, failed, durationMs, filters, focusPaths: focusPaths ?? [], focusMode: focusMode ?? 'none', baseValidatorCount: baseValidatorCount ?? results.length, focusReducedValidatorCount: focusReducedValidatorCount ?? results.length, parallel, legacy, cache, skipSlow, run: runContext ? { schemaId: 'atm.validatorRunCheckpoint.v1',
enabled: true, runId: runContext.runId, resumed: runContext.resumed === true, attempt: runContext.attempt, runDir: path.relative(root, runContext.runDir).replace(/\\/g, '/'), summaryPath: path.relative(root, runContext.summaryPath).replace(/\\/g, '/') } : { schemaId: 'atm.validatorRunCheckpoint.v1', enabled: false }, baselinePath: baselinePath ?? null, performanceBaselinePath: performanceBaselinePath ?? null,
baselineFingerprintCount: baselineFingerprintCount ?? 0, cached: results.filter((entry: any) => entry.cached === true).length, resumed: results.filter((entry: any) => entry.resumedFromReceipt === true).length, selection, performance, dag: resolvedDag, usageTelemetry, lifecycleTelemetry, validatorLifecycle: lifecycleTelemetry, requiredCommand: firstRequiredCommand(envelopes), blockingFindings, baselineFailures, currentTaskFailures, environmentFindings, currentTaskFindings,
currentTaskOk: currentTaskFindings.length === 0 && environmentFindings.length === 0, taskLevelOk: currentTaskFindings.length === 0 && environmentFindings.length === 0, focusedValidatorCommand: buildFocusedValidatorCommand(results), validators: results }; } function emitSummary(summary: any, jsonMode: any) { if (jsonMode) { process.stdout.write(`${JSON.stringify(summary, null, 2)}\n`); return; }
const status = summary.failed === 0 ? 'ok' : 'failed'; process.stdout.write(`[validators:${summary.profile}] ${status} (passed=${summary.passed}, failed=${summary.failed}, total=${summary.total}, cached=${summary.cached}, durationMs=${summary.durationMs})\n`); for (const warning of summary.performance?.warnings ?? []) {
process.stderr.write(`[validators:${summary.profile}:performance] ${warning.code} ${warning.message}\n`); } } function normalizeCommandPath(relativePath: string): string { return relativePath.split(path.sep).join('/'); } function normalizeFocusPath(relativePath: string): string { return String(relativePath || '').replace(/\\/g, '/').replace(/^\.\//, ''); }
function focusPatternMatches(pattern: string, candidatePath: string): boolean { const escaped = String(pattern || '') .replace(/\\/g, '/') .replace(/[|\\{}()[\]^$+?.]/g, '\\$&') .replace(/\*\*/g, '::DOUBLE_STAR::') .replace(/\*/g, '[^/]*') .replace(/::DOUBLE_STAR::/g, '.*'); return new RegExp(`^${escaped}$`, 'i').test(candidatePath); } function readChangedPaths(): string[] {
const result = spawnSync('git', ['status', '--porcelain=v1', '--untracked-files=all'], { cwd: root, encoding: 'utf8', env: createSanitizedGitEnv() }); if (result.status !== 0) { return []; } const changed = new Set<string>(); for (const rawLine of String(result.stdout ?? '').split(/\r?\n/)) { if (!rawLine.trim()) continue; const normalized = normalizePorcelainPath(rawLine); if (normalized) { changed.add(normalized);
} } return [...changed]; } function normalizePorcelainPath(rawLine: string): string | null { const line = String(rawLine || ''); if (line.length < 4) { return null; } const payload = line.slice(3).trim(); if (!payload) { return null; } const renameParts = payload.split(' -> '); return normalizeFocusPath(renameParts[renameParts.length - 1]); } function createSanitizedGitEnv(): NodeJS.ProcessEnv {
const env = { ...process.env }; for (const key of ['GIT_INDEX_FILE', 'GIT_DIR', 'GIT_WORK_TREE', 'GIT_PREFIX', 'GIT_COMMON_DIR', 'GIT_NAMESPACE']) { delete env[key]; } return env; } function formatSpawnError(error: unknown): string { if (error instanceof Error) { const code = 'code' in error && typeof (error as any).code === 'string' ? ` (${(error as any).code})` : ''; return `${error.name}: ${error.message}${code}`;
} return String(error); } function readValidatorEnvWhitelist(): Record<string, string> { return Object.fromEntries(Object.entries(process.env).filter(([key, value]) => key.startsWith('ATM_VALIDATOR_') && typeof value === 'string').sort(([left], [right]) => left.localeCompare(right)) as [string, string][]); } function buildValidatorCacheKey(validator: any, mode: string, command: string, validatorPath: string): string { const sourceDigest = safeFileSha256(validatorPath); const fingerprint = { schemaId: 'atm.validatorCacheKey.v3', validator: validator.name, validatorVersion: sourceDigest, entry: validator.entry, mode, command, sourceDigest, gitHead: readGitHead(), toolchain: { node: process.version, platform: process.platform, arch: process.arch, packageLockDigest: safeFileSha256(path.join(root, 'package-lock.json')) }, envWhitelist: readValidatorEnvWhitelist() }; return crypto.createHash('sha256').update(JSON.stringify(fingerprint)).digest('hex'); }
function validatorCachePath(cacheKey: string): string { return path.join(root, '.atm', 'runtime', 'validator-cache', `${cacheKey}.json`); } function readValidatorCache(cacheKey: string): any | null { const filePath = validatorCachePath(cacheKey); if (!existsSync(filePath)) return null; try { const parsed = JSON.parse(readFileSync(filePath, 'utf8'));
const result = parsed?.schemaId === 'atm.validatorRunCache.v1' ? parsed.result ?? null : null; return result?.ok === true ? result : null; } catch { return null; } } function writeValidatorCache(cacheKey: string, result: any): void { const filePath = validatorCachePath(cacheKey); mkdirSync(path.dirname(filePath), { recursive: true }); writeFileSync(filePath, `${JSON.stringify({ schemaId: 'atm.validatorRunCache.v1',
cacheKey, generatedAt: new Date().toISOString(), result }, null, 2)}\n`, 'utf8'); } function markResultAgainstBaseline(result: any, baselineFingerprints: ReadonlySet<string>): any { if (!result?.envelope || baselineFingerprints.size === 0) return result; const envelope = applyBaselineFailureSnapshot(result.envelope, baselineFingerprints); return { ...result, requiredCommand: envelope.requiredCommand,
blockingFindings: envelope.blockingFindings, envelope }; } function readBaselineSummary(baselinePath: string): unknown { const resolved = path.resolve(root, baselinePath); if (!existsSync(resolved)) { throw new Error(`Baseline validator summary not found: ${baselinePath}`); } return JSON.parse(readFileSync(resolved, 'utf8').replace(/^\uFEFF/, '')); }
function writePerformanceOutputIfRequested(summary: any, outputPath: string | null): void { if (!outputPath) return; const resolved = path.resolve(root, outputPath); mkdirSync(path.dirname(resolved), { recursive: true }); writeFileSync(resolved, `${JSON.stringify(summary, null, 2)}\n`, 'utf8'); } function persistPartialSummary(options: any, results: any[], phase: 'running' | 'completed'): void {
if (!options?.runContext || !options?.summaryInput) { return; } const summary = createSummary({ ...options.summaryInput, results, runContext: options.runContext, dag: options.summaryInput.dag }); persistRunSummary(options.runContext, summary, phase); } function persistRunSummary(runContext: any, summary: any, phase: 'running' | 'completed'): void { if (!runContext) return; writeJsonFile(runContext.summaryPath, { ...summary, phase,
updatedAt: new Date().toISOString() }); const manifest = readJsonFile(runContext.manifestPath); writeJsonFile(runContext.manifestPath, { ...manifest, updatedAt: new Date().toISOString(), latestPhase: phase, latestSummaryPath: path.relative(root, runContext.summaryPath).replace(/\\/g, '/') }); } function persistValidatorReceiptResult({ runContext, validatorName, fingerprint, result, status }: any): void {
if (!runContext) return; const receipt = readValidatorReceipt(runContext, validatorName) ?? { schemaId: 'atm.validatorRunReceipt.v1', validatorName, attempts: [] }; const attempts = Array.isArray(receipt.attempts) ? [...receipt.attempts] : []; if (attempts.length > 0 && attempts[attempts.length - 1]?.attempt === runContext.attempt) { attempts[attempts.length - 1] = { ...attempts[attempts.length - 1],
finishedAt: new Date().toISOString(), status }; } else { attempts.push({ attempt: runContext.attempt, startedAt: new Date().toISOString(), finishedAt: new Date().toISOString(), status }); } writeValidatorReceipt(runContext, validatorName, { ...receipt, validatorName, fingerprint, status, lastAttempt: runContext.attempt, updatedAt: new Date().toISOString(), attempts, result }); }
function readJsonFile(filePath: string): any { return JSON.parse(readFileSync(filePath, 'utf8').replace(/^\uFEFF/, '')); } function writeJsonFile(filePath: string, value: unknown): void { mkdirSync(path.dirname(filePath), { recursive: true }); writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8'); } function sha256Json(value: unknown): string {
return crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex'); } function readGitHead(): string | null { const result = spawnSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8', env: createSanitizedGitEnv() }); if (result.status !== 0) { return null; } const head = String(result.stdout ?? '').trim(); return head || null; }
function createPerformanceReport({ profile, durationMs, results, profileConfig, performanceBudgetOverrides, performanceBaselineSummary, duplicateDedupeKeys }: any) { const budgetMs = Number.isFinite(profileConfig?.performanceBudgetMs) ? Number(profileConfig.performanceBudgetMs) : null; const performanceDefaults = resolvePerformanceDefaults();
const fastValidatorBudgetMs = Number.isFinite(performanceBudgetOverrides?.fastValidatorBudgetMs) ? Number(performanceBudgetOverrides.fastValidatorBudgetMs) : performanceDefaults.fastValidatorBudgetMs; const slowValidatorBudgetMs = Number.isFinite(performanceBudgetOverrides?.slowValidatorBudgetMs) ? Number(performanceBudgetOverrides.slowValidatorBudgetMs) : performanceDefaults.slowValidatorBudgetMs;
const slowestValidators = [...results] .sort((left: any, right: any) => Number(right.durationMs ?? 0) - Number(left.durationMs ?? 0)) .slice(0, 10) .map((entry: any) => ({ name: entry.name, durationMs: entry.durationMs, durationBudgetMs: resolveValidatorDurationBudget(entry, fastValidatorBudgetMs, slowValidatorBudgetMs),
overBudgetMs: Math.max(0, Number(entry.durationMs ?? 0) - resolveValidatorDurationBudget(entry, fastValidatorBudgetMs, slowValidatorBudgetMs)), cached: entry.cached === true, slow: entry.slow === true, catalogKey: entry.catalogKey ?? null, family: entry.family ?? null, command: entry.command })); const baselineByName = new Map( Array.isArray((performanceBaselineSummary as any)?.validators)
? (performanceBaselineSummary as any).validators.map((entry: any) => [String(entry.name ?? ''), entry]) : [] ); const warnings: any[] = []; const optimizationCandidates: any[] = []; if (budgetMs !== null && durationMs > budgetMs) { const finding = { code: 'ATM_VALIDATOR_PROFILE_BUDGET_EXCEEDED', message: `profile ${profile} took ${durationMs}ms, over budget ${budgetMs}ms`, profile, durationMs, budgetMs,
remediation: 'Inspect performance.slowestValidators and split or narrow heavyweight validators before adding more cases.' }; warnings.push(finding); optimizationCandidates.push({ kind: 'profile-budget', profile, severity: 'high', durationMs, budgetMs, overBudgetMs: durationMs - budgetMs, rationale: finding.message, remediation: finding.remediation }); } const budgetViolations = results
.filter((entry: any) => entry.cached !== true) .flatMap((entry: any) => { const durationBudgetMs = resolveValidatorDurationBudget(entry, fastValidatorBudgetMs, slowValidatorBudgetMs); const durationMsValue = Number(entry.durationMs ?? 0); if (!Number.isFinite(durationMsValue) || durationMsValue <= durationBudgetMs) return []; return [{ code: 'ATM_VALIDATOR_DURATION_BUDGET_EXCEEDED', validatorName: entry.name,
durationMs: durationMsValue, durationBudgetMs, overBudgetMs: durationMsValue - durationBudgetMs, slow: entry.slow === true, key: entry.catalogKey ?? null, family: entry.family ?? null, command: entry.command, message: `${entry.name} took ${durationMsValue}ms, over budget ${durationBudgetMs}ms`,
remediation: 'Reduce fixture scope, split broad assertions, use focused regressions, or explicitly raise the validator budget with justification.' }]; }); warnings.push(...budgetViolations); optimizationCandidates.push(...budgetViolations.map((entry: any) => ({ kind: 'validator-budget', validatorName: entry.validatorName, severity: entry.overBudgetMs >= 5_000 ? 'high' : 'medium', durationMs: entry.durationMs,
durationBudgetMs: entry.durationBudgetMs, overBudgetMs: entry.overBudgetMs, rationale: entry.message, remediation: entry.remediation }))); const regressions = results .filter((entry: any) => entry.cached !== true) .flatMap((entry: any) => { const baseline = baselineByName.get(String(entry.name ?? '')) as any; const baselineDurationMs = Number(baseline?.durationMs ?? 0);
const currentDurationMs = Number(entry.durationMs ?? 0); if (!Number.isFinite(baselineDurationMs) || baselineDurationMs <= 0 || !Number.isFinite(currentDurationMs)) return []; const deltaMs = currentDurationMs - baselineDurationMs; const ratio = currentDurationMs / baselineDurationMs; if (deltaMs < 1000 || ratio < 1.5) return []; return [{ code: 'ATM_VALIDATOR_DURATION_REGRESSION', validatorName: entry.name,
baselineDurationMs, durationMs: currentDurationMs, deltaMs, ratio: Number(ratio.toFixed(2)), message: `${entry.name} grew from ${baselineDurationMs}ms to ${currentDurationMs}ms`, remediation: 'Check fixture size, temp-repo setup, broad scans, and duplicated validator coverage before raising the budget.' }]; }); warnings.push(...regressions); optimizationCandidates.push(...regressions.map((entry: any) => ({
kind: 'validator-regression', validatorName: entry.validatorName, severity: entry.deltaMs >= 5_000 ? 'high' : 'medium', durationMs: entry.durationMs, baselineDurationMs: entry.baselineDurationMs, deltaMs: entry.deltaMs, ratio: entry.ratio, rationale: entry.message, remediation: entry.remediation }))); const familyHotspots = createFamilyHotspots(results, fastValidatorBudgetMs, slowValidatorBudgetMs);
const overweightFamilies = familyHotspots .filter((entry: any) => entry.validatorCount >= 5 || entry.totalDurationShare >= 0.25) .map((entry: any) => ({ code: 'ATM_VALIDATOR_FAMILY_OVERWEIGHT', familyId: entry.familyId, familyLabel: entry.familyLabel, validatorCount: entry.validatorCount, totalDurationMs: entry.totalDurationMs, totalDurationShare: entry.totalDurationShare,
overBudgetValidators: entry.overBudgetValidators, message: `${entry.familyLabel} owns ${entry.validatorCount} validators and ${Math.round(entry.totalDurationShare * 100)}% of profile runtime`, remediation: 'Consider routing this family from task scope first, sharing one source inventory across sibling validators, or merging repeated assertions into a family runner.' })); warnings.push(...overweightFamilies);
optimizationCandidates.push(...overweightFamilies.map((entry: any) => ({ kind: 'family-overweight', familyId: entry.familyId, familyLabel: entry.familyLabel, severity: entry.totalDurationShare >= 0.35 || entry.validatorCount >= 8 ? 'high' : 'medium', validatorCount: entry.validatorCount, totalDurationMs: entry.totalDurationMs, totalDurationShare: entry.totalDurationShare,
overBudgetValidators: entry.overBudgetValidators, rationale: entry.message, remediation: entry.remediation }))); return { schemaId: 'atm.validatorPerformanceReport.v1', profile, durationMs, budgetMs, fastValidatorBudgetMs, slowValidatorBudgetMs, baselinePresent: performanceBaselineSummary !== null && performanceBaselineSummary !== undefined, warningCount: warnings.length, slowestValidators,
slowestEntries: slowestValidators, familyHotspots, duplicateDedupeKeys: Array.isArray(duplicateDedupeKeys) ? duplicateDedupeKeys : [], budgetViolations, regressions, optimizationCandidates, warnings }; } function createSelectionReport({ profile, baseValidatorCount, focusReducedValidatorCount, focusMode, results, catalog }: any) { const familySummary = summarizeFamilies(results); const headCommit = readGitHead();
const dominantFamilies = familySummary .filter((entry: any) => entry.validatorCount > 0) .sort((left: any, right: any) => right.validatorCount - left.validatorCount) .slice(0, 5); return { schemaId: 'atm.validatorSelectionReport.v1', catalogSchemaId: catalog?.schemaId ?? null, catalogSourcePath: catalog?.sourcePath ?? null, capability: catalog?.capability ?? 'validator', profile,
totalCatalogValidators: Array.isArray(config.validators) ? config.validators.length : results.length, baseProfileValidatorCount: baseValidatorCount, selectedValidatorCount: results.length, focusReducedValidatorCount, focusMode: focusMode ?? 'none', duplicateDedupeKeys: Array.isArray(catalog?.duplicateDedupeKeys) ? catalog.duplicateDedupeKeys : [], obligationMap: catalog?.obligationMap ?? null,
sealedCommitCanary: headCommit ? createSealedCommitCanaryPlan({ commitSha: headCommit, validators: catalog?.obligationMap?.validators ?? [] }) : null, familyCount: familySummary.length, dominantFamilies, families: familySummary }; } function createFamilyHotspots(results: any[], fastValidatorBudgetMs: number, slowValidatorBudgetMs: number) {
const totalDurationMs = Math.max(1, results.reduce((sum: number, entry: any) => sum + Number(entry.durationMs ?? 0), 0)); return summarizeFamilies(results) .map((entry: any) => ({ ...entry, averageDurationMs: entry.validatorCount > 0 ? Math.round(entry.totalDurationMs / entry.validatorCount) : 0, totalDurationShare: Number((entry.totalDurationMs / totalDurationMs).toFixed(4)),
overBudgetValidators: entry.validators.filter((validator: any) => { const budget = resolveValidatorDurationBudget(validator, fastValidatorBudgetMs, slowValidatorBudgetMs); return Number(validator.durationMs ?? 0) > budget; }).length })) .filter((entry: any) => entry.validatorCount > 0) .sort((left: any, right: any) => { if (right.totalDurationMs !== left.totalDurationMs) {
return right.totalDurationMs - left.totalDurationMs; } return right.validatorCount - left.validatorCount; }); } function summarizeFamilies(results: any[]): any[] { const mappedResults = results.map((entry: any) => { const family = resolveSelectionFamily(entry); return { ...entry, familyId: family.id, familyLabel: family.label, familyDescription: family.description }; }); const grouped = new Map<string, any>();
for (const entry of mappedResults) { const bucket = grouped.get(entry.familyId) ?? { familyId: entry.familyId, familyLabel: entry.familyLabel, description: entry.familyDescription, validatorCount: 0, totalDurationMs: 0, validators: [] }; bucket.validatorCount += 1; bucket.totalDurationMs += Number(entry.durationMs ?? 0); bucket.validators.push({ name: entry.name, durationMs: Number(entry.durationMs ?? 0),
slow: entry.slow === true, cached: entry.cached === true, tags: Array.isArray(entry.tags) ? entry.tags : [] }); grouped.set(entry.familyId, bucket); } return [...grouped.values()].sort((left: any, right: any) => { if (right.validatorCount !== left.validatorCount) { return right.validatorCount - left.validatorCount; } return right.totalDurationMs - left.totalDurationMs; }); }
function resolveSelectionFamily(entry: any) { if (entry?.family) { const configured = selectionFamilies.find((family: any) => String(family?.id ?? '') === String(entry.family)); return { id: String(entry.family), label: String(configured?.label ?? entry.family), description: String(configured?.description ?? '') }; }
const tags = Array.isArray(entry?.tags) ? entry.tags.map((tag: any) => String(tag).toLowerCase()) : []; for (const family of selectionFamilies) { const matchTags = Array.isArray(family?.matchTags) ? family.matchTags.map((tag: any) => String(tag).toLowerCase()) : []; if (matchTags.some((tag: string) => tags.includes(tag))) { return { id: String(family.id), label: String(family.label ?? family.id),
description: String(family.description ?? '') }; } } return { id: 'misc', label: 'Miscellaneous', description: 'Validators not yet assigned to a managed family.' }; } function resolveValidatorDurationBudget(entry: any, fastValidatorBudgetMs: number, slowValidatorBudgetMs: number): number { if (Number.isFinite(entry?.performanceBudgetMs)) { return Number(entry.performanceBudgetMs); }
const configEntry: any = validatorMap.get(entry?.name); if (Number.isFinite(configEntry?.performanceBudgetMs)) { return Number(configEntry.performanceBudgetMs); } return entry?.slow === true ? slowValidatorBudgetMs : fastValidatorBudgetMs; } function resolvePerformanceDefaults() { const defaults = config.performanceDefaults ?? {}; return { fastValidatorBudgetMs: Number.isFinite(defaults.fastValidatorBudgetMs)
? Number(defaults.fastValidatorBudgetMs) : DEFAULT_FAST_VALIDATOR_BUDGET_MS, slowValidatorBudgetMs: Number.isFinite(defaults.slowValidatorBudgetMs) ? Number(defaults.slowValidatorBudgetMs) : DEFAULT_SLOW_VALIDATOR_BUDGET_MS }; } function buildFocusedValidatorCommand(results: readonly any[]): string | null { const failingCurrentTask = results.find((entry) => (entry.envelope?.currentTaskFailures ?? []).length > 0);
if (failingCurrentTask?.command) { return String(failingCurrentTask.command); } const firstFailed = results.find((entry) => entry.ok !== true); if (firstFailed?.command) { return String(firstFailed.command); } return null; } function safeFileSha256(filePath: string): string | null { try { return `sha256:${crypto.createHash('sha256').update(readFileSync(filePath)).digest('hex')}`; } catch { return null; } }
function isEnvironmentFinding(finding: any): boolean { const code = String(finding?.code ?? ''); const source = String(finding?.source ?? ''); const classification = String(finding?.classification ?? ''); return classification === 'environment' || source === 'environment' || source === 'git-index' || code.startsWith('ATM_ENV_') || code.startsWith('ATM_GIT_INDEX_'); }
function isBaselineFinding(finding: any): boolean { return String(finding?.classification ?? '') === 'baseline' || String(finding?.source ?? '') === 'baseline'; } function dedupeFindings(findings: readonly any[]): readonly any[] { const seen = new Set<string>(); const deduped: any[] = []; for (const finding of findings) {
const key = `${finding?.code ?? ''}\0${finding?.source ?? ''}\0${finding?.detail ?? ''}\0${finding?.requiredCommand ?? ''}`; if (seen.has(key)) continue; seen.add(key); deduped.push(finding); } return deduped; } }
