import { execFileSync } from 'node:child_process'; import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs'; import path from 'node:path'; import { getCommandSpec } from '../command-specs.ts'; import { buildResidueDiagnosisEvidence, generateTaskCard, loadTaskDocumentOrThrow, runTasks, runTasksRosterUpdate } from '../tasks/public-surface.ts';
import { inspectHistoricalDelivery } from '../tasks/historical-delivery.ts'; import { assertClosebackPlanningPathReady, buildCloseBackendArgv, buildClosebackPlan, buildCloseWriteRollbackSnapshot, buildTaskflowCloseDiagnostics, executeCloseWriteCommitPhase, resolveClosebackPlanningPath, resolveCloseWriteSupport, capturePlanningCardSnapshot, applyPlanningCardCloseback, resolvePlanningRosterPaths,
type PlanningCardCloseback } from './closeback-orchestration.ts'; import { buildAutoEvidencePlan, executeAutoEvidencePlan } from '../evidence.ts'; import { mapAutoEvidenceCommand, type PackageJsonLike } from './auto-evidence-mapper.ts'; import { CliError, makeResult, message, parseArgsForCommand, quoteCliValue, relativePathFrom } from '../shared.ts'; import { buildDelegationContract, buildTaskflowOpenDiagnostics,
loadProfile, resolveOpenerMode, resolveWriteSupport, type TaskflowProfileV1 } from './profile-loader.ts'; import { canResolveHostOpenerPolicy, resolveHostOpenerPolicyDecision } from './host-opener-policy.ts'; import { buildTaskflowCommitMessage } from './commit-messages.ts'; import { buildTaskflowClosePreflight, inspectPlanningAuthorityDelivery, preflightBlockersToWriteReadinessBlockers } from './close-preflight.ts';
import { withTaskflowOperatorLane } from '../emergency/context.ts'; import { isRunnerSyncRequired } from '../framework-development.ts'; import { buildTaskflowCloseWriteReadinessHint, prioritizeSharedHistoricalDeliveryBlockers } from './write-readiness.ts'; import { resolveTaskflowDeclaredFiles } from './task-scope.ts'; import { assertCommitBundleReady, buildTaskflowCommitBundle, commitTaskflowDeliveryFiles,
deferGovernanceDirtyFiles, finalizeTaskflowCommitBundle, readStagedFiles, restoreDeferredGovernanceDirtyFiles, type DeferredGovernanceDirtyReport, type TaskflowCommitMode, type TaskflowGovernedCommitBundle } from './commit-bundle-assembly.ts'; import { acquireCloseWindowStagedIndexLock, releaseCloseWindowStagedIndexLock, type CloseWindowStagedIndexLockReport } from '../tasks/close-window-lock.ts';
import { promoteTeamHandoffArchive, teamHandoffRuntimeDirectory } from '../../../../core/src/team-runtime/handoff-ledger.ts'; import { clearBrokerRuntimeStateForTask } from '../../../../core/src/broker/lifecycle.ts'; interface DeferredGovernanceDirtyFile { file: string; snapshotPath: string; originalSha256: string; restoredAt: string | null; } function buildTasksNewCommand(input: { taskId?: string | null;
outputPath?: string | null; template?: string | null; title?: string | null; }): string { const parts = ['node atm.mjs tasks new']; if (input.template) { parts.push(`--template ${input.template}`); } if (input.taskId) { parts.push(`--task-id ${input.taskId}`); } if (input.title) { parts.push(`--title ${JSON.stringify(input.title)}`); } if (input.outputPath) { parts.push(`--output ${input.outputPath}`); }
return parts.join(' '); } function buildRosterSyncCommand(input: { indexPath: string; fromPath: string; dryRun?: boolean; }): string { const parts = ['node atm.mjs tasks roster update', `--index ${input.indexPath}`, `--from ${input.fromPath}`]; if (input.dryRun) { parts.push('--dry-run'); } parts.push('--json'); return parts.join(' '); } async function runRosterSyncFollowUp(input: { command: string; cwd: string;
indexPath: string; fromPath: string; messages: ReturnType<typeof message>[]; }): Promise<{ mode: 'follow-up-command'; command: string; result: Awaited<ReturnType<typeof runTasksRosterUpdate>>; }> { let result: Awaited<ReturnType<typeof runTasksRosterUpdate>> | null = null; try { result = await runTasksRosterUpdate([ '--cwd', input.cwd, '--index', input.indexPath, '--from', input.fromPath ]);
} catch (error: unknown) { const caught = error instanceof Error ? { message: error.message, name: error.name } : { message: String(error), name: 'UnknownError' }; result = makeResult({ ok: false, command: 'tasks roster update', cwd: input.cwd, mode: 'standalone', messages: [ message('error', 'ATM_TASK_ROSTER_SYNC_FOLLOWUP_EXCEPTION', `Roster follow-up command failed before writing: ${caught.message}`, caught) ],
evidence: { indexPath: input.indexPath, fromPath: input.fromPath, followUpCommand: input.command, syncMode: 'follow-up-command', failure: caught } }); } if (!result.ok) { input.messages.push(message( 'warn', 'ATM_TASKFLOW_ROSTER_SYNC_FOLLOWUP_FAILED', `${input.command} returned non-ok result; please rerun this follow-up command manually.`,
{ command: input.command, indexPath: input.indexPath, fromPath: input.fromPath } )); } return { mode: 'follow-up-command', command: input.command, result }; } function buildTasksImportCommand(input: { fromPath: string; }): string { return `node atm.mjs tasks import --from ${quoteCliValue(input.fromPath)} --write --json`; } function buildTaskflowOpenDryRunCommand(input: { profilePath?: string | null;
taskId?: string | null; outputPath?: string | null; title?: string | null; }): string { const parts = ['node atm.mjs taskflow open --dry-run']; if (input.profilePath) parts.push(`--profile ${quoteCliValue(input.profilePath)}`); if (input.taskId) parts.push(`--task-id ${quoteCliValue(input.taskId)}`); if (input.outputPath) parts.push(`--output ${quoteCliValue(input.outputPath)}`);
if (input.title) parts.push(`--title ${quoteCliValue(input.title)}`); parts.push('--json'); return parts.join(' '); } function readPackageJsonForAutoEvidence(cwd: string): PackageJsonLike | null { const pkgPath = path.join(cwd, 'package.json'); if (!existsSync(pkgPath)) return null; try { const raw = readFileSync(pkgPath, 'utf8'); const parsed = JSON.parse(raw); if (parsed && typeof parsed === 'object') {
return parsed as PackageJsonLike; } return null; } catch { return null; } } function buildOrchestrationPlan(input: { profile: TaskflowProfileV1 | null; openerMode: ReturnType<typeof resolveOpenerMode>; delegationContract: ReturnType<typeof buildDelegationContract>; outputRoot?: string | null; taskId?: string | null; outputPath?: string | null; template?: string | null; title?: string | null;
rosterIndexPath?: string | null; hostPolicyDecision?: ReturnType<typeof resolveHostOpenerPolicyDecision> | null; profilePath?: string | null; }) { const resolvedTaskId = input.hostPolicyDecision?.taskId ?? input.taskId ?? null; const resolvedOutputPath = input.hostPolicyDecision?.outputPath ?? input.outputPath ?? null; const followUpSteps: string[] = ['generate-via-tasks-new'];
if (input.delegationContract.hostOpenerAvailable) { followUpSteps.unshift('resolve-delegation'); } if (input.hostPolicyDecision?.sources.taskId === 'host-policy') { followUpSteps.push('allocate-task-id-via-host-policy'); } if (input.hostPolicyDecision?.sources.outputPath === 'host-policy') { followUpSteps.push('resolve-output-path-via-host-policy'); } if (input.openerMode === 'template-only-fallback') {
followUpSteps.push('operator-supply-task-id-and-output'); } if (resolvedOutputPath) { followUpSteps.push('import-into-runtime'); } const rosterSyncPolicy = input.delegationContract.policy.rosterSyncPolicy; const rosterIndexPath = input.rosterIndexPath ?? input.delegationContract.policy.rosterSync.indexPath; let rosterFollowUpCommand: string | null = null;
if (rosterSyncPolicy === 'follow-up-command' && rosterIndexPath && resolvedOutputPath) { rosterFollowUpCommand = buildRosterSyncCommand({ indexPath: rosterIndexPath, fromPath: resolvedOutputPath }); followUpSteps.push('roster-sync-follow-up-command'); } else if (rosterSyncPolicy === 'inline' && rosterIndexPath && resolvedOutputPath) { followUpSteps.push('roster-sync-inline'); } return {
generationSurface: 'tasks-new' as const, wouldInvokeTasksNew: true, wouldInvokeTasksImport: Boolean(resolvedOutputPath), tasksNewCommand: buildTasksNewCommand({ taskId: resolvedTaskId, outputPath: resolvedOutputPath, template: input.template, title: input.title }), tasksImportCommand: resolvedOutputPath ? buildTasksImportCommand({
fromPath: input.outputRoot ? resolveOutputAbsolute(input.outputRoot, resolvedOutputPath) : resolvedOutputPath }) : null, hostOpenerInvocation: input.delegationContract.displayHint, planningCard: resolvedOutputPath, targetRepository: input.profile?.ownerRepo ?? 'adopter-repo', nextDryRunCommand: buildTaskflowOpenDryRunCommand({ profilePath: input.profilePath, taskId: resolvedTaskId, outputPath: resolvedOutputPath,
title: input.title }), nextImportCommand: resolvedOutputPath ? buildTasksImportCommand({ fromPath: input.outputRoot ? resolveOutputAbsolute(input.outputRoot, resolvedOutputPath) : resolvedOutputPath }) : null, rosterSyncPolicy, rosterIndexPath, rosterFollowUpCommand, followUpRequired: input.openerMode === 'template-only-fallback' || !resolvedTaskId || !resolvedOutputPath
|| (rosterSyncPolicy === 'follow-up-command' && Boolean(rosterFollowUpCommand)), followUpSteps, targetRepo: input.profile?.ownerRepo ?? 'adopter-repo', outputRepoRoot: input.outputRoot ?? null, profileRepoLabel: input.profile?.repoLabel ?? 'adopter-repo', policyDecision: { allocateTaskId: input.delegationContract.policy.allocateTaskId,
resolveCanonicalOutputPath: input.delegationContract.policy.resolveCanonicalOutputPath, rosterSyncPolicy, rosterSyncIndexPath: rosterIndexPath, fallbackBehavior: input.delegationContract.policy.fallbackBehavior }, hostPolicyDecision: input.hostPolicyDecision ?? null }; } type TaskflowOpenWriteReadinessStatus = 'ready' | 'fallback' | 'incomplete'; interface TaskflowOpenWriteReadinessHint {
schemaId: 'atm.taskflowOpenWriteReadinessHint.v1'; status: TaskflowOpenWriteReadinessStatus; summary: string; missingPrerequisites: string[]; nextCommand: string | null; operatorLane: 'taskflow open'; fallbackSurface: 'tasks new (low-level generator)' | null; } interface TaskflowCloseKnownBlocker { readonly code: string; readonly summary: string; readonly requiredCommand: string | null; readonly files?: readonly string[]; readonly multiTaskCloseRecipe?: string | null; }
interface TaskflowBranchCommitQueueGate { readonly schemaId: 'atm.taskflowBranchCommitQueueGate.v1'; readonly status: 'clear' | 'busy'; readonly branchRef: string | null; readonly branchName: string; readonly lockPath: string | null; readonly actorId: string | null; readonly summary: string; readonly requiredCommand: string | null; } interface TaskflowCloseWriteReadinessHint {
readonly schemaId: 'atm.taskflowCloseWriteReadinessHint.v1'; readonly status: 'ready' | 'blocked'; readonly summary: string; readonly blockers: readonly TaskflowCloseKnownBlocker[]; readonly nextCommand: string | null; readonly operatorLane: 'taskflow close'; readonly brokerConflictGate: TaskflowBrokerConflictGate; readonly branchCommitQueueGate: TaskflowBranchCommitQueueGate; } interface TaskflowBrokerConflictGate {
readonly schemaId: 'atm.taskflowBrokerConflictGate.v1'; readonly verdict: 'confirmedConflict' | 'takeoverRequired' | 'insufficientMutationIntent' | 'noConflict'; readonly confirmedConflict: boolean; readonly overlappingTaskIds: readonly string[]; readonly summary: string; readonly requiredCommand: string | null; readonly brokerVerdict: string | null; readonly decisionClass: 'serial-release' | 'blocked' | null;
readonly decisionReason: string | null; readonly violationStatus: 'broker-conflict-blocked' | null; readonly statusCode: 'broker-conflict-blocked' | null; } function uniqueTaskIds(values: readonly string[]): readonly string[] { return [...new Set(values.map((value) => value.trim()).filter(Boolean))]; } function buildWriteReadinessHint(input: { openerMode: ReturnType<typeof resolveOpenerMode>;
delegationContract: ReturnType<typeof buildDelegationContract>; hostPolicyDecision: ReturnType<typeof resolveHostOpenerPolicyDecision> | null; taskId: string | null; outputPath: string | null; profileLoaded: boolean; }): TaskflowOpenWriteReadinessHint { if (input.openerMode === 'delegated-governed') { return { schemaId: 'atm.taskflowOpenWriteReadinessHint.v1', status: 'ready',
summary: 'taskflow open --write is ready to orchestrate the governed opener lane.', missingPrerequisites: [], nextCommand: 'node atm.mjs taskflow open --write --json', operatorLane: 'taskflow open', fallbackSurface: null }; } const policy = input.delegationContract.policy; const missing: string[] = []; if (!input.profileLoaded) {
missing.push('Load a planning/adopter profile via --profile <adopter-repo>/taskflow.profile.json'); } else if (!input.delegationContract.invocable) { missing.push('Profile delegation must declare an invocable host opener (delegation.openerPath set and delegation.writerInvocation.describeOnly = false)'); } const resolvedTaskId = input.hostPolicyDecision?.taskId ?? input.taskId;
if (policy.allocateTaskId.mode !== 'host-opener' && !resolvedTaskId) { missing.push('Either set delegation.policy.allocateTaskId.mode = "host-opener" in the profile, or pass --task-id TASK-XXX-NNNN explicitly'); } const resolvedOutputPath = input.hostPolicyDecision?.outputPath ?? input.outputPath; if (policy.resolveCanonicalOutputPath.mode !== 'host-opener' && !resolvedOutputPath) {
missing.push('Either set delegation.policy.resolveCanonicalOutputPath.mode = "host-opener" in the profile, or pass --output <planning-relative-path> explicitly'); } const status: TaskflowOpenWriteReadinessStatus = input.openerMode === 'template-only-fallback' ? 'fallback' : 'incomplete'; const summary = status === 'fallback'
? 'taskflow open --write will fail closed in template-only-fallback mode. Configure the listed prerequisites, or use tasks new as the explicit low-level generator surface.' : 'taskflow open --write prerequisites are incomplete. Resolve the listed items before retrying --write.'; return { schemaId: 'atm.taskflowOpenWriteReadinessHint.v1', status, summary, missingPrerequisites: missing, nextCommand: null,
operatorLane: 'taskflow open', fallbackSurface: 'tasks new (low-level generator)' }; } function collectHistoricalDeliveryRefs(parsed: ReturnType<typeof parseArgsForCommand>): string[] { const refs: string[] = []; const historicalDelivery = parsed.options.historicalDelivery; if (Array.isArray(historicalDelivery)) { refs.push(...historicalDelivery.map(String));
} else if (typeof historicalDelivery === 'string' && historicalDelivery.trim()) { refs.push(historicalDelivery); } const deliveryCommit = parsed.options.deliveryCommit ? String(parsed.options.deliveryCommit) : null; if (deliveryCommit) { refs.push(deliveryCommit); } return [...new Set(refs)]; } function collectHistoricalBatchRef(parsed: ReturnType<typeof parseArgsForCommand>): string | null {
const value = parsed.options.historicalBatch; return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; } function collectWaiverOutOfScopeDelivery(parsed: ReturnType<typeof parseArgsForCommand>) { const waiverOutOfScopeDelivery = parsed.options.waiverOutOfScopeDelivery === true || parsed.options.waiveOutOfScope === true;
const reason = typeof parsed.options.reason === 'string' && parsed.options.reason.trim() ? parsed.options.reason.trim() : null; if (waiverOutOfScopeDelivery && !reason) { throw new CliError('ATM_TASKFLOW_CLOSE_WAIVER_REASON_REQUIRED', 'taskflow close --waiver-out-of-scope-delivery requires --reason <text>.', { exitCode: 2 }); } return { waiverOutOfScopeDelivery, waiverReason: reason }; }
function resolveHistoricalBatchPath(cwd: string, batchRef: string) { const trimmed = batchRef.trim(); if (!trimmed) return null; if (path.isAbsolute(trimmed)) return trimmed; if (trimmed.includes('/') || trimmed.includes('\\')) return path.resolve(cwd, trimmed); return path.join(cwd, '.atm', 'history', 'evidence', 'historical-batches', trimmed.endsWith('.json') ? trimmed : `${trimmed}.json`); }
function loadHistoricalBatchMatchedCommits(cwd: string, taskId: string, batchRef: string) { const batchPath = resolveHistoricalBatchPath(cwd, batchRef); if (!batchPath || !existsSync(batchPath)) { throw new CliError('ATM_TASKFLOW_CLOSE_HISTORICAL_BATCH_NOT_FOUND', `Historical batch evidence not found for ${batchRef}.`, { exitCode: 1,
details: { taskId, batchRef, batchPath: batchPath ? relativePathFrom(cwd, batchPath) : null } }); } const envelope = JSON.parse(readFileSync(batchPath, 'utf8')) as Record<string, unknown>; const tasks = Array.isArray(envelope.tasks) ? envelope.tasks : []; const rawSlice = tasks.find((entry) =>
entry && typeof entry === 'object' && !Array.isArray(entry) && String((entry as Record<string, unknown>).taskId ?? '') === taskId ) as Record<string, unknown> | undefined; if (!rawSlice) { throw new CliError('ATM_TASKFLOW_CLOSE_HISTORICAL_BATCH_TASK_NOT_FOUND', `Historical batch ${batchRef} does not contain task ${taskId}.`, { exitCode: 1, details: { taskId, batchRef, batchPath: relativePathFrom(cwd, batchPath) } });
} if (rawSlice.okToCloseTask !== true) { throw new CliError('ATM_TASKFLOW_CLOSE_HISTORICAL_BATCH_NOT_CLOSE_READY', `Historical batch ${batchRef} task slice for ${taskId} is not close-ready.`, { exitCode: 1, details: { taskId, batchRef, batchPath: relativePathFrom(cwd, batchPath), coverageStatus: rawSlice.coverageStatus ?? null, okToRecordEvidence: rawSlice.okToRecordEvidence === true,
okToCloseTask: rawSlice.okToCloseTask === true, diagnosticOnly: rawSlice.diagnosticOnly === true, missingCoverage: Array.isArray(rawSlice.missingCoverage) ? rawSlice.missingCoverage : [] } }); } return Array.isArray(rawSlice.matchedCommits) ? rawSlice.matchedCommits.filter((entry): entry is string => typeof entry === 'string' && entry.trim().length > 0) : []; }
function resolveExistingHistoricalBatchStageFile(cwd: string, batchRef?: string | null): string | null { if (!batchRef) return null; const batchPath = resolveHistoricalBatchPath(cwd, batchRef); if (!batchPath || !existsSync(batchPath)) return null; return normalizeRepoRelativePath(cwd, batchPath); } function normalizeRepoRelativePath(repoRoot: string, filePath: string): string {
const resolved = path.isAbsolute(filePath) ? filePath : path.resolve(repoRoot, filePath); return relativePathFrom(repoRoot, resolved).replace(/\\/g, '/'); } function uniqueSorted(values: readonly string[]): string[] { return [...new Set(values.map((value) => value.replace(/\\/g, '/')).filter(Boolean))].sort((a, b) => a.localeCompare(b)); }
function buildCloseOwnedDirtyPendingBlocker(input: { taskId: string; actorId: string; previewCommitBundle: TaskflowGovernedCommitBundle; dirtyGuard: { advisoryTrackedDirtyFiles?: readonly string[]; regenerableArtifactFiles?: readonly string[]; correctPlanningMirrorPreEditFiles?: readonly string[]; }; fallbackCommand: string | null; }): TaskflowCloseKnownBlocker | null { const advisoryDirty = new Set(uniqueSorted([ ...(input.dirtyGuard.advisoryTrackedDirtyFiles ?? []), ...(input.dirtyGuard.regenerableArtifactFiles ?? []), ...(input.dirtyGuard.correctPlanningMirrorPreEditFiles ?? []) ])); const closeOwnedFiles = uniqueSorted([ ...input.previewCommitBundle.targetRepo.stageFiles, ...input.previewCommitBundle.targetGovernanceFiles, ...input.previewCommitBundle.planningRepo.stageFiles, ...input.previewCommitBundle.planningFiles ]); const pendingFiles = closeOwnedFiles.filter((file) => advisoryDirty.has(file)); if (pendingFiles.length === 0) return null; const preview = pendingFiles.slice(0, 4).join(', '); const suffix = pendingFiles.length > 4 ? ` (+${pendingFiles.length - 4} more)` : ''; return { code: 'ATM_TASKFLOW_CLOSE_OWNED_DIRTY_PENDING', summary: `taskflow close owns pending dirty file(s) (${preview}${suffix}), but close --write is blocked by another readiness issue. Leaving them unstaged or uncommitted can block other lanes as foreign dirty work.`, requiredCommand: input.fallbackCommand ?? `node atm.mjs taskflow pre-close --task ${input.taskId} --actor ${quoteCliValue(input.actorId || '<actor>')} --json`, files: pendingFiles, multiTaskCloseRecipe: 'Finish taskflow close, commit the close-owned bundle, or explicitly hand off the listed files before claiming another lane.' }; }
function listExistingFilesRecursively(root: string, relativeDirectory: string): string[] { const directory = path.join(root, relativeDirectory); if (!existsSync(directory)) return []; const files: string[] = []; for (const entry of readdirSync(directory, { withFileTypes: true })) { const relativePath = path.posix.join(relativeDirectory.replace(/\\/g, '/'), entry.name);
const absolutePath = path.join(root, relativePath); if (entry.isDirectory()) { files.push(...listExistingFilesRecursively(root, relativePath)); } else if (entry.isFile()) { files.push(normalizeRepoRelativePath(root, absolutePath)); } } return files; } function tryGitScalar(cwd: string, args: readonly string[]): string | null { try { return execFileSync('git', [...args], { cwd, encoding: 'utf8',
stdio: ['ignore', 'pipe', 'pipe'] }).trim() || null; } catch { return null; } } function readGitRoot(startPath: string): string | null { const probe = existsSync(startPath) && statSync(startPath).isDirectory() ? startPath : path.dirname(startPath); const root = tryGitScalar(probe, ['rev-parse', '--show-toplevel']); return root ? path.resolve(root) : null; }
function resolveProfileRepoRoot(profilePath: string | null, fallbackCwd: string): string { if (!profilePath) return fallbackCwd; const resolvedProfilePath = path.resolve(profilePath); return readGitRoot(resolvedProfilePath) ?? path.dirname(resolvedProfilePath); } function resolveTaskflowOpenOutputRoot(input: { profilePath: string | null; profile: TaskflowProfileV1 | null; cwd: string; }): string {
if (!input.profile) return input.cwd; return resolveProfileRepoRoot(input.profilePath, input.cwd); } function resolveOutputAbsolute(root: string, outputPath: string): string { return path.isAbsolute(outputPath) ? path.resolve(outputPath) : path.resolve(root, outputPath); } function runGitOrThrow(cwd: string, args: readonly string[]) { execFileSync('git', [...args], { cwd, encoding: 'utf8',
stdio: ['ignore', 'pipe', 'pipe'] }); } async function runTaskflowClose(parsed: ReturnType<typeof parseArgsForCommand>, cwd: string, surface: 'close' | 'pre-close' = 'close') { const taskId = parsed.options.task ? String(parsed.options.task) : ''; const actorId = parsed.options.actor ? String(parsed.options.actor) : ''; const writeRequested = !!parsed.options.write;
const noCommitRequested = !!parsed.options.noCommit; const autoEvidenceRequested = parsed.options.autoEvidence === true; const deferForeignState = parsed.options.deferForeignState === true; const deferForeignStaged = parsed.options.deferForeignStaged === true || deferForeignState; const deferGovernanceDirty = parsed.options.deferGovernanceDirty === true || deferForeignState;
const commitMode: TaskflowCommitMode = writeRequested ? noCommitRequested ? 'stage-only' : 'auto-commit' : 'dry-run'; const profilePath = parsed.options.profile ? String(parsed.options.profile) : null; const historicalBatchRef = collectHistoricalBatchRef(parsed); const waiver = collectWaiverOutOfScopeDelivery(parsed); const explicitHistoricalDeliveryRefs = collectHistoricalDeliveryRefs(parsed);
const historicalBatchMatchedCommits = historicalBatchRef ? loadHistoricalBatchMatchedCommits(cwd, taskId, historicalBatchRef) : []; const historicalDeliveryRefs = uniqueSorted([ ...explicitHistoricalDeliveryRefs, ...historicalBatchMatchedCommits ]); if (!taskId) { throw new CliError('ATM_CLI_USAGE', `taskflow ${surface} requires --task <work-item-id>.`, { exitCode: 2 }); } if (surface === 'pre-close' && !actorId) {
throw new CliError('ATM_CLI_USAGE', 'taskflow pre-close requires --actor <id>.', { exitCode: 2 }); } let profileData: TaskflowProfileV1 | null = null; if (profilePath) { profileData = loadProfile(profilePath); } const delegationContract = buildDelegationContract(profileData); const { taskDocument } = loadTaskDocumentOrThrow(cwd, taskId); const profileRepoRoot = profilePath && profileData
? resolveProfileRepoRoot(profilePath, cwd) : null; const closebackPathResolution = resolveClosebackPlanningPath({ cwd, taskId, taskDocument, profile: profileData, profileRepoRoot, delegationContract }); if (profileData || writeRequested) { assertClosebackPlanningPathReady(closebackPathResolution, { profileSupplied: Boolean(profileData), requirePlanningPath: true }); }
const diagnosis = buildResidueDiagnosisEvidence(cwd, taskId, taskDocument); const enrichedDiagnosis = closebackPathResolution.planningMirrorPath ? { ...diagnosis, triangulation: { ...diagnosis.triangulation, planningFrontmatter: { status: closebackPathResolution.planningStatus ?? diagnosis.triangulation.planningFrontmatter.status, source: closebackPathResolution.planningMirrorPath } } } : diagnosis;
const planningAuthorityDeliveryGate = inspectPlanningAuthorityDelivery({ cwd, taskDocument, historicalDeliveryRefs, resolvedPlanningMirrorPath: closebackPathResolution.planningMirrorPath }); if ( planningAuthorityDeliveryGate.required && historicalDeliveryRefs.length > 0 && !planningAuthorityDeliveryGate.ok ) {
throw new CliError('ATM_TASKFLOW_CLOSE_PLANNING_DELIVERY_INVALID', 'taskflow close could not verify the supplied planning-repo delivery commit against the task deliverables.', { exitCode: 1, details: { taskId, planningAuthorityDeliveryGate, historicalDeliveryRefs } }); } const closebackPlan = buildClosebackPlan({ taskId, actorId: actorId || '<actor>', historicalDeliveryRefs, historicalBatchRef,
waiverOutOfScopeDelivery: waiver.waiverOutOfScopeDelivery, waiverReason: waiver.waiverReason, planningAuthorityDeliveryGate, delegationContract, diagnosis: { bucket: enrichedDiagnosis.bucket, truth: enrichedDiagnosis.truth, residue: enrichedDiagnosis.residue, reason: enrichedDiagnosis.reason, nextCommand: enrichedDiagnosis.nextCommand, triangulation: enrichedDiagnosis.triangulation }, closebackPathResolution });
const diagnostics = buildTaskflowCloseDiagnostics({ closeMode: closebackPlan.closeMode, writeRequested, actorSupplied: actorId.length > 0, taskIdSupplied: taskId.length > 0 }); const previewCommitBundle = buildTaskflowCommitBundle({ cwd, taskId, actorId: actorId || null, commitMode, planningMirrorPath: closebackPlan.writerBoundary.planningMirrorPath,
rosterIndexPath: closebackPlan.writerBoundary.rosterSyncPolicy === 'inline' ? closebackPlan.writerBoundary.rosterIndexPath : null, historicalDeliveryRefs, historicalBatchRef, planningAuthorityDeliveryOk: planningAuthorityDeliveryGate.ok }); const hasUncommittedDeliverables = previewCommitBundle.targetDeliveryFiles.length > 0; const declaredFiles = [...resolveTaskflowDeclaredFiles(cwd, taskId, taskDocument)];
const historicalClosePreflight = buildTaskflowClosePreflight({ cwd, taskId, actorId: actorId || '<actor>', taskDocument, previewCommitBundle, historicalDeliveryRefs, waiverOutOfScopeDelivery: waiver.waiverOutOfScopeDelivery, waiverReason: waiver.waiverReason }); let writeReadinessHint = buildTaskflowCloseWriteReadinessHint({ cwd, taskId, actorId, taskDocument, declaredFiles, closebackPlan, previewCommitBundle,
historicalDeliveryRefs, waiverOutOfScopeDelivery: waiver.waiverOutOfScopeDelivery, waiverReason: waiver.waiverReason, planningAuthorityDeliveryGate }); const staleRunnerBlockers = isRunnerSyncRequired(cwd) ? [{ code: 'ATM_TASKFLOW_PRECLOSE_STALE_RUNNER',
summary: 'The frozen runner (release/atm-onefile/atm.mjs) is older than framework source files; taskflow close --write will be refused with ATM_RUNNER_STALE_WRITE_REFUSED until the runner is rebuilt.', requiredCommand: 'ATM_RETAIN_RELEASE_ARTIFACTS=1 npm run build' }] : []; const baseWriteBlockers = [ ...writeReadinessHint.blockers, ...staleRunnerBlockers, ...preflightBlockersToWriteReadinessBlockers(historicalClosePreflight) ]; const closeOwnedDirtyPendingBlocker = baseWriteBlockers.length > 0 ? buildCloseOwnedDirtyPendingBlocker({ taskId, actorId: actorId || '<actor>', previewCommitBundle, dirtyGuard: historicalClosePreflight.dirtyGuard, fallbackCommand: baseWriteBlockers[0]?.requiredCommand ?? writeReadinessHint.nextCommand }) : null; if (baseWriteBlockers.length > 0 || closeOwnedDirtyPendingBlocker) {
const mergedBlockers = prioritizeSharedHistoricalDeliveryBlockers([ ...baseWriteBlockers, ...(closeOwnedDirtyPendingBlocker ? [closeOwnedDirtyPendingBlocker] : []) ], { taskId, actorId: actorId || '<actor>', historicalDeliveryRef: historicalDeliveryRefs[0] ?? null, outOfScopeFiles: historicalClosePreflight.mixedDeliveryCommit?.fileBuckets.outOfScopeSourceFiles ?? [] });
writeReadinessHint = { ...writeReadinessHint, status: 'blocked', summary: mergedBlockers[0]?.summary ?? `taskflow close --write has ${mergedBlockers.length} known blocker(s) that dry-run can already disclose.`, blockers: mergedBlockers, nextCommand: mergedBlockers[0]?.requiredCommand ?? writeReadinessHint.nextCommand }; } const packageJsonForAutoEvidencePlan = actorId ? readPackageJsonForAutoEvidence(cwd) : null;
const autoEvidencePlan = actorId ? buildAutoEvidencePlan({ cwd, taskId, actorId, mode: writeRequested && autoEvidenceRequested ? 'execute' : 'dry-run', commandMapper: (declared) => mapAutoEvidenceCommand(declared, packageJsonForAutoEvidencePlan).command }) : null; const preCloseWriteBlocked = writeReadinessHint.status === 'blocked'; const preCloseMessageLevel = historicalClosePreflight.ok && !preCloseWriteBlocked ? 'info' : 'warn'; const preCloseMessageCode = !historicalClosePreflight.ok ? 'ATM_TASKFLOW_PRECLOSE_BLOCKED' : preCloseWriteBlocked ? 'ATM_TASKFLOW_PRECLOSE_WRITE_NOT_READY' : 'ATM_TASKFLOW_PRECLOSE_READY'; const preCloseMessageText = !historicalClosePreflight.ok ? `taskflow pre-close found ${historicalClosePreflight.blockers.length} blocker(s) for ${taskId}; resolve them before taskflow close --write.` : preCloseWriteBlocked ? `taskflow pre-close found no preflight blockers for ${taskId}, but close --write is not ready; inspect writeReadinessHint.blockers before leaving this lane.` : `taskflow pre-close found no blockers for ${taskId}; inspect writeRollbackSummary before --write.`; if (surface === 'pre-close') { return { ...makeResult({ ok: historicalClosePreflight.ok && !preCloseWriteBlocked, command: 'taskflow pre-close', cwd, mode: 'pre-close', messages: [
message( preCloseMessageLevel, preCloseMessageCode, preCloseMessageText, { taskId, blockerCount: historicalClosePreflight.blockers.length, writeReadinessBlockerCount: writeReadinessHint.blockers.length } ) ], evidence: { historicalClosePreflight, writeReadinessHint, closebackPlan, governedCommitBundle: previewCommitBundle, residueDiagnosis: enrichedDiagnosis, closebackPathResolution,
...(autoEvidencePlan ? { autoEvidencePlan } : {}), ...(profileData ? { profile: profileData } : {}) } }), schemaId: 'atm.taskflowPreCloseResult.v1', writeEnabled: false, historicalClosePreflight }; } const writeSupport = resolveCloseWriteSupport({ writeRequested, closeMode: closebackPlan.closeMode, actorSupplied: actorId.length > 0, taskIdSupplied: taskId.length > 0,
historicalDeliveryGateRequired: closebackPlan.historicalDeliveryGate.required && !hasUncommittedDeliverables, historicalDeliverySupplied: historicalDeliveryRefs.length > 0 || historicalBatchRef !== null }); if (writeRequested && !writeSupport.allowed) { throw new CliError( closebackPlan.closeMode === 'ambiguous-manual-review' ? 'ATM_TASKFLOW_CLOSE_AMBIGUOUS_RESIDUE' : 'ATM_TASKFLOW_CLOSE_WRITE_BLOCKED',
writeSupport.reason, { exitCode: 1, details: { closeMode: closebackPlan.closeMode, writeSupport, diagnostics, closebackPlan, recommendedCommand: diagnosis.nextCommand } } ); } if (writeRequested) { assertCommitBundleReady(previewCommitBundle); } if (writeRequested && writeSupport.allowed) { let autoEvidenceExecution = null; if (autoEvidenceRequested) { if (!actorId) {
throw new CliError('ATM_CLI_USAGE', 'taskflow close --auto-evidence requires --actor <id>.', { exitCode: 2 }); } const packageJson = readPackageJsonForAutoEvidence(cwd); autoEvidenceExecution = executeAutoEvidencePlan({ cwd, taskId, actorId, commandMapper: (declared) => mapAutoEvidenceCommand(declared, packageJson).command }); if (!autoEvidenceExecution.ok) { throw new CliError( 'ATM_TASKFLOW_AUTO_EVIDENCE_FAILED',
`Auto-evidence could not satisfy declared validators for ${taskId}.`, { exitCode: 1, details: { taskId, failedValidator: autoEvidenceExecution.failedValidator, remediationCommand: autoEvidenceExecution.remediationCommand, autoEvidenceExecution } } ); } } if (previewCommitBundle.targetDeliveryFiles.length > 0 && commitMode !== 'auto-commit') {
throw new CliError('ATM_TASKFLOW_CLOSE_DELIVERY_COMMIT_REQUIRED', 'taskflow close --write --no-commit cannot close dirty source deliverables because backend close requires a delivery commit first. Rerun without --no-commit or commit through the governed taskflow close operator lane.', { exitCode: 1, details: { taskId, governedCommitBundle: previewCommitBundle,
remediation: `node atm.mjs taskflow close --task ${taskId} --actor ${actorId || '<actor>'} --write --json` } }); } const taskLedgerPath = path.join(cwd, '.atm/history/tasks', `${taskId}.json`); const previousTaskContent = existsSync(taskLedgerPath) ? readFileSync(taskLedgerPath, 'utf8') : ''; const planningCardSnapshot = capturePlanningCardSnapshot({ cwd,
planningMirrorPath: closebackPlan.writerBoundary.planningMirrorPath }); const expectedCloseWindowStageFiles = uniqueSorted([ ...previewCommitBundle.targetRepo.stageFiles, ...previewCommitBundle.targetDeliveryFiles, ...previewCommitBundle.targetGovernanceFiles ]); let closeWindowLock: CloseWindowStagedIndexLockReport | null = null; let closeWindowLockReleased = false;
let deferredGovernanceDirty = deferGovernanceDirtyFiles(cwd, deferGovernanceDirty, taskId); let deferredGovernanceDirtyRestored = false; try { closeWindowLock = acquireCloseWindowStagedIndexLock({ cwd, taskId, actorId, expectedStageFiles: expectedCloseWindowStageFiles, deferForeignStaged }); if (!closeWindowLock.ok) {
throw new CliError(closeWindowLock.blockedCode ?? 'ATM_CLOSE_WINDOW_STAGED_INDEX_BLOCKED', closeWindowLock.blockedSummary ?? 'Close window staged-index lock could not be acquired.', { exitCode: 1, details: { taskId, actorId, closeWindowLock, deferForeignStagedCommand: `node atm.mjs taskflow close --task ${taskId} --actor ${quoteCliValue(actorId)} --defer-foreign-staged --write --json` } }); }
const preCloseStagedFiles = readStagedFiles(cwd); const preCloseDeliveryCommit = await commitTaskflowDeliveryFiles({ bundle: previewCommitBundle, actorId, taskId, deferForeignStaged }); const effectiveHistoricalDeliveryRefs = preCloseDeliveryCommit?.commitSha ? uniqueSorted([...historicalDeliveryRefs, preCloseDeliveryCommit.commitSha]) : historicalDeliveryRefs; const backendArgv = buildCloseBackendArgv({ cwd, taskId,
actorId, backendSurface: closebackPlan.backendSurface, historicalDeliveryRefs: effectiveHistoricalDeliveryRefs, historicalBatchRef, historicalDeliveryRepo: closebackPlan.planningAuthorityDeliveryGate.ok ? closebackPlan.planningAuthorityDeliveryGate.repoRoot : null, waiverOutOfScopeDelivery: waiver.waiverOutOfScopeDelivery, waiverReason: waiver.waiverReason,
planningMirrorPath: closebackPlan.writerBoundary.planningMirrorPath, forceImport: diagnosis.bucket === 'stale-import' }); const ledgerAlreadyClosedHistoricalCloseback = closebackPlan.backendSurface === 'tasks-close' && closebackPlan.closeMode === 'historical-delivery-close' && enrichedDiagnosis.triangulation.liveLedger.status === 'done' && effectiveHistoricalDeliveryRefs.length > 0;
const backendResult = ledgerAlreadyClosedHistoricalCloseback ? makeResult({ ok: true, command: 'tasks close', cwd, mode: 'taskflow-closeback-reconcile', messages: [ message('info', 'ATM_TASKFLOW_CLOSE_LEDGER_ALREADY_DONE', 'Live task ledger is already done; taskflow is reconciling planning closeback only.', { taskId, historicalDeliveryRefs: effectiveHistoricalDeliveryRefs }) ], evidence: {
action: 'closeback-reconcile', taskId, actorId, ledgerAlreadyDone: true, historicalDeliveryRefs: effectiveHistoricalDeliveryRefs } }) : await withTaskflowOperatorLane(() => runTasks(backendArgv)); const rollbackSnapshot = buildCloseWriteRollbackSnapshot({ cwd, taskId, previousTaskContent, backendEvidence: backendResult.evidence as Record<string, unknown> | undefined, planningCard: planningCardSnapshot,
closeWindowStagedIndexLockActive: closeWindowLock?.ok === true, preCloseStagedFiles }); const planningCardCloseback = closebackPlan.backendSurface === 'tasks-close' && backendResult.ok ? applyPlanningCardCloseback({ cwd, planningMirrorPath: closebackPlan.writerBoundary.planningMirrorPath, actorId, historicalDeliveryRefs: effectiveHistoricalDeliveryRefs }) : null;
const rollbackSnapshotWithPlanning = planningCardCloseback?.transitionPath && rollbackSnapshot.planningCard ? { ...rollbackSnapshot, planningCard: { ...rollbackSnapshot.planningCard, transitionPath: planningCardCloseback.transitionPath }, stagedArtifacts: [...rollbackSnapshot.stagedArtifacts, planningCardCloseback.transitionPath] } : rollbackSnapshot; let rosterCloseback: Record<string, unknown> | null = null;
const closeMessages: ReturnType<typeof message>[] = []; const planningRosterPaths = closebackPlan.writerBoundary.rosterClosebackCommand && closebackPlan.writerBoundary.rosterIndexPath && closebackPlan.writerBoundary.planningMirrorPath ? resolvePlanningRosterPaths({ cwd, planningMirrorPath: closebackPlan.writerBoundary.planningMirrorPath, rosterIndexPath: closebackPlan.writerBoundary.rosterIndexPath }) : null; if (
closebackPlan.writerBoundary.rosterClosebackCommand && closebackPlan.writerBoundary.rosterSyncPolicy === 'inline' && closebackPlan.writerBoundary.rosterIndexPath && closebackPlan.writerBoundary.planningMirrorPath ) { if (!planningRosterPaths?.repoRoot || !planningRosterPaths?.indexPath || !planningRosterPaths?.fromPath) {
throw new CliError('ATM_TASKFLOW_CLOSE_PLANNING_ROSTER_UNRESOLVED', planningRosterPaths?.reason ?? 'taskflow close could not resolve planning roster paths.', { exitCode: 1, details: { closebackPlan } }); } rosterCloseback = { mode: 'inline', command: closebackPlan.writerBoundary.rosterClosebackCommand, result: await runTasksRosterUpdate([ '--cwd', planningRosterPaths.repoRoot,
'--index', planningRosterPaths.indexPath, '--from', planningRosterPaths.fromPath ]) }; } else if ( closebackPlan.writerBoundary.rosterClosebackCommand && closebackPlan.writerBoundary.rosterSyncPolicy === 'follow-up-command' ) { if (!planningRosterPaths?.repoRoot || !planningRosterPaths.indexPath || !planningRosterPaths.fromPath) { closeMessages.push(message( 'warn',
'ATM_TASKFLOW_CLOSE_ROSTER_SYNC_FOLLOWUP_UNRESOLVED', 'taskflow close --write could not resolve planning roster paths for the follow-up sync; please rerun the roster update command manually.', { command: closebackPlan.writerBoundary.rosterClosebackCommand } )); rosterCloseback = { mode: 'follow-up-command', command: closebackPlan.writerBoundary.rosterClosebackCommand }; } else {
const command = buildRosterSyncCommand({ indexPath: planningRosterPaths.indexPath, fromPath: planningRosterPaths.fromPath }); rosterCloseback = await runRosterSyncFollowUp({ command, cwd: planningRosterPaths.repoRoot, indexPath: planningRosterPaths.indexPath, fromPath: planningRosterPaths.fromPath, messages: closeMessages }); } } const planningIndexAdvisory = buildTaskflowPlanningIndexAdvisory({ taskId,
planningRosterPaths, rosterCloseback, rosterCommand: closebackPlan.writerBoundary.rosterClosebackCommand ?? null }); if (planningIndexAdvisory) { closeMessages.push(message( planningIndexAdvisory.status === 'follow-up-required' ? 'warn' : 'info', planningIndexAdvisory.status === 'follow-up-required' ? 'ATM_TASKFLOW_CLOSE_PLANNING_INDEX_FOLLOWUP_REQUIRED' : 'ATM_TASKFLOW_CLOSE_PLANNING_INDEX_SYNCED',
planningIndexAdvisory.status === 'follow-up-required' ? 'taskflow close succeeded; planning roster/index sync still needs an explicit follow-up command.' : 'taskflow close synced the planning roster/index and recorded the closeback fields.', planningIndexAdvisory )); } promoteTaskRuntimeHandoffs(cwd, taskId, 'completed'); const commitBundleInput = buildTaskflowCommitBundle({ cwd, taskId, actorId, commitMode,
planningMirrorPath: closebackPlan.writerBoundary.planningMirrorPath, rosterIndexPath: closebackPlan.writerBoundary.rosterSyncPolicy === 'inline' ? closebackPlan.writerBoundary.rosterIndexPath : null, extraPlanningStageFiles: planningCardCloseback?.transitionPath ? [planningCardCloseback.transitionPath] : [], backendResult: backendResult as unknown as Record<string, unknown>,
historicalDeliveryRefs: effectiveHistoricalDeliveryRefs, historicalBatchRef, planningAuthorityDeliveryOk: planningAuthorityDeliveryGate.ok }); const { bundle: governedCommitBundle, transaction: closeWriteTransaction } = backendResult.ok ? await executeCloseWriteCommitPhase({ cwd, taskId, actorId, snapshot: rollbackSnapshotWithPlanning, commit: () => finalizeTaskflowCommitBundle({ bundle: commitBundleInput, actorId,
taskId }) }) : { bundle: commitBundleInput, transaction: { schemaId: 'atm.closeWriteTransaction.v1' as const, taskId, phase: 'pending' as const, ok: false, failureStep: 'backend-close', failureCode: 'ATM_TASKFLOW_CLOSE_WRITE_FAILED', failureReason: 'backend close did not complete', rolledBackArtifacts: [], recoveryCommand: diagnosis.nextCommand, backendCloseApplied: false, commitBundleApplied: false } };
const writeOk = backendResult.ok && closeWriteTransaction.ok && !governedCommitBundle.failClosed; const brokerRuntimeCleanup = writeOk ? clearBrokerRuntimeStateForTask({ cwd, taskId }).runtimeCleanup ?? null : null; const residueAdvisory = writeOk ? buildTaskflowCloseResidueAdvisory(enrichedDiagnosis) : null; if (residueAdvisory) { closeMessages.push(message( 'warn', 'ATM_TASKFLOW_CLOSE_RESIDUE_ADVISORY',
'taskflow close succeeded; remaining planning mirror residue is advisory and should be reconciled separately.', residueAdvisory )); } closeMessages.push( message( writeOk ? 'info' : 'error', writeOk ? 'ATM_TASKFLOW_CLOSE_WRITE_ORCHESTRATED' : closeWriteTransaction.phase === 'rolled_back' ? 'ATM_TASKFLOW_CLOSE_WRITE_ROLLED_BACK' : 'ATM_TASKFLOW_CLOSE_WRITE_FAILED', writeOk
? `taskflow close orchestrated ${closebackPlan.backendSurface} for ${taskId}.` : closeWriteTransaction.phase === 'rolled_back' ? `taskflow close --write rolled back ${taskId} after a commit-bundle failure; ledger close state was restored.` : `taskflow close write failed for ${taskId}.`, { closeMode: closebackPlan.closeMode, backendSurface: closebackPlan.backendSurface } ) );
const releasedCloseWindowLock = releaseCloseWindowStagedIndexLock({ cwd, taskId, actorId, outcome: writeOk ? 'committed' : closeWriteTransaction.phase === 'rolled_back' ? 'rolled_back' : 'aborted' }); closeWindowLockReleased = true; deferredGovernanceDirty = restoreDeferredGovernanceDirtyFiles(cwd, deferredGovernanceDirty); deferredGovernanceDirtyRestored = true; return { ...makeResult({ ok: writeOk,
command: 'taskflow close', cwd, mode: 'write', messages: closeMessages, evidence: { closeMode: closebackPlan.closeMode, writeSupport, commitMode, delegationContract, diagnostics, closebackPlan, backendResult, preCloseDeliveryCommit, planningCardCloseback, rosterCloseback, governedCommitBundle, closeWriteTransaction, closeWindowLock, releasedCloseWindowLock, brokerRuntimeCleanup, deferredGovernanceDirty,
residueDiagnosis: enrichedDiagnosis, residueAdvisory, planningIndexAdvisory, closebackPathResolution, ...(autoEvidenceExecution ? { autoEvidenceExecution, autoEvidencePlan: autoEvidenceExecution.plan } : {}), ...(profileData ? { profile: profileData } : {}) } }), schemaId: 'atm.taskflowCloseResult.v1', writeEnabled: true }; } finally { if (closeWindowLock?.ok && !closeWindowLockReleased) {
releaseCloseWindowStagedIndexLock({ cwd, taskId, actorId, outcome: 'aborted' }); } if (!deferredGovernanceDirtyRestored) { restoreDeferredGovernanceDirtyFiles(cwd, deferredGovernanceDirty); } } } return { ...makeResult({ ok: true, command: 'taskflow close', cwd, mode: 'dry-run', messages: [ message( closebackPlan.closeMode === 'ambiguous-manual-review' || writeReadinessHint.status === 'blocked' ? 'warn' : 'info',
closebackPlan.closeMode === 'ambiguous-manual-review' ? 'ATM_TASKFLOW_CLOSE_AMBIGUOUS_RESIDUE' : writeReadinessHint.status === 'blocked' ? 'ATM_TASKFLOW_CLOSE_WRITE_NOT_READY' : 'ATM_TASKFLOW_CLOSE_ORCHESTRATION_READY', closebackPlan.closeMode === 'ambiguous-manual-review' ? 'taskflow close dry-run blocked on ambiguous residue; operator review required.' : writeReadinessHint.status === 'blocked'
? `taskflow close dry-run found known write blockers (${closebackPlan.closeMode}); inspect writeReadinessHint before --write.` : `taskflow close dry-run plan is ready (${closebackPlan.closeMode}).`, { taskId, closeMode: closebackPlan.closeMode } ) ], evidence: { closeMode: closebackPlan.closeMode, commitMode, writeSupport, writeReadinessHint, delegationContract, diagnostics, closebackPlan,
governedCommitBundle: previewCommitBundle, historicalClosePreflight, residueDiagnosis: enrichedDiagnosis, closebackPathResolution, ...(autoEvidencePlan ? { autoEvidencePlan } : {}), ...(profileData ? { profile: profileData } : {}) } }), schemaId: 'atm.taskflowCloseResult.v1', writeEnabled: false }; }
function promoteTaskRuntimeHandoffs(cwd: string, taskId: string, runOutcome: 'completed' | 'aborted' | 'failed'): void { const root = path.join(cwd, '.atm', 'runtime', 'handoff', taskId.replace(/[^A-Za-z0-9._-]/g, '_')); if (!existsSync(root)) return; for (const entry of readdirSync(root, { withFileTypes: true })) { if (!entry.isDirectory()) continue;
const runPath = teamHandoffRuntimeDirectory(cwd, taskId, entry.name); if (existsSync(path.join(runPath, 'manifest.json'))) { promoteTeamHandoffArchive({ cwd, taskId, teamRunId: entry.name, runOutcome }); } } } export async function runTaskflow(argv: string[] = []) { const spec = getCommandSpec('taskflow'); if (!spec) { throw new CliError('ATM_CLI_HELP_NOT_FOUND', 'No help spec found for taskflow.', { exitCode: 2 });
} const parsed = parseArgsForCommand(spec, argv); const cwd = path.resolve(String(parsed.options.cwd ?? process.cwd())); const action = parsed.positional[0]; if (action === 'close') { return runTaskflowClose(parsed, cwd, 'close'); } if (action === 'pre-close') { return runTaskflowClose(parsed, cwd, 'pre-close'); } if (action !== 'open') {
throw new CliError('ATM_CLI_USAGE', `Unknown taskflow action: ${action}. Supported actions: open, close, pre-close.`, { exitCode: 2 }); } const writeRequested = !!parsed.options.write; const profilePath = parsed.options.profile ? String(parsed.options.profile) : null; const taskId = parsed.options.taskId ? String(parsed.options.taskId) : null;
const outputPath = parsed.options.output ? String(parsed.options.output) : null; const rosterIndexPath = parsed.options.rosterIndex ? String(parsed.options.rosterIndex) : null; const template = parsed.options.template ? String(parsed.options.template) : 'aao-l2-split'; const title = parsed.options.title ? String(parsed.options.title) : 'New Task'; let profileData: TaskflowProfileV1 | null = null; if (profilePath) {
profileData = loadProfile(profilePath); } const openOutputRoot = resolveTaskflowOpenOutputRoot({ profilePath, profile: profileData, cwd }); const prerequisiteInput = { profile: profileData, taskIdSupplied: taskId !== null, outputPathSupplied: outputPath !== null, writeRequested }; const delegationContract = buildDelegationContract(profileData); const openerMode = resolveOpenerMode(prerequisiteInput);
const writeSupport = resolveWriteSupport(prerequisiteInput); const diagnostics = buildTaskflowOpenDiagnostics(prerequisiteInput); let hostPolicyDecision: ReturnType<typeof resolveHostOpenerPolicyDecision> | null = null; if (profileData && canResolveHostOpenerPolicy({ cwd: openOutputRoot, profile: profileData, delegationContract, taskId, outputPath, title })) { try {
hostPolicyDecision = resolveHostOpenerPolicyDecision({ cwd: openOutputRoot, profile: profileData, delegationContract, taskId, outputPath, title }); diagnostics.messages.push(...hostPolicyDecision.diagnostics); } catch (error) { if (writeRequested || taskId || outputPath) { throw error; } } } const orchestrationPlan = buildOrchestrationPlan({ profile: profileData, openerMode, delegationContract,
outputRoot: openOutputRoot, taskId: hostPolicyDecision?.taskId ?? taskId, outputPath: hostPolicyDecision?.outputPath ?? outputPath, template, title, rosterIndexPath, hostPolicyDecision, profilePath }); const writeReadinessHint = buildWriteReadinessHint({ openerMode, delegationContract, hostPolicyDecision, taskId, outputPath, profileLoaded: profileData != null }); if (writeRequested && !writeSupport.allowed) {
throw new CliError( 'ATM_TASKFLOW_TEMPLATE_ONLY_FALLBACK', openerMode === 'template-only-fallback' ? 'taskflow open --write is not available in template-only-fallback mode. Load an invocable host opener profile or use tasks new (low-level generator surface) for explicit template generation.'
: 'taskflow open --write prerequisites are incomplete. Supply --task-id/--output or configure host-opener numbering and output-path policy.', { exitCode: 1, details: { openerMode, writeSupport, writeReadinessHint, delegationContract, diagnostics, orchestrationPlan, recommendedCommand: buildTasksNewCommand({ taskId: hostPolicyDecision?.taskId ?? taskId, outputPath: hostPolicyDecision?.outputPath ?? outputPath,
template, title }) } } ); } if (writeRequested && writeSupport.allowed) { if (!profileData) { throw new CliError('ATM_TASKFLOW_TEMPLATE_ONLY_FALLBACK', 'taskflow open --write requires a governed profile.', { exitCode: 1 }); } const resolved = hostPolicyDecision ?? resolveHostOpenerPolicyDecision({ cwd: openOutputRoot, profile: profileData, delegationContract, taskId, outputPath, title }); if (resolved.familyDrift) {
throw new CliError( 'ATM_TASK_ID_FAMILY_DRIFT', resolved.familyDrift.message, { exitCode: 1, details: { familyDrift: resolved.familyDrift, planningCard: resolved.outputPath, targetRepository: profileData.ownerRepo, nextDryRunCommand: orchestrationPlan.nextDryRunCommand, nextImportCommand: orchestrationPlan.nextImportCommand } } ); } const targetAbsolute = resolveOutputAbsolute(openOutputRoot, resolved.outputPath);
const hadExistingTarget = existsSync(targetAbsolute); let generated: Awaited<ReturnType<typeof generateTaskCard>> | null = null; if (!hadExistingTarget) { generated = await generateTaskCard({ cwd: openOutputRoot, templateKey: template, taskId: resolved.taskId, title, outputPath: resolved.outputPath }); mkdirSync(path.dirname(targetAbsolute), { recursive: true });
writeFileSync(targetAbsolute, generated.content, 'utf8'); } let runtimeImport: Record<string, unknown> | null = null; try { const runtimeImportResult = await withTaskflowOperatorLane(() => runTasks([ 'import', '--cwd', cwd, '--from', targetAbsolute, '--write' ])); runtimeImport = { command: buildTasksImportCommand({ fromPath: targetAbsolute }), result: runtimeImportResult }; } catch (error) {
if (!hadExistingTarget && existsSync(targetAbsolute)) { rmSync(targetAbsolute, { force: true }); } throw error; } const effectiveRosterIndex = rosterIndexPath ?? delegationContract.policy.rosterSync.indexPath; let rosterSync: Record<string, unknown> | null = null; const writeMessages = [ message( 'info', 'ATM_TASKFLOW_OPEN_WRITE_ORCHESTRATED',
`taskflow open orchestrated tasks new generation at ${resolved.outputPath}.`, { openerMode, generationSurface: 'tasks-new', runtimeImported: true } ) ]; if (delegationContract.policy.rosterSyncPolicy === 'inline' && effectiveRosterIndex) { const rosterResult = await runTasksRosterUpdate([ '--cwd', cwd, '--index', effectiveRosterIndex, '--from', resolved.outputPath ]); rosterSync = { mode: 'inline',
command: buildRosterSyncCommand({ indexPath: effectiveRosterIndex, fromPath: resolved.outputPath }), result: rosterResult }; } else if (delegationContract.policy.rosterSyncPolicy === 'follow-up-command' && effectiveRosterIndex) { const command = buildRosterSyncCommand({ indexPath: effectiveRosterIndex, fromPath: resolved.outputPath }); rosterSync = await runRosterSyncFollowUp({ command, cwd,
indexPath: effectiveRosterIndex, fromPath: resolved.outputPath, messages: writeMessages }); } return { ...makeResult({ ok: true, command: 'taskflow open', cwd, mode: 'write', messages: writeMessages, evidence: { openerMode, writeSupport, writeReadinessHint, delegationContract, diagnostics, orchestrationPlan, hostPolicyDecision: resolved, generation: { surface: 'tasks-new',
taskId: generated?.taskId ?? resolved.taskId, sourcePath: generated?.sourcePath ?? resolved.outputPath, templateUsed: generated?.templateUsed ?? template, reusedExistingCard: hadExistingTarget, outputRepoRoot: openOutputRoot }, runtimeImport, rosterSync, ...(profileData ? { profile: profileData } : {}) } }), schemaId: 'atm.taskflowOpenResult.v1', writeEnabled: true, writeReadinessHint }; } const result = makeResult({
ok: true, command: 'taskflow open', cwd, mode: 'dry-run', messages: [ message( hostPolicyDecision?.familyDrift ? 'warn' : openerMode === 'delegated-governed' ? 'info' : 'warn', hostPolicyDecision?.familyDrift ? 'ATM_TASK_ID_FAMILY_DRIFT' : openerMode === 'delegated-governed' ? 'ATM_TASKFLOW_OPEN_ORCHESTRATION_READY' : 'ATM_TASKFLOW_OPEN_TEMPLATE_ONLY_FALLBACK', hostPolicyDecision?.familyDrift
? hostPolicyDecision.familyDrift.message : openerMode === 'delegated-governed' ? 'taskflow open dry-run orchestration plan is ready for delegated governed entry.' : 'taskflow open is in template-only-fallback mode. --write will fail closed; see writeReadinessHint for the exact missing prerequisites. tasks new (low-level generator surface) remains the explicit non-governed escape hatch.',
{ cwd, openerMode, writeReadinessHintStatus: writeReadinessHint.status } ) ], evidence: { openerMode, writeSupport, writeReadinessHint, delegationContract, diagnostics, orchestrationPlan, hostPolicyDecision, fallbackBehavior: delegationContract.policy.fallbackBehavior, ...(profileData ? { profile: profileData } : {}) } }); return { ...result, schemaId: 'atm.taskflowOpenResult.v1', writeEnabled: false,
writeReadinessHint }; } export function buildTaskflowCloseResidueAdvisory(diagnosis: { readonly bucket?: unknown; readonly truth?: unknown; readonly residue?: unknown; readonly reason?: unknown; readonly nextCommand?: unknown; }) { const bucket = typeof diagnosis.bucket === 'string' ? diagnosis.bucket : null; const advisoryBuckets = new Set([ 'planning-mirror-only', 'stale-import', 'ledger-ahead-of-planning-mirror'
]); if (!bucket || !advisoryBuckets.has(bucket)) return null; return { schemaId: 'atm.taskflowCloseResidueAdvisory.v1', bucket, truth: typeof diagnosis.truth === 'string' ? diagnosis.truth : null, residue: typeof diagnosis.residue === 'string' ? diagnosis.residue : null, reason: typeof diagnosis.reason === 'string' ? diagnosis.reason : null, recoveryCommand: typeof diagnosis.nextCommand === 'string'
? diagnosis.nextCommand : 'node atm.mjs tasks status --task <id> --residue --json', severity: 'warning', closeSucceeded: true }; } export function buildTaskflowPlanningIndexAdvisory(input: { readonly taskId: string; readonly planningRosterPaths: { readonly repoRoot?: string | null; readonly indexPath?: string | null; readonly fromPath?: string | null; } | null;
readonly rosterCloseback: Record<string, unknown> | null; readonly rosterCommand: string | null; }) { if (!input.rosterCommand && !input.planningRosterPaths?.indexPath) return null; const result = input.rosterCloseback?.result; const evidence = result && typeof result === 'object' && !Array.isArray(result) ? (result as Record<string, unknown>).evidence : null;
const evidenceRecord = evidence && typeof evidence === 'object' && !Array.isArray(evidence) ? evidence as Record<string, unknown> : {}; const diff = evidenceRecord.diff && typeof evidenceRecord.diff === 'object' && !Array.isArray(evidenceRecord.diff) ? evidenceRecord.diff as Record<string, unknown> : null; const ok = result && typeof result === 'object' && !Array.isArray(result)
? (result as Record<string, unknown>).ok === true : false; const unchanged = evidenceRecord.unchanged === true || (diff && typeof diff.before === 'string' && typeof diff.after === 'string' && diff.before === diff.after); return { schemaId: 'atm.taskflowPlanningIndexAdvisory.v1', taskId: input.taskId, status: ok ? (unchanged ? 'already-current' : 'updated') : 'follow-up-required',
repoRoot: input.planningRosterPaths?.repoRoot ?? null, indexPath: input.planningRosterPaths?.indexPath ?? null, planningCardPath: input.planningRosterPaths?.fromPath ?? null, frontmatterFields: [ 'status', 'completed_by_agent', 'closedByActor', 'closedByCommand', 'lastTransitionId', 'delivery_commit' ], requiredCommand: input.rosterCommand
?? (input.planningRosterPaths?.indexPath && input.planningRosterPaths?.fromPath ? buildRosterSyncCommand({ indexPath: input.planningRosterPaths.indexPath, fromPath: input.planningRosterPaths.fromPath }) : 'node atm.mjs tasks roster update --index <tasks/README.md> --from <task-card.md> --json'), diff: diff ? { before: diff.before ?? null, after: diff.after ?? null } : null }; }
