import { defineCommandSpec } from '../shared.ts';
import {
  commonCwdOption,
  commonHelpOption,
  commonJsonOption,
  commonPrettyOption,
} from './_common.ts';

export default defineCommandSpec({
  name: 'broker',
  summary: 'Manage write intents, proposal capsules, compose merge plans, runtime activation, steward apply, and inspect the local write-broker registry.',
  positional: [
    { name: 'action', summary: 'register | decision | status | release | cleanup | proposal | compose | steward | runtime | runner-sync | projection | plan-batch | schedule | batch', required: true },
    { name: 'proposal-action', summary: 'create | list | show | validate', required: false },
    { name: 'steward-action', summary: 'plan | apply', required: false },
    { name: 'runtime-action', summary: 'activate', required: false },
    { name: 'proposal-id', summary: 'Proposal id for show / validate.', required: false }
  ],
  options: [
    commonCwdOption,
    { flag: '--task', value: 'id', summary: 'Task ID to register or release.' },
    { flag: '--actor', value: 'id', summary: 'Actor id for register payload parity checks or runtime activate.' },
    { flag: '--intent-file', value: 'path', summary: 'Path to WriteIntent JSON payload.' },
    { flag: '--ttl-seconds', value: 'number', summary: 'TTL lease duration in seconds for registering write intent.' },
    { flag: '--sealed-source-sha', value: 'sha', summary: 'Sealed source SHA for broker runner-sync enqueue.' },
    { flag: '--surface', value: 'path', summary: 'Release surface path for broker runner-sync enqueue. Repeatable.' },
    { flag: '--steward-work-id', value: 'id', summary: 'Runner-sync steward work id to release after one coalesced build.' },
    { flag: '--receipt-ref', value: 'path', summary: 'Runner-sync build/publication receipt path used when releasing a steward entry.' },
    { flag: '--receipt-digest', value: 'sha256', summary: 'Runner-sync build/publication receipt digest used when releasing a steward entry.' },
    { flag: '--projection-key', value: 'key', summary: 'Generated projection key for broker projection enqueue.' },
    { flag: '--wave', value: 'id', summary: 'Wave id for broker schedule enqueue or plan.' },
    { flag: '--surface-kind', value: 'kind', summary: 'Broker schedule surface kind: commit, build, runner-sync, projection, or checkpoint.' },
    { flag: '--surface-family', value: 'family', summary: 'Broker schedule compatible surface family.' },
    { flag: '--payload-digest', value: 'digest', summary: 'Broker schedule payload digest used in idempotency keys, or source digest for build/projection batch execution.' },
    { flag: '--manifest-digest', value: 'digest', summary: 'Wave manifest digest for broker batch write receipts.' },
    { flag: '--current-head', value: 'sha', summary: 'Current HEAD SHA observed by broker batch execute.' },
    { flag: '--expected-head', value: 'sha', summary: 'Expected HEAD SHA for stale-head rejection in broker batch execute.' },
    { flag: '--expected-task', value: 'id', summary: 'Expected task id for broker schedule plan. Repeatable.' },
    { flag: '--claimed-task', value: 'id', summary: 'Task id with claim evidence for broker batch execute. Repeatable.' },
    { flag: '--validator-task', value: 'id', summary: 'Task id with validator evidence for broker batch execute. Repeatable.' },
    { flag: '--file-slice', value: 'task:path', summary: 'Task-owned file slice for shared delivery commit receipts. Repeatable.' },
    { flag: '--collection-timeout-ms', value: 'ms', summary: 'Broker schedule collection timeout before reseal or serial fallback.' },
    { flag: '--source-item', value: 'path', summary: 'Source item shard for broker projection enqueue. Repeatable.' },
    { flag: '--proposal-file', value: 'path', summary: 'Path to PatchProposal JSON payload. Repeatable for compose / steward.' },
    { flag: '--proposal-id', value: 'id', summary: 'Proposal id for compose / steward or proposal show / validate.' },
    { flag: '--merge-plan-file', value: 'path', summary: 'Path to MergePlan JSON payload for steward plan / apply.' },
    { flag: '--scope-file', value: 'path', summary: 'Scoped file-write target allowed for steward apply or runtime activate. Repeatable.' },
    { flag: '--steward-id', value: 'id', summary: 'Neutral write steward identifier.' },
    { flag: '--evidence-out', value: 'path', summary: 'Output path for steward apply or runtime activation evidence JSON.' },
    { flag: '--run-evidence-dir', value: 'path', summary: 'Directory to write broker batch run records (default: .atm/runtime/broker-collision-evidence/runs, resolved against --cwd).' },
    { flag: '--store', value: 'path', summary: 'Path to broker proposal store JSON.' },
    commonJsonOption,
    commonPrettyOption,
    commonHelpOption
  ],
  examples: [
    'node atm.mjs broker register --task TASK-GOV-0100 --actor worker-1 --intent-file intent.json --json',
    'node atm.mjs broker decision --intent-file intent.json --json',
    'node atm.mjs broker status --json',
    'node atm.mjs broker release --task TASK-GOV-0100 --json',
    'node atm.mjs broker cleanup --json',
    'node atm.mjs broker runner-sync enqueue --task TASK-GOV-0100 --actor worker-1 --sealed-source-sha <sha> --surface release/atm-onefile/atm.mjs --json',
    'node atm.mjs broker runner-sync release --task TASK-GOV-0100 --steward-work-id runner-sync-1234abcd --receipt-ref .atm/history/evidence/TASK-GOV-0100.runner-sync-receipt.json --json',
    'node atm.mjs broker projection enqueue --task TASK-GOV-0100 --actor worker-1 --projection-key atm.generated-projection.governance-backlog --source-item docs/governance/atm-bug-and-optimization-backlog.items/ATM-BUG-YYYY-MM-DD-NNN.json --json',
    'node atm.mjs broker schedule enqueue --task TASK-GOV-0100 --wave wave-123 --surface-kind commit --surface-family cli --payload-digest sha256:abc --json',
    'node atm.mjs broker schedule plan --wave wave-123 --surface-kind commit --surface-family cli --expected-task TASK-GOV-0100 --expected-task TASK-GOV-0101 --json',
    'node atm.mjs broker batch execute --surface commit --wave wave-123 --surface-family cli --manifest-digest sha256:abc --sealed-source-sha <sha> --claimed-task TASK-GOV-0100 --validator-task TASK-GOV-0100 --scope-file src/a.ts --evidence-out .atm/history/evidence/wave-123.shared-write.json --json',
    'node atm.mjs broker batch execute --surface build --wave wave-123 --surface-family cli --manifest-digest sha256:abc --sealed-source-sha <sha> --payload-digest sha256:source --receipt-digest sha256:output --evidence-out .atm/history/evidence/wave-123.build.json --json',
    'node atm.mjs broker proposal create --proposal-file proposal.json --json',
    'node atm.mjs broker proposal list --json',
    'node atm.mjs broker proposal show proposal-123 --json',
    'node atm.mjs broker proposal validate proposal-123 --json',
    'node atm.mjs broker compose --proposal-file proposal-a.json --proposal-file proposal-b.json --json',
    'node atm.mjs broker compose --store .atm/runtime/broker-proposals.json --proposal-id proposal-a --proposal-id proposal-b --json',
    'node atm.mjs broker runtime activate --task TASK-GOV-0100 --actor team-planner --scope-file src/target.ts --json',
    'node atm.mjs broker runtime activate --task TASK-GOV-0100 --actor team-planner --merge-plan-file merge-plan.json --proposal-file proposal.json --scope-file src/target.ts --evidence-out runtime-evidence.json --json',
    'node atm.mjs broker steward plan --merge-plan-file merge-plan.json --proposal-file proposal.json --scope-file src/target.ts --json',
    'node atm.mjs broker steward apply --merge-plan-file merge-plan.json --proposal-file proposal.json --scope-file src/target.ts --evidence-out steward-evidence.json --json',
    'node atm.mjs broker plan-batch --request-file tmp/request-a.json --request-file tmp/request-b.json --apply --run-evidence-dir .atm/runtime/broker-collision-evidence/runs --json'
  ]
});
