// Spec definitions for tasks command
import { defineCommandSpec } from '../shared.ts';
import {
  commonCwdOption,
  commonHelpOption,
  commonJsonOption,
  commonPrettyOption,
} from './_common.ts';

export default defineCommandSpec({
  name: 'tasks',
  summary: 'Create/import/mirror/verify/audit task plans, manage prompt-scoped queues and claim lifecycle, run read-only tasks parallel advisor checks, migrate legacy ledger records, close tasks with deliverable/evidence gates, and amend active task scope via tasks scope add. taskflow open/close is the official operator lane; tasks close/reconcile/import --write/repair-closure/reset/lock cleanup are backend surfaces and protected emergency mutations when used directly. tasks new is the low-level template generator only; taskflow open is the official governed opener orchestration entry. tasks import preserves task-card machine fields with high fidelity: scopePaths, deliverables, validators, target_repo, planning_repo, closure_authority, planningMirrorPaths, planningReadOnlyPaths, outOfScope, nonGoals, nested evidence.required, rollback.strategy, rollback.notes, atomizationImpact, compact dispatchPattern / conditionReview / mailboxAssignee dispatch metadata, and emits importDiagnostics for legacy aliases (allowed_files, blocked_by, upstream_repo).',
  positional: [
    { name: 'action', summary: 'create | import | mirror | verify | scope | audit | queue | parallel | lock | migrate-legacy-ledger | reserve | promote | reset | claim | renew | release | handoff | takeover | block | abandon | close | reconcile | repair-closure | show | status | finalize | roster | new', required: true }
  ],
  options: [
    commonCwdOption,
    { flag: '--from', value: 'path', summary: 'Markdown plan path for tasks import.' },
    { flag: '--dry-run', summary: 'Parse the plan and emit a manifest without writing task files.' },
    { flag: '--write', summary: 'Write canonical task JSON files to .atm/history/tasks/ and persist import evidence.' },
    { flag: '--force', summary: 'Overwrite existing task files even when the source hash differs. Active claims are still preserved unless --force-overwrite-claims is set.' },
    { flag: '--force-overwrite-claims', summary: 'Allow tasks import --write to overwrite tasks with active or handoff claims and emit claim-displaced-by-import transition events.' },
    { flag: '--reset-open', summary: 'Rebuild matching imported tasks as open during tasks import --write.' },
    { flag: '--apply', summary: 'Apply tasks migrate-legacy-ledger changes instead of reporting a dry-run.' },
    { flag: '--all-stale', summary: 'Clean every stale runtime task lock candidate for tasks lock cleanup.' },
    { flag: '--reserved-ok', summary: 'Allow tasks release to return a reserved task with no active claim back to open.' },
    { flag: '--staged', summary: 'Run tasks audit in staged/pre-commit mode.' },
    { flag: '--queue', value: 'id', summary: 'Task queue id for tasks queue abandon.' },
    { flag: '--task', value: 'id', summary: 'Task id for reserve/promote/claim/renew/release/handoff/takeover/close/reconcile/repair-closure/status/finalize diagnose/scope add.' },
    { flag: '--residue', summary: 'For tasks status, return residue-focused diagnosis evidence only (including source-done-governance-incomplete vs ambiguous-manual-review).' },
    { flag: '--allow-stale-runner', summary: 'Allow write actions while the frozen runner is older than framework source (disaster recovery only).' },
    { flag: '--emergency-approval', value: 'leaseId', summary: 'Required for protected direct backend emergency surfaces; obtain via emergency approve after human approval.' },
    { flag: '--with', value: 'id', summary: 'Second task id for tasks parallel pair analysis.' },
    { flag: '--actor', value: 'id', summary: 'Actor id for reservation/claim/close/reconcile lifecycle actions (or set ATM_ACTOR_ID).' },
    { flag: '--claim-intent', value: 'mode', summary: 'Claim mode for tasks claim: write (default) or closeout-only/no-more-mutation.' },
    { flag: '--closeout-only', summary: 'Alias for --claim-intent closeout-only when claiming for non-mutating closeback work.' },
    { flag: '--no-more-mutation', summary: 'Alias for --claim-intent closeout-only; keep for closeback-only intent surface.' },
    { flag: '--title', value: 'text', summary: 'Optional title for tasks reserve when creating a manual task entry.' },
    { flag: '--provider', value: 'id', summary: 'External provider id for tasks mirror.' },
    { flag: '--origin-task', value: 'id', summary: 'External task id for tasks mirror.' },
    { flag: '--origin-url', value: 'url', summary: 'External task URL for tasks mirror.' },
    { flag: '--sync-status', value: 'state', summary: 'Mirror sync status for tasks mirror.' },
    { flag: '--files', value: 'csv', summary: 'Comma-separated scope files for claim/takeover lock acquisition.' },
    { flag: '--add', value: 'csv', summary: 'Comma-separated paths to add to the active task direction lock allowedFiles. Used with tasks scope add.' },
    { flag: '--ttl-seconds', value: 'number', summary: 'Lease ttl in seconds for claim/renew/takeover.' },
    { flag: '--to', value: 'id', summary: 'Target actor id for handoff.' },
    { flag: '--status', value: 'state', summary: 'Target status for tasks close: done|review|blocked|abandoned. done requires real non-.atm deliverables plus evidence.' },
    { flag: '--reason', value: 'text', summary: 'Reason for release, handoff, takeover, or close.' },
    { flag: '--historical-delivery', value: 'commit', summary: 'Allow tasks close done or tasks reconcile to verify an earlier delivery commit.' },
    { flag: '--waiver-out-of-scope-delivery', summary: 'Allow historical delivery when the commit also contains unrelated source files; requires --reason.' },
    { flag: '--scope', value: 'taskId', summary: 'For tasks repair-closure, limit dirty-tree blocking to files overlapping the scoped task claim/direction lock/deliverables; unrelated dirty files become warnings.' },
    { flag: '--amend', summary: 'For tasks repair-closure, explicitly request HEAD rewrite after staging the repaired packet. ATM fails safely when no amend-capable governed wrapper is available.' },
    { flag: '--no-amend', summary: 'Compatibility alias for the default stage-only tasks repair-closure flow.' },
    { flag: '--template', value: 'name', summary: 'Template key for tasks new.' },
    { flag: '--task-id', value: 'id', summary: 'Task id for tasks new.' },
    { flag: '--output', value: 'path', summary: 'Output markdown path for tasks new.' },
    { flag: '--atom-id', value: 'id', summary: 'Atom id placeholder for tasks new.' },
    { flag: '--scope-path', value: 'path', summary: 'Scope path placeholder for tasks new.' },
    { flag: '--test-path', value: 'path', summary: 'Test path placeholder for tasks new.' },
    { flag: '--depends-on', value: 'id', summary: 'Depends on placeholder for tasks new.' },
    { flag: '--capability', value: 'text', summary: 'Capability description placeholder for tasks new.' },
    { flag: '--goal', value: 'text', summary: 'Goal description placeholder for tasks new.' },
    { flag: '--index', value: 'path', summary: 'Roster README path for tasks roster update.' },
    { flag: '--from', value: 'path', summary: 'Task markdown path for tasks roster update.' },
    commonJsonOption,
    commonPrettyOption,
    commonHelpOption
  ],
  examples: [
    'node atm.mjs tasks import --from docs/plan.md --dry-run --json',
    'node atm.mjs tasks import --from docs/plan.md --write --json',
    'node atm.mjs tasks create --task ATM-GOV-0100 --actor codex-main --title "Governance task" --json',
    'node atm.mjs tasks mirror --provider github --origin-task 123 --origin-url https://github.com/org/repo/issues/123 --actor codex-main --json',
    'node atm.mjs tasks verify --json',
    'node atm.mjs tasks audit --json',
    'node atm.mjs tasks audit --staged --json',
    'node atm.mjs tasks scope add --task ATM-GOV-0101 --actor codex-main --add packages/cli/src/commands/new-feature.ts --json',
    'node atm.mjs tasks scope add --task ATM-GOV-0101 --actor codex-main --add packages/cli/src/commands/foo.ts,packages/cli/src/commands/bar.ts --json',
    'node atm.mjs tasks queue status --json',
    'node atm.mjs tasks queue abandon --queue queue-abc123 --actor codex-main --json',
    'node atm.mjs tasks parallel --task TASK-AAO-0130 --with TASK-AAO-0131 --json',
    'node atm.mjs tasks parallel --task TASK-AAO-0130 --queue --json',
    'node atm.mjs tasks parallel --queue --report --json',
    'node atm.mjs tasks lock cleanup --all-stale --actor codex-main --json',
    'node atm.mjs tasks migrate-legacy-ledger --actor codex-main --dry-run --json',
    'node atm.mjs tasks migrate-legacy-ledger --actor codex-main --apply --json',
    'node atm.mjs tasks reserve --task ATM-GOV-0101 --actor codex-main --title "Actor model" --json',
    'node atm.mjs tasks promote --task ATM-GOV-0101 --actor codex-main --json',
    'node atm.mjs tasks reset --task ATM-GOV-0101 --actor codex-main --to open --reason "rollback cleanup" --json',
    'node atm.mjs tasks claim --task ATM-GOV-0101 --actor codex-main --files packages/core/src/index.ts --json',
    'node atm.mjs tasks claim --task ATM-GOV-0101 --actor codex-main --files packages/core/src/index.ts --claim-intent closeout-only --json',
    'node atm.mjs tasks claim --task ATM-GOV-0101 --actor codex-main --files packages/core/src/index.ts --no-more-mutation --json',
    'node atm.mjs tasks renew --task ATM-GOV-0101 --actor codex-main --ttl-seconds 3600 --json',
    'node atm.mjs tasks release --task ATM-GOV-0101 --actor codex-main --reason "handoff complete" --json',
    'node atm.mjs tasks release --task ATM-GOV-0101 --actor codex-main --reserved-ok --reason "rollback cleanup" --json',
    'node atm.mjs tasks close --task ATM-GOV-0104 --actor codex-main --status done --json',
    'node atm.mjs tasks close --task ATM-GOV-0104 --actor codex-main --status done --historical-delivery abc123 --emergency-approval EMG-... --json',
    'node atm.mjs tasks repair-closure --task TASK-AAO-0102 --json',
    'node atm.mjs tasks block --task ATM-GOV-0104 --actor codex-main --reason "waiting on target evidence" --json',
    'node atm.mjs tasks reconcile --task TASK-AAO-0055 --actor codex-main --delivery-commit abc1234 --emergency-approval EMG-... --json',
    'node atm.mjs tasks status --task TASK-AAO-0137 --json',
    'node atm.mjs tasks status --task TASK-AAO-0137 --residue --json',
    'node atm.mjs tasks finalize diagnose --task TASK-AAO-0137 --json',
    'node atm.mjs tasks roster update --index docs/tasks/README.md --from docs/tasks/TASK-ADOPTER-0001.task.md --dry-run --json',
    'node atm.mjs tasks roster update --index docs/tasks/README.md --from docs/tasks/TASK-ADOPTER-0001.task.md --json'
  ]
});
