import { computeSha256ForContent } from '../../hash-lock/hash-lock.ts';
import { createAtomicMapSemanticFingerprint } from '../../registry/semantic-fingerprint.ts';
import { createGeneratorError } from './errors.ts';
import {
  assertSpecVersionSupportsMapSurface,
  inferSpecVersion,
  normalizeAtomId,
  normalizeMapId,
  normalizeRequiredText,
  normalizeSemver,
  normalizeSpecVersion
} from './normalize-fields.ts';
import {
  normalizeOptionalEdgeKind,
  normalizeOptionalMemberRole,
  normalizeReplacement
} from './normalize-lineage.ts';
import type { HashPayloadInput, MapEdge, MapMember, MapReplacement, NormalizedRequest } from './types.ts';

export function createMinimalAtomicMapSpec(request: NormalizedRequest & { mapId: string }) {
  const members = normalizeMembers(request.members);
  const memberIds = new Set(members.map((member) => member.atomId));
  const edges = normalizeEdges(request.edges, memberIds);
  const entrypoints = normalizeEntrypoints(request.entrypoints, memberIds);
  const qualityTargets = normalizeQualityTargets(request.qualityTargets);
  const mapVersion = normalizeSemver(request.mapVersion ?? '0.1.0', 'mapVersion');
  const replacement = normalizeReplacement(request.replacement);
  const specVersion = normalizeSpecVersion(request.specVersion ?? inferSpecVersion({ members, edges, replacement }));
  assertSpecVersionSupportsMapSurface(specVersion, { members, edges, replacement });
  const mapHash = computeAtomicMapHash({ members, edges, entrypoints, replacement });
  const pendingSfCalculation = request.pendingSfCalculation === true;
  const semanticFingerprint = pendingSfCalculation
    ? null
    : createAtomicMapSemanticFingerprint({ entrypoints, qualityTargets });

  return {
    schemaId: 'atm.atomicMap',
    specVersion,
    migration: {
      strategy: 'none',
      fromVersion: null,
      notes: 'Generated by AtomicMapGenerator provisioning facade.'
    },
    mapId: normalizeMapId(request.mapId),
    mapVersion,
    members,
    edges,
    entrypoints,
    qualityTargets,
    mapHash,
    ...(replacement ? { replacement } : {}),
    semanticFingerprint,
    ...(pendingSfCalculation ? { pendingSfCalculation: true } : {})
  };
}

export function normalizeRequest(request: unknown): NormalizedRequest {
  if (!request || typeof request !== 'object' || Array.isArray(request)) {
    throw createGeneratorError('ATM_MAP_GENERATOR_REQUEST_INVALID', 'Atomic map generator request must be an object.');
  }

  const req = request as Record<string, unknown>;
  return {
    members: normalizeMembers(req.members),
    edges: (req.edges as MapEdge[] | undefined) ?? [],
    entrypoints: req.entrypoints as string[],
    qualityTargets: req.qualityTargets as Record<string, string | number | boolean>,
    mapVersion: (req.mapVersion as string | undefined) ?? '0.1.0',
    specVersion: req.specVersion as string | undefined,
    replacement: normalizeReplacement(req.replacement),
    pendingSfCalculation: req.pendingSfCalculation === true
  };
}

export function computeAtomicMapHash(input: HashPayloadInput): string {
  return computeSha256ForContent(JSON.stringify(createAtomicMapHashPayload(input)));
}

function normalizeMembers(members: unknown): MapMember[] {
  if (!Array.isArray(members) || members.length === 0) {
    throw createGeneratorError('ATM_MAP_GENERATOR_REQUEST_INVALID', 'Atomic map generator requires at least one member.', { fieldName: 'members' });
  }

  return members.map((member: unknown) => {
    const m = member as Record<string, unknown> | null | undefined;
    return {
      atomId: normalizeAtomId(m?.atomId, 'members[].atomId'),
      version: normalizeSemver(m?.version, 'members[].version'),
      ...normalizeOptionalMemberRole(m?.role),
      ...(m?.versionLineage ? { versionLineage: m.versionLineage as string } : {})
    };
  });
}

function normalizeEdges(edges: unknown, memberIds: Set<string>): MapEdge[] {
  if (edges == null) {
    return [];
  }
  if (!Array.isArray(edges)) {
    throw createGeneratorError('ATM_MAP_GENERATOR_REQUEST_INVALID', 'Atomic map generator edges must be an array.', { fieldName: 'edges' });
  }

  return edges.map((edge: unknown) => {
    const e = edge as Record<string, unknown> | null | undefined;
    const from = normalizeAtomId(e?.from, 'edges[].from');
    const to = normalizeAtomId(e?.to, 'edges[].to');
    const binding = normalizeRequiredText(e?.binding, 'edges[].binding');
    if (!memberIds.has(from) || !memberIds.has(to)) {
      throw createGeneratorError('ATM_MAP_GENERATOR_EDGE_UNKNOWN_MEMBER', 'Edge endpoints must reference declared map members.', {
        from,
        to
      });
    }
    return {
      from,
      to,
      binding,
      ...normalizeOptionalEdgeKind(e?.edgeKind)
    };
  });
}

function normalizeEntrypoints(entrypoints: unknown, memberIds: Set<string>): string[] {
  if (!Array.isArray(entrypoints) || entrypoints.length === 0) {
    throw createGeneratorError('ATM_MAP_GENERATOR_REQUEST_INVALID', 'Atomic map generator requires at least one entrypoint.', { fieldName: 'entrypoints' });
  }

  const normalized = entrypoints.map((entrypoint: unknown) => normalizeAtomId(entrypoint, 'entrypoints[]'));
  for (const entrypoint of normalized) {
    if (!memberIds.has(entrypoint)) {
      throw createGeneratorError('ATM_MAP_GENERATOR_ENTRYPOINT_UNKNOWN_MEMBER', 'Entrypoints must reference declared map members.', {
        entrypoint
      });
    }
  }
  return [...new Set(normalized)];
}

function normalizeQualityTargets(qualityTargets: unknown): Record<string, string | number | boolean> {
  if (!qualityTargets || typeof qualityTargets !== 'object' || Array.isArray(qualityTargets)) {
    throw createGeneratorError('ATM_MAP_GENERATOR_REQUEST_INVALID', 'Atomic map generator requires qualityTargets object.', { fieldName: 'qualityTargets' });
  }

  const entries = Object.entries(qualityTargets as Record<string, string | number | boolean>).map(([key, value]) => {
    const normalizedKey = normalizeRequiredText(key, 'qualityTargets key');
    if (!['string', 'number', 'boolean'].includes(typeof value)) {
      throw createGeneratorError('ATM_MAP_GENERATOR_QUALITY_TARGET_INVALID', 'qualityTargets values must be string, number, or boolean.', {
        key: normalizedKey,
        actualType: typeof value
      });
    }
    return [normalizedKey, typeof value === 'string' ? value.trim() : value];
  });

  if (entries.length === 0) {
    throw createGeneratorError('ATM_MAP_GENERATOR_REQUEST_INVALID', 'Atomic map generator requires at least one quality target.', { fieldName: 'qualityTargets' });
  }

  return Object.fromEntries((entries as Array<[string, string | number | boolean]>).sort(([left], [right]) => left.localeCompare(right)));
}

function createAtomicMapHashPayload(input: HashPayloadInput) {
  return {
    members: [...input.members]
      .map((member) => ({
        atomId: String(member.atomId).trim(),
        version: String(member.version).trim(),
        ...(member.role ? { role: String(member.role).trim() } : {})
      }))
      .sort((left, right) => left.atomId.localeCompare(right.atomId) || left.version.localeCompare(right.version) || String((left as { role?: string }).role ?? '').localeCompare(String((right as { role?: string }).role ?? ''))),
    edges: [...input.edges]
      .map((edge) => ({
        from: String(edge.from).trim(),
        to: String(edge.to).trim(),
        binding: String(edge.binding).trim(),
        ...(edge.edgeKind ? { edgeKind: String(edge.edgeKind).trim() } : {})
      }))
      .sort((left, right) => left.from.localeCompare(right.from) || left.to.localeCompare(right.to) || left.binding.localeCompare(right.binding) || String((left as { edgeKind?: string }).edgeKind ?? '').localeCompare(String((right as { edgeKind?: string }).edgeKind ?? ''))),
    entrypoints: [...input.entrypoints]
      .map((entrypoint) => String(entrypoint).trim())
      .filter(Boolean)
      .sort((left, right) => left.localeCompare(right)),
    ...(input.replacement ? { replacement: normalizeAtomicMapReplacementForHash(input.replacement) } : {})
  };
}

function normalizeAtomicMapReplacementForHash(replacement: MapReplacement) {
  return {
    legacyUris: [...replacement.legacyUris]
      .map((legacyUri) => String(legacyUri).trim())
      .filter(Boolean)
      .sort((left, right) => left.localeCompare(right))
  };
}
