import {
  isCommitAttributionSideEffectPath,
  isIgnorableTaskScopedDirtySideEffect,
  isRuntimeCommitSideEffect,
  resolveGitExecutable,
  shouldStageGovernedGitHeadEvidenceBeforeCommit,
} from './git-process-port.ts';
import {
  findCloseCommitWindowCoveringPaths,
  inspectAutoGeneratedResidue,
  readActiveCloseCommitWindows,
} from "../../framework-development.ts";
import { isReleasedGeneratedBundleSafeToClean, planReleasedResidueTransaction, readGeneratedResidueTaskDisposition, reconcileReleasedResidueReport } from '../../tasks/generated-residue-policy.ts';
import {
  gitHeadEvidencePath,
  gitHeadEvidencePaths,
} from "../../git-head-evidence.ts";
import { readResolutionAuthorizedForeignTaskIds } from "../../broker-conflict-resolution.ts";
import { mergeSealedCommitBundles, sealCommitBundleFromCandidateIndex, sealCommitBundleFromLiveIndex, withWorktreeCandidateIndex } from "./sealed-commit-attribution.ts";
import {
  ATM_INDEX_FOREIGN_ACTIVE_STAGED,
  authorizeGitIndexOverrideLease,
  buildForeignActiveStagedDiagnostic,
  consumeGitIndexOverrideLease,
  inspectGitIndexOwnership,
  parkGitIndexLease,
  restoreGitIndexLease,
} from "../../git-index-ownership.ts";
import {
  extractGovernanceTaskIdFromPath,
  inspectTouchedPhysicalLineBudget,
  isProtectedStagedGovernanceOwnershipPath,
  normalizeRelativePath,
  normalizeTaskClaimIntent,
  pathMatchesTaskScope,
  uniqueSorted,
} from "../commit-scope-policy.ts";
import {
  buildTaskScopedCommitFileSet,
  isFileAllowedInTaskBundle as isTaskBundleAllowedByPolicy,
} from "../commit-bundle-filter.ts";
import {
  isActionableManualResidue,
  isDeferrableForeignGovernanceResidue,
} from "../governance-residue-policy.ts";
import {
  ATM_PROTECTED_GOVERNANCE_STATE_DESTRUCTIVE_WRITE,
  inspectProtectedGovernanceStateDestructiveChanges,
} from "../protected-governance-state.ts";
import { buildCopyableGitCommitCommand, buildProtectedForeignStagedOwnershipFiles, buildUnexpectedStagedTasksForGitCommit, deferStagedFilePaths, isActiveForeignGovernanceResidueOwner, isAllowedGovernanceArtifactPath, isFileAllowedInTaskBundle, listTaskOwnedProtectedOverrideAuditFiles, readStagedDiffNames, readStagedFiles, readUnstagedFiles } from './git-index-transaction.ts';
import { isExplicitTerminalHistoryCleanupArtifact } from './terminal-history-cleanup.ts';
import { parseTaskClaim } from './identity-check-command.ts';
import { createCommitAuthorityPolicy } from './commit-authority-scopes.ts';
import { cleanupAutoGeneratedResidue, isIgnorableCommitStagingSideEffect, listTaskScopedWorktreeDirtyFiles, resolveTaskDeclaredScope } from './task-scope-staging.ts';
import { listTaskDeclaredIgnoredWorktreeFiles } from './task-ignored-deliverable-discovery.ts';
import { isUncommittableTaskEvidenceArtifact } from './task-evidence-admission.ts';
import { resolvePublicationSliceAdmission } from './publication-slice-admission.ts';
type LegacyValue = ReturnType<typeof JSON.parse>;
export function resolveTaskScopedCommitBundle(input: LegacyValue) {
  const declaredScope = resolveTaskDeclaredScope(
    input.cwd,
    input.taskId,
    input.taskDocument,
  );
  const currentTaskPlanningSourcePath =
    typeof input.taskDocument?.source?.planPath === 'string'
      ? input.taskDocument.source.planPath
      : null;
  const commitAuthority = createCommitAuthorityPolicy(input);
  const isAllowedCommitArtifact = (filePath: string) => isAllowedGovernanceArtifactPath(input.cwd, filePath, input.taskId) || isExplicitTerminalHistoryCleanupArtifact(input.cwd, filePath, input.taskId, declaredScope, (candidate) => isAllowedGovernanceArtifactPath(input.cwd, candidate, input.taskId), currentTaskPlanningSourcePath);
  const gitExecutable = resolveGitExecutable();
  const copyableCommitCommand = buildCopyableGitCommitCommand({
    cwd: input.cwd,
    message: input.message,
    trailers: input.trailers,
  });
  let stagedFiles = readStagedFiles(input.cwd);
  // `--defer-foreign-staged` promises an isolated commit transaction.  The
  // complete pre-existing index is therefore the preservation boundary: a
  // path that happens to look like current-task evidence must not leak into
  // the new commit merely because ownership classification is incomplete.
  const preexistingStagedFiles = [...stagedFiles];
  let gitIndexOwnership = inspectGitIndexOwnership({
    cwd: input.cwd,
    taskId: input.taskId,
    stagedFiles,
  });
  // An explicit stage-override lease authorizes the isolated commit
  // transaction itself. Deferral is a separate fallback policy; tying lease
  // authorization to --defer-foreign-staged silently bypasses park/restore.
  const indexLeaseAuthorization =
    Boolean(input.stageOverrideLease) &&
    gitIndexOwnership.foreignActiveStaged.length > 0
      ? authorizeGitIndexOverrideLease({
          cwd: input.cwd,
          leaseId: input.stageOverrideLease ?? null,
          actorId: input.actorId ?? "",
          taskId: input.taskId,
          report: gitIndexOwnership,
        })
      : null;
  const hasAuthorizedIndexLease = indexLeaseAuthorization?.ok === true;
  let unexpectedStagedTasks = buildUnexpectedStagedTasksForGitCommit(
    input.cwd,
    input.taskId,
    declaredScope,
    stagedFiles,
  );
  let protectedForeignStagedOwnershipFiles =
    buildProtectedForeignStagedOwnershipFiles(unexpectedStagedTasks);
  const resolutionAuthorizedForeignTaskIds =
    readResolutionAuthorizedForeignTaskIds(
      input.cwd,
      input.brokerConflictResolutionPath ?? null,
      input.taskId,
    );
  const protectedForeignDeferAuthorized =
    unexpectedStagedTasks.length > 0 &&
    unexpectedStagedTasks.every((entry: LegacyValue) =>
      resolutionAuthorizedForeignTaskIds.has(entry.taskId.toUpperCase()),
    );
  const releasedResidueTransaction = planReleasedResidueTransaction({
    cwd: input.cwd,
    candidateTaskId: input.taskId,
    ownerTaskIds: unexpectedStagedTasks.map((entry: LegacyValue) => entry.taskId),
  });
  const lifecycleAuthorizedForeignDefer =
    input.deferForeignStaged &&
    releasedResidueTransaction.disposition === 'park-and-restore';
  let deferredForeignStagedSnapshot = null;
  let deferredForeignStagedFiles: readonly string[] = [];
  if (
    input.deferForeignStaged &&
    preexistingStagedFiles.length > 0 &&
    input.apply &&
    !hasAuthorizedIndexLease &&
    (protectedForeignDeferAuthorized || lifecycleAuthorizedForeignDefer) &&
    (protectedForeignStagedOwnershipFiles.length === 0 ||
      (protectedForeignDeferAuthorized || lifecycleAuthorizedForeignDefer))
  ) {
    deferredForeignStagedFiles = preexistingStagedFiles;
    deferredForeignStagedSnapshot = deferStagedFilePaths(
      input.cwd,
      input.taskId,
      preexistingStagedFiles,
    );
    stagedFiles = readStagedFiles(input.cwd);
    gitIndexOwnership = inspectGitIndexOwnership({
      cwd: input.cwd,
      taskId: input.taskId,
      stagedFiles,
    });
  }
  // `.atm/` is ignored by the ordinary untracked-file scan.  Bring verified
  // task-owned protected audits into the source set before either pass of the
  // bundle resolver, including the second resolve used by commit execution.
  const taskOwnedProtectedOverrideAudits = new Set(
    listTaskOwnedProtectedOverrideAuditFiles(input.cwd, input.taskId),
  );
  const dirtyFiles = uniqueSorted([
    ...listTaskScopedWorktreeDirtyFiles(input.cwd),
    ...listTaskDeclaredIgnoredWorktreeFiles(input.cwd, declaredScope),
    ...taskOwnedProtectedOverrideAudits,
  ]);
  const activeDeferredSnapshot = normalizeRelativePath(
    deferredForeignStagedSnapshot ?? "",
  );
  const residueCandidateFiles = dirtyFiles.filter(
    (filePath: LegacyValue) =>
      normalizeRelativePath(filePath) !== activeDeferredSnapshot &&
      !isIgnorableTaskScopedDirtySideEffect(filePath),
  );
  const residueReport = inspectAutoGeneratedResidue(
    input.taskId,
    residueCandidateFiles,
    input.cwd,
  );
  const releasedBundleResidue = residueCandidateFiles
    .filter((filePath) => /^\.atm\/history\/evidence\/[^/]+\.bundle-manifest\.json$/i.test(filePath))
    .map((filePath) => {
      const ownerTaskId = filePath.match(/^\.atm\/history\/evidence\/([^/]+)\.bundle-manifest\.json$/i)?.[1]?.toUpperCase() ?? null;
      const disposition = ownerTaskId ? readGeneratedResidueTaskDisposition(input.cwd, ownerTaskId) : null;
      // A task-scoped commit may clean only its own disposable byproducts.
      // Foreign released residue can still be evidence for another lifecycle
      // and must survive both successful and failed defer transactions.
      return ownerTaskId === input.taskId.toUpperCase() && isReleasedGeneratedBundleSafeToClean(disposition)
        ? { path: filePath, verdict: 'auto-clean-safe' as const, reason: 'Released-task bundle-manifest is disposable generated residue; lifecycle audit records remain preserved.', ownerTaskId, cleanupAction: 'remove' as const }
        : null;
    })
    .filter((entry): entry is NonNullable<typeof entry> => Boolean(entry));
  const releasedBundleReconciledReport = releasedBundleResidue.length === 0 ? residueReport : {
    ...residueReport,
    autoCleanSafe: [...residueReport.autoCleanSafe, ...releasedBundleResidue],
    blockAndExplain: residueReport.blockAndExplain.filter((entry) => !releasedBundleResidue.some((released) => released.path === entry.path)),
  };
  // A completed, unclaimed foreign task may leave auditable generated residue
  // in the shared worktree. Preserve those bytes, but do not let them turn a
  // path-bounded commit for another task into a global write refusal.
  const reconciledResidueReport = reconcileReleasedResidueReport(
    input.cwd,
    input.taskId,
    releasedBundleReconciledReport,
  );
  const autoCleanedResidue = input.apply
    ? cleanupAutoGeneratedResidue(input.cwd, reconciledResidueReport.autoCleanSafe)
    : [];
  const deferredForeignStagedSet = new Set(
    deferredForeignStagedFiles.map(normalizeRelativePath),
  );
  const stagedSet = new Set(stagedFiles);
  const preservedForeignUnstagedResidue = new Set(
    reconciledResidueReport.blockAndExplain
      .filter((entry: LegacyValue) =>
        entry.ownerTaskId?.trim().toUpperCase() !== input.taskId.toUpperCase()
        && isDeferrableForeignGovernanceResidue(input.taskId, entry)
        && !stagedSet.has(normalizeRelativePath(entry.path)),
      )
      .map((entry: LegacyValue) => normalizeRelativePath(entry.path)),
  );
  const blockedResidue = reconciledResidueReport.blockAndExplain.filter(
    (entry: LegacyValue) =>
      !deferredForeignStagedSet.has(normalizeRelativePath(entry.path)) &&
      !(
        input.deferForeignStaged &&
        isDeferrableForeignGovernanceResidue(input.taskId, entry)
      ) &&
      !preservedForeignUnstagedResidue.has(normalizeRelativePath(entry.path)) &&
      !isActiveForeignGovernanceResidueOwner(input.cwd, input.taskId, entry),
  );
  const manualReviewResidue = reconciledResidueReport.manualReview.filter(
    (entry: LegacyValue) =>
      isActionableManualResidue(entry.path) &&
      !(
        input.deferForeignStaged &&
        isDeferrableForeignGovernanceResidue(input.taskId, entry)
      ) &&
      !preservedForeignUnstagedResidue.has(normalizeRelativePath(entry.path)) &&
      !isActiveForeignGovernanceResidueOwner(input.cwd, input.taskId, entry),
  );
  const effectiveDirtyFiles =
    autoCleanedResidue.length > 0
      ? listTaskScopedWorktreeDirtyFiles(input.cwd)
      : dirtyFiles;
  const trackedUnstagedSet = new Set(readUnstagedFiles(input.cwd));
  const unstagedDirtyFiles = uniqueSorted([
    ...effectiveDirtyFiles.filter((filePath: LegacyValue) => !stagedSet.has(filePath)),
    ...effectiveDirtyFiles.filter((filePath: LegacyValue) => trackedUnstagedSet.has(filePath)),
  ]);
  // A protected-override audit is neither generic evidence nor disposable
  // residue: its embedded taskId is the ownership proof.  Preserve a
  // current-task audit through the generic evidence admissibility filter so a
  // foreign staged audit can be deferred without suppressing its companion.
  // Protected-override audits live below `.atm/`, which is normally ignored
  // by Git.  A task-owned audit can therefore be absent from the ordinary
  // dirty-file discovery even though its embedded task identity authorizes
  // it.  Add only that verified set; foreign or malformed audit files remain
  // outside this task's candidate.
  const inScopeUnstagedDirty = uniqueSorted([
    ...unstagedDirtyFiles,
    ...taskOwnedProtectedOverrideAudits,
  ]).filter(
    (filePath: LegacyValue) =>
      (taskOwnedProtectedOverrideAudits.has(normalizeRelativePath(filePath)) ||
        !isRuntimeCommitSideEffect(filePath)) &&
      (taskOwnedProtectedOverrideAudits.has(normalizeRelativePath(filePath)) ||
        !isUncommittableTaskEvidenceArtifact(input.cwd, filePath, input.taskId, input.taskDocument, isAllowedCommitArtifact(filePath))) &&
      (isCommitAttributionSideEffectPath(filePath) ||
        isAllowedCommitArtifact(filePath) ||
        (declaredScope.some((scope: LegacyValue) => pathMatchesTaskScope(filePath, scope)) &&
          commitAuthority.evaluate(filePath).ok)),
  );
  const { deliverySliceRejection, deliverySliceStageFiles } = resolvePublicationSliceAdmission({
    cwd: input.cwd,
    taskId: input.taskId,
    manifestPath: input.deliverySliceManifestPath,
    receiptPath: input.deliverySliceReceiptPath,
    effectiveDirtyFiles,
    declaredScope,
  });
  const autoStagePool = deliverySliceStageFiles
    ? uniqueSorted(inScopeUnstagedDirty.filter((filePath: LegacyValue) => deliverySliceStageFiles.includes(filePath)))
    : inScopeUnstagedDirty;
  const skippedExternalDirtyFiles = unstagedDirtyFiles.filter(
    (filePath: LegacyValue) =>
      !isCommitAttributionSideEffectPath(filePath) &&
      !isAllowedCommitArtifact(filePath) &&
      (!declaredScope.some((scope: LegacyValue) => pathMatchesTaskScope(filePath, scope)) ||
        !commitAuthority.evaluate(filePath).ok) &&
      !isIgnorableTaskScopedDirtySideEffect(filePath) &&
      !isIgnorableCommitStagingSideEffect(input.cwd, filePath, input.taskId),
  );
  const inScopeStagedFiles = stagedFiles.filter((filePath: LegacyValue) =>
    !isUncommittableTaskEvidenceArtifact(input.cwd, filePath, input.taskId, input.taskDocument, isAllowedCommitArtifact(filePath)) &&
    isFileAllowedInTaskBundle(input.cwd, filePath, input.taskId, declaredScope) &&
    (isCommitAttributionSideEffectPath(filePath) ||
      isAllowedCommitArtifact(filePath) ||
      commitAuthority.evaluate(filePath).ok),
  );
  const outOfScopeStagedFiles = stagedFiles.filter(
    (filePath: LegacyValue) =>
      !isFileAllowedInTaskBundle(
        input.cwd,
        filePath,
        input.taskId,
        declaredScope,
      ) || (
        !isCommitAttributionSideEffectPath(filePath) &&
        !isAllowedCommitArtifact(filePath) &&
        !commitAuthority.evaluate(filePath).ok
      ),
  );
  const inScopeStagedDeletions = readStagedDiffNames(input.cwd, "D").filter(
    (filePath: LegacyValue) =>
      isFileAllowedInTaskBundle(
        input.cwd,
        filePath,
        input.taskId,
        declaredScope,
      ) && (
        isCommitAttributionSideEffectPath(filePath) ||
        isAllowedCommitArtifact(filePath) ||
        commitAuthority.evaluate(filePath).ok
      ),
  );
  const outOfScopeStagedDeletions = readStagedDiffNames(input.cwd, "D").filter(
    (filePath: LegacyValue) =>
      !isFileAllowedInTaskBundle(
        input.cwd,
        filePath,
        input.taskId,
        declaredScope,
      ) || (
        !isCommitAttributionSideEffectPath(filePath) &&
        !isAllowedCommitArtifact(filePath) &&
        !commitAuthority.evaluate(filePath).ok
      ),
  );
  const taskClaim = parseTaskClaim(input.taskDocument.claim);
  const claimIntent =
    input.taskDocument.claim &&
    typeof input.taskDocument.claim === "object" &&
    !Array.isArray(input.taskDocument.claim)
      ? normalizeTaskClaimIntent(input.taskDocument.claim.intent)
      : "write";
  const source =
    input.taskDocument.source &&
    typeof input.taskDocument.source === "object" &&
    !Array.isArray(input.taskDocument.source)
      ? input.taskDocument.source
      : {};
  const planningPath =
    typeof source.planPath === "string"
      ? normalizeRelativePath(source.planPath)
      : "";
  const governanceBundleWarnings = [];
  // A publication delivery slice is closed over the published receipt's
  // inventory plus the task records derived from that receipt.  Repository
  // attribution metadata is useful for ordinary commits, but is not evidence
  // that it belongs to this particular publication.  Letting it bypass the
  // slice would reintroduce unrelated global state into an otherwise exact
  // generated-output delivery bundle.
  const commitAttributionStageCandidates = deliverySliceStageFiles
    ? []
    : unstagedDirtyFiles.filter(
      (filePath: LegacyValue) => isCommitAttributionSideEffectPath(filePath),
    );
  const stageCandidates = uniqueSorted([
    ...commitAttributionStageCandidates,
    ...(input.autoStage
      ? [
          ...(deliverySliceRejection ? [] : autoStagePool),
          // Protected audit records are ignored worktree files.  Their embedded
          // task id is the ownership proof, so include the verified set at the
          // final candidate boundary even if an earlier generic classifier
          // discarded the ignored path.
          ...taskOwnedProtectedOverrideAudits,
        ].filter((filePath: LegacyValue) => !isCommitAttributionSideEffectPath(filePath))
      : []),
  ]);
  const commitFiles = buildTaskScopedCommitFileSet({
    inScopeStagedFiles,
    inScopeStagedDeletions,
    stageCandidates,
    uniqueSorted,
  });
  const commitFilesWithGovernanceEvidence =
    shouldStageGovernedGitHeadEvidenceBeforeCommit(commitFiles)
      ? uniqueSorted([...commitFiles, gitHeadEvidencePath])
      : commitFiles;
  let protectedGovernanceStateReport = inspectProtectedGovernanceStateDestructiveChanges({
    cwd: input.cwd,
    taskId: input.taskId,
    commitFiles: commitFilesWithGovernanceEvidence,
    authorizedGeneratedResidueDeletions: autoCleanedResidue.map((entry: LegacyValue) => entry.path),
  });
  const closeoutOnlyMutationFiles =
    claimIntent === "closeout-only"
      ? uniqueSorted(
          [...commitFiles, ...unstagedDirtyFiles, ...inScopeStagedFiles].filter((filePath: LegacyValue) => {
            const normalized = normalizeRelativePath(filePath);
            if (!normalized || normalized.startsWith(".atm/")) return false;
            if (planningPath && normalized === planningPath) return false;
            if (isCommitAttributionSideEffectPath(normalized)) return false;
            return declaredScope.some((scope: LegacyValue) =>
              pathMatchesTaskScope(normalized, scope),
            );
          }),
        )
      : [];
  let blockedCode = null;
  let blockedSummary = null;
  if (!protectedGovernanceStateReport.ok && !(input.autoStage && stageCandidates.length > 0)) {
    blockedCode = ATM_PROTECTED_GOVERNANCE_STATE_DESTRUCTIVE_WRITE;
    blockedSummary = protectedGovernanceStateReport.summary;
  } else if (
    input.deferForeignStaged &&
    gitIndexOwnership.foreignActiveStaged.length > 0 &&
    !protectedForeignDeferAuthorized &&
    !lifecycleAuthorizedForeignDefer &&
    !hasAuthorizedIndexLease
  ) {
    const diagnostic = buildForeignActiveStagedDiagnostic(gitIndexOwnership);
    blockedCode = ATM_INDEX_FOREIGN_ACTIVE_STAGED;
    blockedSummary = indexLeaseAuthorization && !indexLeaseAuthorization.ok
      ? indexLeaseAuthorization.summary
      : `Refusing to unstage/defer foreign-active staged files owned by ${diagnostic.ownerTaskIds.join(", ")}: ${diagnostic.stagedPaths.join(", ")}. Wait for the owner, request a Broker index lane, or use an explicit stage-override lease with human approval.`;
  } else if (
    input.deferForeignStaged &&
    protectedForeignStagedOwnershipFiles.length > 0 &&
    !protectedForeignDeferAuthorized &&
    !lifecycleAuthorizedForeignDefer &&
    !hasAuthorizedIndexLease
  ) {
    blockedCode = "ATM_GIT_COMMIT_PROTECTED_FOREIGN_STAGED_OWNERSHIP";
    blockedSummary = `Refusing to unstage protected .atm/history files that belong to another task: ${protectedForeignStagedOwnershipFiles.join(", ")}. Wait for that task owner to commit/release, request a Broker index lane, or use an explicit stage-override lease with human approval.`;
  } else if (blockedResidue.length > 0) {
    blockedCode = "ATM_GIT_COMMIT_GENERATED_RESIDUE_BLOCKED";
    blockedSummary = `Generated residue belongs to another task/run and must be cleared explicitly: ${blockedResidue.map((entry: LegacyValue) => entry.path).join(", ")}`;
  } else if (manualReviewResidue.length > 0) {
    blockedCode = "ATM_GIT_COMMIT_GENERATED_RESIDUE_MANUAL_REVIEW";
    blockedSummary = `Generated-looking residue needs manual review before commit: ${manualReviewResidue.map((entry: LegacyValue) => entry.path).join(", ")}`;
  } else if (claimIntent === "closeout-only" && closeoutOnlyMutationFiles.length > 0) {
    blockedCode = "ATM_GIT_COMMIT_CLOSEOUT_ONLY_MUTATION";
    blockedSummary = `Task ${input.taskId} holds a closeout-only claim but the commit bundle contains source mutations: ${closeoutOnlyMutationFiles.join(", ")}. Re-claim with --claim-intent write before committing new source changes.`;
  } else if (deliverySliceRejection) {
    blockedCode = deliverySliceRejection.code;
    blockedSummary = deliverySliceRejection.reason;
  }
  const liveSealedBundle = sealCommitBundleFromLiveIndex({
    cwd: input.cwd,
    paths: commitFilesWithGovernanceEvidence,
    provenance: "task-scope",
  });
  const sealedBundle = input.autoStage && stageCandidates.length > 0
    ? withWorktreeCandidateIndex({
      cwd: input.cwd,
      paths: stageCandidates,
      run: (env) => {
        protectedGovernanceStateReport = inspectProtectedGovernanceStateDestructiveChanges({
          cwd: input.cwd,
          taskId: input.taskId,
          env,
          commitFiles: commitFilesWithGovernanceEvidence,
          authorizedGeneratedResidueDeletions: autoCleanedResidue.map((entry: LegacyValue) => entry.path),
        });
        return mergeSealedCommitBundles(
          liveSealedBundle,
          sealCommitBundleFromCandidateIndex({ cwd: input.cwd, env, paths: stageCandidates }),
          { supersedingPaths: stageCandidates, surface: "auto-stage-worktree-overlay" },
        );
      },
    })
    : liveSealedBundle;
  if (!blockedCode && !protectedGovernanceStateReport.ok) {
    blockedCode = ATM_PROTECTED_GOVERNANCE_STATE_DESTRUCTIVE_WRITE;
    blockedSummary = protectedGovernanceStateReport.summary;
  }
  // Auto-stage is assembled solely in the sealed candidate index. Writing the
  // same paths into the shared index is both unnecessary for the eventual
  // commit and a concurrency hazard for unrelated lanes.
  if (unexpectedStagedTasks.length > 0) {
    governanceBundleWarnings.push(
      `Foreign staged tasks remain in the shared index but will be excluded from the governed commit bundle: ${unexpectedStagedTasks.map((entry: LegacyValue) => entry.taskId).join(", ")}`,
    );
  }
  if (lifecycleAuthorizedForeignDefer) {
    governanceBundleWarnings.push(
      `Lifecycle-authorized released residue was preserved through the standard index park/restore transaction: ${releasedResidueTransaction.ownerTaskIds.join(', ')}.`,
    );
  }
  if (autoCleanedResidue.length > 0) {
    governanceBundleWarnings.push(
      `ATM auto-cleaned generated residue before governed commit: ${autoCleanedResidue.map((entry: LegacyValue) => `${entry.path} (${entry.reason})`).join("; ")}`,
    );
  }
  const deferredGovernanceResidue = reconciledResidueReport.blockAndExplain.filter(
    (entry: LegacyValue) =>
      input.deferForeignStaged &&
      isDeferrableForeignGovernanceResidue(input.taskId, entry),
  );
  if (deferredGovernanceResidue.length > 0) {
    governanceBundleWarnings.push(
      `Deferred foreign generated governance residue outside this task bundle: ${deferredGovernanceResidue.map((entry: LegacyValue) => `${entry.path} (${entry.ownerTaskId})`).join("; ")}`,
    );
  }
  return {
    schemaId: "atm.taskScopedCommitBundle.v1",
    taskId: input.taskId,
    ok: blockedCode === null,
    // TASK-GIT-0029: seal the admitted content here, where ownership was just
    // inspected. The commit executor assembles from this seal, so a concurrent
    // writer replacing content behind an admitted path afterwards cannot ride
    // along under an already-approved path.
    sealedBundle,
    apply: input.apply,
    stagingStrategy: input.autoStage
      ? "explicit-pathspec-git-add"
      : "manual-staged-index",
    stagingCommand:
      input.autoStage && stageCandidates.length > 0
        ? ["git", "add", "-A", "-f", "--", ...stageCandidates]
        : null,
    stageFiles: input.autoStage
      ? uniqueSorted([...stageCandidates, ...inScopeStagedFiles, ...inScopeStagedDeletions])
      : inScopeUnstagedDirty,
    commitFiles: commitFilesWithGovernanceEvidence,
    skippedExternalDirtyFiles: uniqueSorted(skippedExternalDirtyFiles),
    unexpectedStagedTasks,
    gitIndexOwnership,
    indexLeaseAuthorization,
    outOfScopeStagedFiles: uniqueSorted([
      ...outOfScopeStagedFiles,
      ...outOfScopeStagedDeletions,
    ]),
    governanceBundleWarnings,
    protectedGovernanceStateReport,
    blockedCode,
    blockedSummary,
    closeoutOnlyMutationFiles,
    gitExecutable,
    copyableCommitCommand,
    deferredForeignStagedSnapshot,
    autoCleanedResidue,
    blockedResidue,
    manualReviewResidue,
  };
}
