import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AgentPack } from '../packages/agent-pack-sdk/src/index.ts';
import { claudeCodePack } from '../packages/agent-pack-claude-code/src/index.ts';
import { copilotPack } from '../packages/agent-pack-copilot/src/index.ts';
import { cursorPack } from '../packages/agent-pack-cursor/src/index.ts';
import { geminiPack } from '../packages/agent-pack-gemini/src/index.ts';
import { windsurfPack } from '../packages/agent-pack-windsurf/src/index.ts';
import { supportedAgentProfiles } from '../packages/cli/src/commands/agent-confidence.ts';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

export const agentMatrixOutputPath = 'docs/multi-agent-compatibility-matrix.md';

const builtInAgentPacks = [
  claudeCodePack,
  cursorPack,
  copilotPack,
  geminiPack,
  windsurfPack
] as const;

const displayNameByPackId: Record<string, string> = {
  'claude-code': 'Claude Code',
  cursor: 'Cursor',
  copilot: 'GitHub Copilot Agent',
  gemini: 'Gemini',
  windsurf: 'Windsurf'
};

const confidenceAdapterByProfileId: Record<string, string> = {
  'claude-code': '`claude-code`',
  cursor: '`cursor`',
  aider: 'n/a',
  'github-copilot-agent': '`copilot`',
  'openai-assistants-api': 'n/a'
};

const officialIntegrationAdapters = [
  {
    adapterId: 'claude-code',
    managedRoots: '`.claude/skills`',
    fileFormats: 'SKILL.md',
    firstCommand: '`node atm.mjs next --json`'
  },
  {
    adapterId: 'codex',
    managedRoots: '`integrations/codex-skills`',
    fileFormats: 'SKILL.md',
    firstCommand: '`node atm.mjs next --json`'
  },
  {
    adapterId: 'copilot',
    managedRoots: '`.github`, `.github/instructions`, `.github/prompts`',
    fileFormats: 'Markdown',
    firstCommand: '`node atm.mjs next --json`'
  },
  {
    adapterId: 'cursor',
    managedRoots: '`.cursor/rules/skills`',
    fileFormats: 'Markdown',
    firstCommand: '`node atm.mjs next --json`'
  },
  {
    adapterId: 'gemini',
    managedRoots: '`.gemini/commands`',
    fileFormats: 'TOML',
    firstCommand: '`node atm.mjs next --json`'
  }
] as const;

interface AgentPackMatrixRow {
  readonly agent: string;
  readonly packId: string;
  readonly agentTarget: string;
  readonly managedRoots: string;
  readonly fileFormats: string;
  readonly managedFiles: number;
  readonly firstCommand: string;
  readonly sourceHash: string;
}

export function collectAgentPackRows(): AgentPackMatrixRow[] {
  return builtInAgentPacks.map((pack) => ({
    agent: displayNameByPackId[pack.packId] ?? pack.name.replace(/ Agent Pack$/, ''),
    packId: pack.packId,
    agentTarget: pack.agentTarget,
    managedRoots: summarizeManagedRoots(pack),
    fileFormats: summarizeFormats(pack),
    managedFiles: pack.targetFiles.length,
    firstCommand: '`node atm.mjs next --json`',
    sourceHash: `\`${(pack.sourceHash ?? hashJson(pack.targetFiles)).slice(0, 16)}\``
  }));
}

export function renderAgentMatrixMarkdown(): string {
  const packRows = collectAgentPackRows();
  const sourceHash = hashJson({
    packRows,
    officialIntegrationAdapters,
    confidenceProfiles: supportedAgentProfiles.map((profile) => ({
      id: profile.id,
      label: profile.label,
      executionMode: profile.executionMode
    }))
  });

  return `${[
    '# Multi-Agent Compatibility Matrix',
    '',
    '<!-- generated by scripts/render-agent-matrix.ts; do not edit manually -->',
    '',
    'This matrix is generated from built-in agent-pack metadata and advisory confidence profiles. It exists to prevent drift between the installed pack registry, the public compatibility table, and the multi-agent confidence workflow.',
    '',
    `Source metadata SHA-256: \`${sourceHash}\``,
    '',
    '## Agent Pack Registry Matrix',
    '',
    '| Agent | Pack ID | Agent Target | Managed Target Roots | File Formats | Managed Files | First Command | Source Hash |',
    '| --- | --- | --- | --- | --- | ---: | --- | --- |',
    ...packRows.map((row) => `| ${row.agent} | \`${row.packId}\` | \`${row.agentTarget}\` | ${row.managedRoots} | ${row.fileFormats} | ${row.managedFiles} | ${row.firstCommand} | ${row.sourceHash} |`),
    '',
    'Every generated agent entry routes the first operational action back to `node atm.mjs next --json`; agent packs are onboarding wrappers, not a second governance protocol.',
    '',
    '## Integration Adapter Registry Matrix',
    '',
    'Official integration adapters are installable through `atm integration list/add/verify/remove` and record per-adapter manifests under `.atm/integrations/`.',
    '',
    '| Adapter ID | Managed Target Roots | File Formats | First Command | CLI Lifecycle |',
    '| --- | --- | --- | --- | --- |',
    ...officialIntegrationAdapters.map((adapter) => `| \`${adapter.adapterId}\` | ${adapter.managedRoots} | ${adapter.fileFormats} | ${adapter.firstCommand} | list/add/verify/remove |`),
    '',
    '## Advisory Confidence Profiles',
    '',
    'The confidence gate is advisory for alpha0. It verifies that bootstrap prompts, AGENTS instructions, and deterministic self-hosting proof remain model-neutral across common agent envelopes.',
    '',
    '| Agent | Profile ID | Confidence Source | Integration Adapter | Charter Entry Status | First Command | Alpha0 Blocker |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...supportedAgentProfiles.map((profile) => `| ${profile.label} | \`${profile.id}\` | \`atm self-host-alpha --verify --agent ${profile.id} --json\` | ${confidenceAdapterByProfileId[profile.id] ?? 'n/a'} | ${confidenceAdapterByProfileId[profile.id] === 'n/a' ? 'n/a' : 'pass'} | \`node atm.mjs next --json\` | no |`),
    '',
    'All profiles also require `atm verify --agents-md --json` to confirm that bootstrap instructions remain vendor-neutral and do not depend on IDE-specific slash commands.',
    '',
    'Adapter Install + First Command evidence lives in `examples/agent-onboarding-flow/run.ts` and `docs/multi-agent-results.md`; this generated matrix records the current pack surface.',
    '',
    'For the first-touch onboarding surface that wraps these adapters for a new agent, see [docs/AGENT_PACK_ONBOARDING.md](docs/AGENT_PACK_ONBOARDING.md).'
  ].join('\n')}\n`;
}

function summarizeManagedRoots(pack: AgentPack): string {
  const roots = new Set<string>();
  for (const targetFile of pack.targetFiles) {
    roots.add(collapseTargetRoot(pack.packId, targetFile.path));
  }
  return [...roots].sort().map((entry) => `\`${entry}\``).join(', ');
}

function collapseTargetRoot(packId: string, targetPath: string): string {
  const parts = targetPath.split('/');
  if (packId === 'cursor') return parts.slice(0, 3).join('/');
  if (packId === 'copilot') return parts.length > 2 ? parts.slice(0, 2).join('/') : parts[0];
  return parts.slice(0, 2).join('/');
}

function summarizeFormats(pack: AgentPack): string {
  const formats = new Set(pack.targetFiles.map((file) => formatForPath(file.path)));
  return [...formats].sort().join(', ');
}

function formatForPath(targetPath: string): string {
  if (targetPath.endsWith('.toml')) return 'TOML';
  if (targetPath.endsWith('.md')) return 'Markdown';
  if (targetPath.endsWith('.prompt.md')) return 'Prompt Markdown';
  if (targetPath.endsWith('.agent.md')) return 'Agent Markdown';
  if (targetPath.endsWith('.yml') || targetPath.endsWith('.yaml')) return 'YAML';
  return path.extname(targetPath).replace(/^\./, '').toUpperCase() || 'text';
}

function hashJson(value: unknown): string {
  return createHash('sha256').update(JSON.stringify(value), 'utf8').digest('hex');
}

function writeMatrix(): void {
  const outputPath = path.join(root, agentMatrixOutputPath);
  mkdirSync(path.dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, renderAgentMatrixMarkdown(), 'utf8');
}

function checkMatrix(): void {
  const outputPath = path.join(root, agentMatrixOutputPath);
  const expected = renderAgentMatrixMarkdown();
  const actual = existsSync(outputPath) ? readFileSync(outputPath, 'utf8') : '';
  if (actual !== expected) {
    console.error(`[agent-matrix] ${agentMatrixOutputPath} is stale. Run: node --strip-types scripts/render-agent-matrix.ts`);
    process.exitCode = 1;
    return;
  }
  console.log(`[agent-matrix] ok (${collectAgentPackRows().length} packs)`);
}

const isDirectRun = process.argv[1]
  ? path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
  : false;

if (isDirectRun) {
  if (process.argv.includes('--check')) {
    checkMatrix();
  } else if (process.argv.includes('--stdout')) {
    process.stdout.write(renderAgentMatrixMarkdown());
  } else {
    writeMatrix();
    console.log(`[agent-matrix] wrote ${agentMatrixOutputPath}`);
  }
}
