// @ts-nocheck
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { appendFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { classifyTerminalLifecycleOwnership } from '../../../../../core/src/broker/historical-work-admission-attestation.ts';
import {
  buildFrameworkTempClaimCommand,
  buildFrameworkStaleCleanupCommand,
  createFrameworkModeStatus,
  findCloseCommitWindowCoveringPaths,
  inspectAutoGeneratedResidue,
  isAdopterInfrastructureSyncCommit,
  isFrameworkStaleLockReleasable,
  readActiveCloseCommitWindows,
  type AutoGeneratedResidueFinding,
  type FrameworkStaleLockInfo
} from '../../framework-development.ts';
import { findActorByResolvedId, inspectTrackedActorRegistryState, readRuntimeIdentityDefault, readRuntimeIdentityForActor } from '../../actor-registry.ts';
import { detectCrossTaskMutation, recordIncidentFlag } from '../../../../../core/src/broker/cross-task-mutation-guard.ts';
import { resolveActorWorkSession } from '../../actor-session.ts';
import { gitHeadEvidencePath, gitHeadEvidencePaths } from '../../git-head-evidence.ts';
import { CliError, makeResult, message, quoteCliValue, readFrameworkVersion, relativePathFrom } from '../../shared.ts';
import {
  diagnoseTaskDirectionLockAllowedFiles,
  isPlanningMirrorPath,
  isTaskDirectionPathCandidate,
  readActiveTaskDirectionLocks,
  type TaskDirectionAllowedFilesDiagnosis
} from '../../task-direction.ts';
import { isPathAllowedByScope, listActiveBatchRuns, readActiveQuickfixLock } from '../../work-channels.ts';
import { readBrokerLifecycleState } from '../../../../../core/src/broker/lifecycle.ts';
import { buildPendingCheckpointCommitWindow } from '../../batch.ts';
import { listTaskOwnedProtectedOverrideAuditFiles } from '../../git-governance.ts';
import { isReleasedGeneratedBundleSafeToClean, readGeneratedResidueTaskDisposition, reconcileReleasedResidueReport } from '../../tasks/generated-residue-policy.ts';
import {
  classifyBlockLifecycleRecordBundle,
  isRecordCommitBlockBridgeAuthorized,
  recordOnlyClaimScopeExemptCovers,
  RECORD_COMMIT_BLOCK_BRIDGE_AUTH_DIR,
  RECORD_COMMIT_BLOCK_BRIDGE_AUTH_ENV,
  type RecordCommitBlockBridgeAuthorization
} from '../../git-governance/record-only-block-lifecycle-bridge.ts';
import { resolvePreCommitResidueCandidates } from './residue-candidates.ts';
import { buildTeamGateFindings } from './team-gate-findings.ts';
import { findCaseInsensitiveRelativePath, taskIdsEqual, taskIdsInclude } from '../../tasks/task-import-validators.ts';
import { hookContractVersion, hookProvider } from '../git-hooks-installer.ts';
import { inspectGitIndexAccess, normalizeRelativePath, runGit, runGitLines, runGitScalar, createSanitizedGitEnv } from '../git-index-diagnostics.ts';
import { type CommandRunReport, type PreCommitAdvisoryFinding } from '../pre-push.ts';
import {
  findFutureCommitEvidenceMatchInWorktree,
  normalizeOptionalText,
  readCurrentHeadForFutureCommit,
  readGitObjectText,
  readJsonText,
  readStagedTreeWithoutEvidence
} from '../commit-range-guard.ts';
import { buildBrokerResolutionDependencyDeferral, checkStageTimeCrossFileConsistency } from './cross-file-consistency.ts';
import { buildCommitTaskFrameworkLockContext } from './framework-lock-context.ts';
import { authorizesRunnerPublicationCloseCommit } from '../../framework-development/runner-publication-close-handoff.ts';
import { buildPreCommitBlockingFindings, buildPreCommitFailureEnvelope, isPreCommitBaselineFinding, isPreCommitEnvironmentFinding, selectActionableResidueFindings, summarizePreCommitFailureEnvelope } from './failure-envelope.ts';
import { inspectTaskCardStatusChanges, readStagedChangedLineCount, readStagedFiles, scanEncoding, shouldWriteGitHeadEvidenceForStagedCommit, writeStagedGitHeadEvidence } from './input-state.ts';
import {
  buildIdentitySetRequiredCommand,
  cleanupAutoGeneratedResidue,
  collectCloseCommitWindowPlanningMirrorFiles,
  collectFrameworkTempClaimAllowedFiles,
  collectIdentityProvenanceFindings,
  collectStagedBatchCheckpointScopeFiles,
  collectTaskGovernedCommitAllowedFiles,
  inferTaskIdsFromStagedFiles,
  inspectCloseCommitWindowStagedArtifacts,
  inspectCommitAttribution,
  inspectEmergencyUseAudit,
  inspectHistoricalLedgerRestoreStagedArtifacts,
  inspectMirrorSyncOnlyStagedArtifacts,
  inspectPendingBatchCheckpointStagedArtifacts,
  inspectProtectedAtmStateChanges,
  inspectSameFileClaimOwnership,
  inspectTaskOpenImportBundleStagedArtifacts,
  isActionableManualResidue,
  isPathAllowedByTaskDirection,
  isResolutionAuthorizedCurrentTask,
  isTaskDirectionPreCommitExempt,
  isUnconsumedCloseWindowDeferralSnapshot,
  parseHookTaskClaim,
  resolveExpectedGitIdentityForActor,
  resolvePendingBatchCheckpointTaskId,
  resolveResidueTaskId,
  selectRelevantDirectionLocksForCommit,
  uniqueSorted,
  type SameFileClaimOwnershipReport
} from './support.ts';

export { inspectProtectedAtmStateChanges, isUnconsumedCloseWindowDeferralSnapshot } from './support.ts';

// ATM-GOV-0266 hook parity: a governed `git record-commit` may persist exactly
// one already-blocked/released card's ledger plus its matching block event while
// an unrelated framework claim is active. The pre-commit hook consumes the same
// block-lifecycle classifier and only lets that exact pair through when a
// single-use, content-bound authorization artifact — written by the governed
// record-commit path and referenced by a commit-env nonce — proves the context.
// A raw `git commit` of an identical pair has no such artifact and stays blocked
// with `ATM_CROSS_TASK_MUTATION_BLOCKED`.
export function authorizeBlockLifecycleRecordBridge(
  root: string,
  crossTaskBlock: { readonly conflictFiles: readonly string[] }
): { readonly authorized: boolean; readonly reason: string } {
  const stagedFiles = readStagedFiles(root).filter(
    (entry) => entry !== gitHeadEvidencePaths.legacyJson && entry !== gitHeadEvidencePaths.jsonl
  );
  const outcome = classifyBlockLifecycleRecordBundle({
    stagedFiles,
    readLedgerRecord: (bridgeTaskId) => {
      const ledgerPath = path.join(root, '.atm', 'history', 'tasks', `${bridgeTaskId}.json`);
      if (!existsSync(ledgerPath)) return null;
      try {
        const ledgerDoc = JSON.parse(readFileSync(ledgerPath, 'utf8')) as Record<string, any>;
        const claim = ledgerDoc.claim && typeof ledgerDoc.claim === 'object' ? ledgerDoc.claim : null;
        return {
          workItemId: typeof ledgerDoc.workItemId === 'string' ? ledgerDoc.workItemId : (typeof ledgerDoc.id === 'string' ? ledgerDoc.id : null),
          status: typeof ledgerDoc.status === 'string' ? ledgerDoc.status : '',
          claimState: claim && typeof claim.state === 'string' ? claim.state : null,
          claimActorId: claim && typeof claim.actorId === 'string' ? claim.actorId : null,
          claimLeaseId: claim && typeof claim.leaseId === 'string' ? claim.leaseId : null
        };
      } catch {
        return null;
      }
    },
    readEventRecord: (eventPath) => {
      const eventAbs = path.join(root, eventPath);
      if (!existsSync(eventAbs)) return null;
      try {
        const eventDoc = JSON.parse(readFileSync(eventAbs, 'utf8')) as Record<string, any>;
        return {
          taskId: typeof eventDoc.taskId === 'string' ? eventDoc.taskId : null,
          action: typeof eventDoc.action === 'string' ? eventDoc.action : null,
          toStatus: typeof eventDoc.toStatus === 'string' ? eventDoc.toStatus : null,
          actorId: typeof eventDoc.actorId === 'string' ? eventDoc.actorId : null,
          taskPath: typeof eventDoc.taskPath === 'string' ? eventDoc.taskPath : null
        };
      } catch {
        return null;
      }
    }
  });
  if (outcome.kind !== 'eligible') {
    return { authorized: false, reason: `staged set is not an eligible block-lifecycle pair (${outcome.kind})` };
  }
  // The exempt pair must fully cover the flagged conflict; any extra conflicting
  // file keeps the block fail-closed.
  if (!recordOnlyClaimScopeExemptCovers(outcome.exemptPaths, crossTaskBlock.conflictFiles)) {
    return { authorized: false, reason: 'cross-task conflict extends beyond the eligible block-lifecycle pair' };
  }
  const nonce = typeof process.env[RECORD_COMMIT_BLOCK_BRIDGE_AUTH_ENV] === 'string'
    ? process.env[RECORD_COMMIT_BLOCK_BRIDGE_AUTH_ENV].trim()
    : '';
  let authorization: RecordCommitBlockBridgeAuthorization | null = null;
  if (nonce.length > 0) {
    const authPath = path.join(root, RECORD_COMMIT_BLOCK_BRIDGE_AUTH_DIR, `${nonce}.json`);
    if (existsSync(authPath)) {
      try {
        authorization = JSON.parse(readFileSync(authPath, 'utf8')) as RecordCommitBlockBridgeAuthorization;
      } catch {
        authorization = null;
      }
    }
  }
  const sha256 = (filePath: string): string => createHash('sha256').update(readFileSync(path.join(root, filePath))).digest('hex');
  const committingActorId = typeof process.env.ATM_COMMIT_ACTOR_ID === 'string' && process.env.ATM_COMMIT_ACTOR_ID.trim().length > 0
    ? process.env.ATM_COMMIT_ACTOR_ID.trim()
    : null;
  return isRecordCommitBlockBridgeAuthorized({
    eligible: outcome,
    authorization,
    committingActorId,
    ledgerSha256: sha256(outcome.ledgerPath),
    eventSha256: sha256(outcome.eventPath),
    nowMs: Date.now()
  });
}

export function runPreCommitHook(cwd: string) {
  const root = path.resolve(cwd);
  const committingTaskIdForHook = typeof process.env.ATM_COMMIT_TASK_ID === 'string' ? process.env.ATM_COMMIT_TASK_ID.trim() : null;
  const scopedIndexActive = typeof process.env.GIT_INDEX_FILE === 'string' && process.env.GIT_INDEX_FILE.trim().length > 0;
  const crossTaskBlock = detectCrossTaskMutation(root, committingTaskIdForHook, 'pre-commit', scopedIndexActive ? readStagedFiles(root) : undefined);
  const hasTaskHistoryCrossTaskBlock = crossTaskBlock?.conflicts.some((entry) => entry.surface === 'task-history') ?? false;
  if (crossTaskBlock && hasTaskHistoryCrossTaskBlock && !isResolutionAuthorizedCurrentTask(root, committingTaskIdForHook, crossTaskBlock.conflictTaskId) && !authorizeBlockLifecycleRecordBridge(root, crossTaskBlock).authorized) {
    recordIncidentFlag(root, crossTaskBlock);
    throw new CliError('ATM_CROSS_TASK_MUTATION_BLOCKED', `Cross-task mutation incident detected: files owned by active task ${crossTaskBlock.conflictTaskId} are mutated. File(s): ${crossTaskBlock.conflictFiles.join(', ')}. Recovery: ${crossTaskBlock.recoveryLane}`, {
      exitCode: 1,
      details: {
        taskId: committingTaskIdForHook,
        conflictTaskId: crossTaskBlock.conflictTaskId,
        conflictFiles: crossTaskBlock.conflictFiles,
        recoveryLane: crossTaskBlock.recoveryLane
      }
    });
  }
  const commitIndexFinalized = process.env.ATM_COMMIT_INDEX_FINALIZED === '1';
  const residueCandidates = resolvePreCommitResidueCandidates(root, scopedIndexActive);
  const residueTaskId = resolveResidueTaskId(root);
  const residueReport = inspectAutoGeneratedResidue(residueTaskId, residueCandidates, root);
  const releasedBundleResidue = residueCandidates.filter((filePath) => /^\.atm\/history\/evidence\/[^/]+\.bundle-manifest\.json$/i.test(filePath)).map((filePath) => {
      const ownerTaskId = filePath.match(/^\.atm\/history\/evidence\/([^/]+)\.bundle-manifest\.json$/i)?.[1]?.toUpperCase() ?? null;
      const disposition = ownerTaskId ? readGeneratedResidueTaskDisposition(root, ownerTaskId) : null;
      return ownerTaskId && isReleasedGeneratedBundleSafeToClean(disposition) ? { path: filePath, verdict: 'auto-clean-safe' as const, reason: 'Released-task bundle-manifest is disposable generated residue; lifecycle audit records remain preserved.', ownerTaskId, cleanupAction: 'remove' as const } : null;
    }).filter((entry): entry is NonNullable<typeof entry> => Boolean(entry));
  const reconciledResidueReport = releasedBundleResidue.length === 0 ? residueReport : {
    ...residueReport,
    autoCleanSafe: [...residueReport.autoCleanSafe, ...releasedBundleResidue],
    blockAndExplain: residueReport.blockAndExplain.filter((entry) => !releasedBundleResidue.some((released) => released.path === entry.path)),
  };
  const transactionReconciledResidueReport = reconcileReleasedResidueReport(root, residueTaskId, reconciledResidueReport);
  const autoCleanedResidue = cleanupAutoGeneratedResidue(root, transactionReconciledResidueReport.autoCleanSafe);
  const stagedFiles = readStagedFiles(root).filter((entry) => entry !== gitHeadEvidencePaths.legacyJson && entry !== gitHeadEvidencePaths.jsonl);
  const actionableResidueFindings = selectActionableResidueFindings({
    findings: [...transactionReconciledResidueReport.blockAndExplain, ...transactionReconciledResidueReport.manualReview.filter((entry) => isActionableManualResidue(entry.path))],
    stagedFiles,
    committingTaskId: residueTaskId,
    activeLockTaskIds: new Set(
      readActiveTaskDirectionLocks(root)
        .map((lock) => typeof lock.taskId === 'string' ? lock.taskId.trim().toUpperCase() : '')
        .filter(Boolean),
    ),
    hasActiveClaim: (ownerTaskId: string) => {
      try {
        const taskDocument = JSON.parse(readFileSync(path.join(root, '.atm', 'history', 'tasks', `${ownerTaskId}.json`), 'utf8')) as Record<string, unknown>;
        const claim = taskDocument.claim as Record<string, unknown> | null | undefined;
        return Boolean(claim) && String((claim as Record<string, unknown>).state ?? '') === 'active';
      } catch {
        return false;
      }
    },
    hasInactiveLifecycleOwner: (ownerTaskId: string) => {
      try {
        const taskDocument = JSON.parse(readFileSync(path.join(root, '.atm', 'history', 'tasks', `${ownerTaskId}.json`), 'utf8')) as Record<string, unknown>;
        const status = String(taskDocument.status ?? '').trim().toLowerCase();
        const claim = taskDocument.claim as Record<string, unknown> | null | undefined;
        const claimState = claim ? String(claim.state ?? '').trim().toLowerCase() : '';
        const lockPath = path.join(root, '.atm', 'runtime', 'locks', `${ownerTaskId}.lock.json`);
        let lockReleased = true;
        if (existsSync(lockPath)) {
          const lock = JSON.parse(readFileSync(lockPath, 'utf8')) as Record<string, unknown>;
          lockReleased = lock.released === true || lock.status === 'released';
        }
        return classifyTerminalLifecycleOwnership({ status, claimState, lockReleased }).decision === 'terminal';
      } catch {
        return false;
      }
    }
  });
  const gitIndexDiagnostic = inspectGitIndexAccess(root);
  const encodingReport = scanEncoding(root, stagedFiles);
  const frameworkStatus = createFrameworkModeStatus({
    cwd: root,
    files: stagedFiles,
    taskId: committingTaskIdForHook,
    actorId: process.env.ATM_COMMIT_ACTOR_ID
  });
  const allowAdopterInfrastructureSync = isAdopterInfrastructureSyncCommit(
    stagedFiles.length > 0 ? stagedFiles : frameworkStatus.changedFiles
  );
  const activeDirectionLocks = readActiveTaskDirectionLocks(root);
  const activeQuickfixLock = readActiveQuickfixLock(root);
  const taskGovernedCommitAllowedFiles = collectTaskGovernedCommitAllowedFiles(root, committingTaskIdForHook);
  // TASK-AAO-0136: collect close-commit-window allowedFiles (short-lived locks
  // opened by tasks close / tasks reconcile). These authorize landing the close
  // artifacts after the regular direction lock has already released.
  const activeCloseCommitWindows = readActiveCloseCommitWindows(root);
  const closeCommitWindowAllowedFiles = uniqueSorted(activeCloseCommitWindows.flatMap((win) => [
    ...win.allowedFiles,
    `.atm/history/tasks/${win.taskId}.json`,
    `.atm/history/evidence/${win.taskId}.json`,
    `.atm/history/evidence/${win.taskId}.bundle-manifest.json`,
    `.atm/history/evidence/${win.taskId}.closure-packet.json`,
    `.atm/history/task-events/${win.taskId}/**`
  ]));
  const closeCommitWindowPlanningMirrorFiles = collectCloseCommitWindowPlanningMirrorFiles(root);
  const relevantDirectionLocks = selectRelevantDirectionLocksForCommit({
    activeDirectionLocks,
    stagedFiles,
    committingTaskId: committingTaskIdForHook,
    taskGovernedCommitAllowedFiles,
    closeCommitWindowAllowedFiles,
    closeCommitWindowPlanningMirrorFiles
  });
  const directionLockAllowedFiles = uniqueSorted(relevantDirectionLocks.flatMap((lock) => lock.allowedFiles));
  const directionLockAllowedFilesDiagnoses: readonly TaskDirectionAllowedFilesDiagnosis[] = activeDirectionLocks
    .map((lock) => diagnoseTaskDirectionLockAllowedFiles(root, lock.taskId));
  const directionLockAllowedFilesMismatches = directionLockAllowedFilesDiagnoses.filter((entry) => entry.mismatches.length > 0);
  const checkpointClosedTaskAllowedFiles = collectStagedBatchCheckpointScopeFiles(root, stagedFiles);
  const checkpointCoversFrameworkCriticalFiles = frameworkStatus.criticalChangedFiles.length > 0
    && frameworkStatus.criticalChangedFiles.every((entry) => isPathAllowedByTaskDirection(entry, checkpointClosedTaskAllowedFiles));
  const directionLockCoversFrameworkCriticalFiles = frameworkStatus.criticalChangedFiles.length > 0
    && frameworkStatus.criticalChangedFiles.every((entry) => isPathAllowedByTaskDirection(entry, directionLockAllowedFiles));
  const frameworkTempClaimAllowedFiles = collectFrameworkTempClaimAllowedFiles(root);
  const frameworkTempClaimCoversFrameworkCriticalFiles = frameworkStatus.criticalChangedFiles.length > 0
    && frameworkStatus.criticalChangedFiles.every((entry) => isPathAllowedByTaskDirection(entry, frameworkTempClaimAllowedFiles));
  const runnerPublicationReceiptPath = committingTaskIdForHook
    ? path.join(root, '.atm', 'history', 'evidence', `${committingTaskIdForHook}.runner-sync-receipt.json`)
    : null;
  const runnerPublicationReceipt = runnerPublicationReceiptPath && existsSync(runnerPublicationReceiptPath)
    ? readJsonText(readFileSync(runnerPublicationReceiptPath, 'utf8'))
    : null;
  const runnerPublicationCoversFrameworkCriticalFiles = committingTaskIdForHook
    ? authorizesRunnerPublicationCloseCommit({
      taskId: committingTaskIdForHook,
      receipt: runnerPublicationReceipt,
      criticalChangedFiles: frameworkStatus.criticalChangedFiles
    })
    : false;
  const rawBlockingFrameworkIssues = frameworkStatus.blockers.filter((entry) => {
    if (entry === 'git-head-evidence-missing') return false;
    if (entry === 'active-framework-claim-required' && (checkpointCoversFrameworkCriticalFiles || directionLockCoversFrameworkCriticalFiles || frameworkTempClaimCoversFrameworkCriticalFiles || runnerPublicationCoversFrameworkCriticalFiles)) return false;
    if (entry === 'closure-authority-belongs-to-target-repo' && allowAdopterInfrastructureSync) return false;
    return true;
  });
  const frameworkLockContext = buildCommitTaskFrameworkLockContext({
    blockers: rawBlockingFrameworkIssues,
    staleLocks: frameworkStatus.staleLocks,
    commitTaskId: process.env.ATM_COMMIT_TASK_ID,
    commitActorId: process.env.ATM_COMMIT_ACTOR_ID
  });
  const blockingFrameworkIssues = frameworkLockContext.blockers;
  const directionLockPlanningMirrorPaths = uniqueSorted(relevantDirectionLocks.flatMap((lock) => lock.planningMirrorPaths ?? []));
  const directionLockAllowsPlanningMirror = relevantDirectionLocks.some((lock) => lock.allowPlanningMirror === true);
  const taskOpenImportBundle = inspectTaskOpenImportBundleStagedArtifacts(root, stagedFiles);
  const directionLockDriftFiles = relevantDirectionLocks.length > 0 && !allowAdopterInfrastructureSync
    ? taskOpenImportBundle.ok
      ? []
      : stagedFiles
      .filter((entry) => !isTaskDirectionPreCommitExempt(entry))
      .filter((entry) => !isPathAllowedByTaskDirection(entry, directionLockAllowedFiles))
      .filter((entry) => !isPathAllowedByTaskDirection(entry, checkpointClosedTaskAllowedFiles))
      .filter((entry) => !isPathAllowedByTaskDirection(entry, frameworkTempClaimAllowedFiles))
      .filter((entry) => !isPathAllowedByTaskDirection(entry, taskGovernedCommitAllowedFiles))
      .filter((entry) => !isPathAllowedByTaskDirection(entry, closeCommitWindowAllowedFiles))
    : [];
  const planningMirrorDriftFiles = relevantDirectionLocks.length > 0 && !allowAdopterInfrastructureSync && directionLockPlanningMirrorPaths.length > 0 && !directionLockAllowsPlanningMirror
    ? stagedFiles
      .filter((entry) => !isTaskDirectionPreCommitExempt(entry))
      .filter((entry) => isPlanningMirrorPath(entry, directionLockPlanningMirrorPaths))
      .filter((entry) => !isPathAllowedByTaskDirection(entry, taskGovernedCommitAllowedFiles))
      .filter((entry) => !isPathAllowedByTaskDirection(entry, closeCommitWindowPlanningMirrorFiles))
    : [];
  const quickfixDriftFiles = activeQuickfixLock && !allowAdopterInfrastructureSync
    ? stagedFiles
      .filter((entry) => !isTaskDirectionPreCommitExempt(entry))
      .filter((entry) => !isPathAllowedByScope(entry, activeQuickfixLock.allowedFiles))
    : [];
  const quickfixFileLimitExceeded = activeQuickfixLock
    ? stagedFiles.filter((entry) => !entry.startsWith('.atm/')).length > activeQuickfixLock.maxFiles
    : false;
  const quickfixChangedLineCount = activeQuickfixLock
    ? readStagedChangedLineCount(root, stagedFiles.filter((entry) => !entry.startsWith('.atm/')))
    : 0;
  const quickfixLineLimitExceeded = activeQuickfixLock
    ? quickfixChangedLineCount > activeQuickfixLock.maxChangedLines
    : false;
  const isBrokerResolutionAuthorizedDependencyDeferral = buildBrokerResolutionDependencyDeferral(root, process.env.ATM_COMMIT_TASK_ID ?? null, process.env.ATM_COMMIT_BROKER_CONFLICT_RESOLUTION);
  const protectedStateReport = inspectProtectedAtmStateChanges(root, stagedFiles);
  const emergencyUseAuditReport = inspectEmergencyUseAudit(root, stagedFiles);
  const taskCardStatusReport = inspectTaskCardStatusChanges(root, stagedFiles);
  const commitAttributionReport = inspectCommitAttribution(root, stagedFiles);
  const explicitActorWarning = stagedFiles.length > 0 && !normalizeOptionalText(process.env.ATM_COMMIT_ACTOR_ID)
    ? message('warn', 'ATM_HOOK_COMMIT_ACTOR_NOT_EXPLICIT', 'No explicit commit actor was provided. Configure this editor/agent with its own actor identity instead of relying on repo default identity.', {
      clearStaleDefaultCommand: 'node atm.mjs identity clear --json',
      requiredCommand: 'node atm.mjs identity clear --json && node atm.mjs identity set --actor <actor-id> --editor <editor-id> --git-name "<git user.name>" --git-email "<git user.email>" --json',
      env: 'ATM_COMMIT_ACTOR_ID or ATM_ACTOR_ID'
    })
    : null;
  // TASK-CID-0024: same-file parallel claims are first-class. Multiple active
  // claims covering one staged file must not block by themselves; only
  // ambiguous staged ownership without steward/broker evidence blocks.
  const sameFileClaimReport = allowAdopterInfrastructureSync
    ? { ok: true, committingTaskId: null, committingClaimIntent: null, multiClaimFiles: [], stewardCoveredFiles: [], sharedWriteAdmission: null, findings: [] } satisfies SameFileClaimOwnershipReport
    : inspectSameFileClaimOwnership({
      cwd: root,
      stagedFiles,
      activeDirectionLocks: relevantDirectionLocks,
      exemptAllowedFileSets: [
        checkpointClosedTaskAllowedFiles,
        taskGovernedCommitAllowedFiles,
        closeCommitWindowAllowedFiles,
        frameworkTempClaimAllowedFiles
      ]
    });
  // A Git hook is a control-plane gate: it must only inspect the sealed staged
  // candidate and its directly-required authority. Repository-wide audits and
  // framework validator suites are execution-plane work, owned by taskflow
  // evidence, pre-push, and CI. Running them here made every commit wait on
  // unrelated task history and repeatedly revalidated one close transaction.
  const commandRuns: CommandRunReport[] = [];
  const failedValidatorRuns: CommandRunReport[] = [];
  const taskAuditFindings: readonly unknown[] = [];
  const staleLocks = frameworkLockContext.staleLocks;
  const releasableStaleLock = staleLocks.find(isFrameworkStaleLockReleasable) ?? null;
  const baseClaimCommand = buildFrameworkTempClaimCommand(frameworkStatus.criticalChangedFiles, 'temporary framework maintenance before commit', releasableStaleLock?.actorId ?? null);
  const frameworkClaimCommand = blockingFrameworkIssues.includes('active-framework-claim-required')
    ? baseClaimCommand
    : blockingFrameworkIssues.includes('framework-stale-lock-cleanup-required') && releasableStaleLock
      ? buildFrameworkStaleCleanupCommand(releasableStaleLock, frameworkStatus.criticalChangedFiles, 'temporary framework maintenance before commit')
    : null;
  const crossFileConsistencyFindings = checkStageTimeCrossFileConsistency({
    root,
    stagedFiles,
    isBrokerResolutionAuthorizedDependencyDeferral
  });
  const blockingTaskAuditFindings: readonly unknown[] = [];
  const baseOk = encodingReport.ok
    && gitIndexDiagnostic.ok
    && blockingFrameworkIssues.length === 0
    && planningMirrorDriftFiles.length === 0
    && directionLockDriftFiles.length === 0
    && quickfixDriftFiles.length === 0
    && !quickfixFileLimitExceeded
    && !quickfixLineLimitExceeded
    && commitAttributionReport.ok
    && protectedStateReport.ok
    && emergencyUseAuditReport.ok
    && taskCardStatusReport.ok
    && sameFileClaimReport.ok
    && blockingTaskAuditFindings.length === 0
    && failedValidatorRuns.length === 0
    && crossFileConsistencyFindings.length === 0
    && actionableResidueFindings.length === 0;
  const gitHeadEvidenceRequired = shouldWriteGitHeadEvidenceForStagedCommit({
    stagedFiles,
    criticalChangedFiles: frameworkStatus.criticalChangedFiles
  });
  // TASK-AAO-0136: collect tree-wide advisory findings (warnings only, not blockers).
  const advisoryFindings: PreCommitAdvisoryFinding[] = [];
  const teamGateFindings = buildTeamGateFindings(root, stagedFiles);
  const blockingFindings = [
    ...buildPreCommitBlockingFindings({
    encodingReport,
    gitIndexDiagnostic,
    blockingFrameworkIssues,
    frameworkClaimCommand,
    staleLocks,
    planningMirrorDriftFiles,
    directionLockDriftFiles,
    quickfixDriftFiles,
    quickfixFileLimitExceeded,
    quickfixLineLimitExceeded,
    quickfixChangedLineCount,
    commitAttributionFindings: commitAttributionReport.findings,
    protectedStateFindings: protectedStateReport.findings,
    emergencyUseAuditFindings: emergencyUseAuditReport.findings,
    taskCardStatusFindings: taskCardStatusReport.findings,
    sameFileClaimFindings: sameFileClaimReport.findings,
    taskAuditFindings,
    failedValidatorRuns,
    stagedFiles,
    advisoryFindingsSink: advisoryFindings,
    crossFileConsistencyFindings,
    residueFindings: actionableResidueFindings
    }),
    ...teamGateFindings
  ];
  const ok = baseOk && teamGateFindings.length === 0;
  const evidenceWrite = ok && gitHeadEvidenceRequired && !scopedIndexActive && !commitIndexFinalized
    ? writeStagedGitHeadEvidence(root, stagedFiles, commandRuns)
    : null;
  const failureEnvelope = ok
    ? null
    : buildPreCommitFailureEnvelope({
      blockingFindings,
      frameworkClaimCommand,
      gitIndexDiagnostic,
      failedValidatorRuns
    });

  const directionLockAllowedFilesWarning = directionLockAllowedFilesMismatches.length > 0
    ? message('warn', 'ATM_DIRECTION_LOCK_ALLOWED_FILES_MISMATCH', 'Active task direction lock(s) have drifted between top-level files, embedded allowedFiles, or claim.files. Canonical source is taskDirectionLock.allowedFiles.', {
      diagnoses: directionLockAllowedFilesMismatches
    })
    : null;

  return makeResult({
    ok,
    command: 'hook',
    cwd: root,
    messages: [
      ok
        ? message('info', 'ATM_HOOK_PRE_COMMIT_OK', 'ATM pre-commit hook passed and staged git-head evidence when needed.', {
          stagedFileCount: stagedFiles.length,
          criticalChangedFileCount: frameworkStatus.criticalChangedFiles.length,
          gitHeadEvidenceRequired,
          evidencePath: evidenceWrite?.evidencePath ?? null,
          scopedIndexActive,
          commitIndexFinalized,
          advisoryTreeWideFindingsCount: advisoryFindings.length
        })
        : message(
          'error',
          failureEnvelope?.deferredGovernanceCandidate
            ? 'ATM_HOOK_PRE_COMMIT_DEFERRED_GOVERNANCE_REQUIRED'
            : 'ATM_HOOK_PRE_COMMIT_FAILED',
          failureEnvelope?.deferredGovernanceCandidate
            ? 'ATM pre-commit blocked this commit on governance-state requirements; content validation did not report a failure.'
            : 'ATM pre-commit hook blocked this commit.',
          {
          encodingFindings: encodingReport.findings.length,
          frameworkBlockers: blockingFrameworkIssues,
          planningMirrorDriftFiles,
          taskDirectionDriftFiles: directionLockDriftFiles,
          quickfixDriftFiles,
          quickfixFileLimitExceeded,
          quickfixLineLimitExceeded,
          quickfixChangedLineCount,
          protectedStateFindings: protectedStateReport.findings,
          emergencyUseAuditFindings: emergencyUseAuditReport.findings,
          taskCardStatusFindings: taskCardStatusReport.findings,
          sameFileClaimFindings: sameFileClaimReport.findings,
          taskAuditFindings: taskAuditFindings.length,
          failedValidators: failedValidatorRuns.map((entry) => entry.command),
          gitIndexDiagnostic,
          crossFileConsistencyFindings: crossFileConsistencyFindings.length,
          // TASK-AAO-0136: blockingStagedFindings is the operator-facing split.
          blockingStagedFindings: blockingFindings,
          blockingFindings,
          governanceStateFindings: failureEnvelope?.governanceStateFailures ?? [],
          contentValidationFindings: failureEnvelope?.contentValidationFailures ?? [],
          deferredGovernanceCandidate: failureEnvelope?.deferredGovernanceCandidate ?? false,
          advisoryTreeWideFindings: advisoryFindings,
          failureEnvelope,
          nextStep: blockingFindings.find((entry) => entry.requiredCommand)?.requiredCommand ?? frameworkClaimCommand
        }),
      ...(directionLockAllowedFilesWarning ? [directionLockAllowedFilesWarning] : []),
      ...(explicitActorWarning ? [explicitActorWarning] : []),
      ...(autoCleanedResidue.length > 0
        ? [message('warn', 'ATM_HOOK_AUTO_CLEANED_GENERATED_RESIDUE', 'ATM auto-cleaned known generated residue before pre-commit evaluation.', {
            autoCleanedResidue
          })]
        : []),
      ...(advisoryFindings.length > 0
        ? [message('warn', 'ATM_HOOK_PRE_COMMIT_TREE_WIDE_ADVISORY', `Pre-commit found ${advisoryFindings.length} tree-wide task-audit finding(s) that do not affect this commit. Surfaced as advisory only.`, {
            advisoryTreeWideFindings: advisoryFindings
          })]
        : [])
    ],
    evidence: {
      action: 'pre-commit',
      stagedFiles,
      gitIndexDiagnostic,
      encodingReport,
      frameworkStatus,
      allowAdopterInfrastructureSync,
      blockingFrameworkIssues,
      frameworkClaimCommand,
      activeDirectionLocks,
      directionLockPlanningMirrorPaths,
      directionLockAllowedFilesDiagnoses,
      directionLockAllowedFilesMismatches,
      taskOpenImportBundle,
      planningMirrorDriftFiles,
      activeQuickfixLock,
      directionLockDriftFiles,
      quickfixDriftFiles,
      quickfixFileLimitExceeded,
      quickfixLineLimitExceeded,
      quickfixChangedLineCount,
      commitAttributionReport,
      protectedStateReport,
      emergencyUseAuditReport,
      taskCardStatusReport,
      sameFileClaimReport,
      taskAudit: {
        executionPlane: 'deferred',
        requiredBy: ['taskflow auto-evidence', 'pre-push', 'CI'],
        findings: taskAuditFindings
      },
      commandRuns,
      blockingFindings,
      crossFileConsistencyFindings,
      autoCleanedResidue,
      residueReport,
      failureEnvelope,
      gitHeadEvidenceRequired,
      evidenceWrite
    }
  });
}
