import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { createRegistryDocument } from '../../registry/registry.ts';
import { createAtomicMapSemanticFingerprint, normalizeSemanticFingerprint } from '../../registry/semantic-fingerprint.ts';
import { allocateMapId, MapIdAllocationError, parseMapId } from '../map-id-allocator.ts';
import { createGeneratorError, type GeneratorError } from './errors.ts';
import { computeAtomicMapHash } from './spec-support.ts';
import type {
  AllocateOptions,
  GenerateAtomicMapOptions,
  MapIdAllocationRecord,
  MapPaths,
  NormalizedRequest,
  PhaseRecord,
  RegistryDocument,
  RegistryEntry,
  RunTestOptions
} from './types.ts';

export function readRegistryDocument(registryAbsolutePath: string, options: GenerateAtomicMapOptions): RegistryDocument {
  if (options.registryDocument) {
    return options.registryDocument as RegistryDocument;
  }
  if (!existsSync(registryAbsolutePath)) {
    return createRegistryDocument([], {
      registryId: 'registry.atoms',
      generatedAt: options.now ?? new Date().toISOString()
    }) as RegistryDocument;
  }
  try {
    return JSON.parse(readFileSync(registryAbsolutePath, 'utf8')) as RegistryDocument;
  } catch (error) {
    throw createGeneratorError('ATM_REGISTRY_INVALID', 'Atomic registry JSON is invalid.', {
      registryPath: toPortablePath(registryAbsolutePath),
      reason: error instanceof Error ? error.message : String(error)
    });
  }
}

export function findExistingEntry(registryDocument: RegistryDocument, request: NormalizedRequest): RegistryEntry | null {
  const entries = Array.isArray(registryDocument?.entries) ? registryDocument.entries : [];
  const mapHash = computeAtomicMapHash({
    ...request,
    replacement: request.replacement ?? null
  });
  const semanticFingerprint = request.pendingSfCalculation === true
    ? null
    : createAtomicMapSemanticFingerprint(request);
  return (entries as RegistryEntry[]).find((entry) => {
    const e = entry as unknown as Record<string, unknown>;
    return e?.schemaId === 'atm.atomicMap'
      && e?.mapHash === mapHash
      && normalizeSemanticFingerprint((e?.semanticFingerprint ?? e?.mapSemanticFingerprint ?? null) as unknown) === semanticFingerprint
      && (request.pendingSfCalculation === true ? e?.pendingSfCalculation === true : true)
      && String(e?.mapVersion || '').trim() === request.mapVersion;
  }) ?? null;
}

export function allocateGeneratorMapId(request: NormalizedRequest, options: AllocateOptions) {
  const requestedMapId = options.mapId ?? (options.force === true ? options.existingEntry?.mapId : null);
  if (requestedMapId) {
    const parsed = parseMapId(requestedMapId);
    if (!parsed) {
      throw createGeneratorError('ATM_MAP_GENERATOR_MAP_ID_INVALID', 'Provided mapId must match ATM-MAP-{NNNN}.', { mapId: requestedMapId });
    }
    return {
      mapId: parsed.mapId,
      bucket: parsed.bucket,
      sequence: parsed.sequence,
      source: 'preassigned',
      reservation: options.force === true ? 'force-existing' : 'preassigned'
    } satisfies MapIdAllocationRecord;
  }

  return allocateMapId({
    repositoryRoot: options.repositoryRoot,
    registryPath: options.registryPath,
    registryDocument: options.registryDocument
  }) as MapIdAllocationRecord;
}

export function upsertRegistryEntry(registryDocument: RegistryDocument, registryEntry: RegistryEntry, options: { generatedAt?: string } = {}): RegistryDocument {
  const entries = Array.isArray(registryDocument?.entries) ? registryDocument.entries : [];
  const existingIndex = (entries as RegistryEntry[]).findIndex((entry) => entry?.mapId === registryEntry.mapId);
  const nextEntries = existingIndex >= 0
    ? (entries as RegistryEntry[]).map((entry, index) => index === existingIndex ? registryEntry : entry)
    : [...entries, registryEntry];
  return {
    schemaId: registryDocument?.schemaId ?? 'atm.registry',
    specVersion: registryDocument?.specVersion ?? '0.1.0',
    migration: registryDocument?.migration ?? {
      strategy: 'none',
      fromVersion: null,
      notes: 'Generated by AtomicMapGenerator provisioning facade.'
    },
    registryId: registryDocument?.registryId ?? 'registry.atoms',
    generatedAt: options.generatedAt ?? registryDocument?.generatedAt ?? new Date().toISOString(),
    entries: nextEntries
  };
}

export function createMapPaths(mapId: string): MapPaths {
  const workbenchPath = `atomic_workbench/maps/${mapId}`;
  return {
    workbenchPath,
    specPath: `${workbenchPath}/map.spec.json`,
    testPath: `${workbenchPath}/map.integration.test.ts`,
    reportPath: `${workbenchPath}/map.test.report.json`
  };
}

export function createMapLocation(paths: MapPaths) {
  return {
    specPath: paths.specPath,
    codePaths: [],
    testPaths: [paths.testPath],
    reportPath: paths.reportPath,
    workbenchPath: paths.workbenchPath
  };
}

export function createGeneratedMapEvidence(paths: MapPaths): string[] {
  return [
    'generator-provenance:generated',
    paths.specPath,
    paths.testPath,
    paths.reportPath
  ];
}

export function renderDefaultMapIntegrationTest(specDocument: Record<string, unknown>): string {
  return [
    "import assert from 'node:assert/strict';",
    "import { readFileSync } from 'node:fs';",
    '',
    "const spec = JSON.parse(readFileSync(new URL('./map.spec.json', import.meta.url), 'utf8'));",
    `assert.equal(spec.schemaId, ${JSON.stringify(specDocument.schemaId)});`,
    `assert.equal(spec.mapId, ${JSON.stringify(specDocument.mapId)});`,
    `assert.equal(spec.mapHash, ${JSON.stringify(specDocument.mapHash)});`,
    specDocument.pendingSfCalculation === true
      ? [
          'assert.equal(spec.pendingSfCalculation, true);',
          'assert.equal(spec.semanticFingerprint, null);'
        ].join('\n')
      : `assert.equal(spec.semanticFingerprint, ${JSON.stringify(specDocument.semanticFingerprint)});`,
    `assert.deepEqual(spec.entrypoints, ${JSON.stringify(specDocument.entrypoints)});`,
    `assert.deepEqual(spec.members, ${JSON.stringify(specDocument.members)});`,
    `assert.deepEqual(spec.edges, ${JSON.stringify(specDocument.edges)});`,
    `assert.deepEqual(spec.qualityTargets, ${JSON.stringify(specDocument.qualityTargets)});`,
    `console.log(${JSON.stringify(`${specDocument.mapId} map integration self-check ok`)});`,
    ''
  ].join('\n');
}

export function runGeneratedMapTest(options: RunTestOptions) {
  const result = spawnSync(process.execPath, [options.testPath], {
    cwd: options.repositoryRoot,
    encoding: 'utf8'
  });
  const report = {
    mapId: options.mapId,
    executedAt: options.now ?? new Date().toISOString(),
    command: [process.execPath, toPortablePath(path.relative(options.repositoryRoot, options.testPath))],
    specPath: toPortablePath(path.relative(options.repositoryRoot, options.specPath)),
    ok: result.status === 0,
    exitCode: result.status ?? 1,
    stdout: (result.stdout || '').trim(),
    stderr: (result.stderr || '').trim()
  };
  writeFileSync(options.reportPath, `${JSON.stringify(report, null, 2)}\n`, 'utf8');
  return {
    ok: report.ok,
    report
  };
}

export function recordPhase<T>(phases: PhaseRecord[], phase: string, action: () => T): T {
  const startedAt = Date.now();
  try {
    const result = action();
    phases.push({ phase, ok: true, durationMs: Date.now() - startedAt });
    return result;
  } catch (error) {
    phases.push({
      phase,
      ok: false,
      durationMs: Date.now() - startedAt,
      error: normalizeError(error)
    });
    throw error;
  }
}

export function normalizeError(error: unknown) {
  if (error instanceof MapIdAllocationError) {
    return {
      code: error.code,
      message: error.message,
      details: error.details
    };
  }
  const typedError = error as Partial<GeneratorError> | undefined;
  return {
    code: typedError?.code ?? 'ATM_MAP_GENERATOR_UNHANDLED',
    message: error instanceof Error ? error.message : String(error),
    details: typedError?.details ?? {}
  };
}

export function normalizeTrailingNewline(value: string): string {
  return String(value).endsWith('\n') ? String(value) : `${value}\n`;
}

export function toPortablePath(value: string): string {
  return String(value).replace(/\\/g, '/');
}
