// ATM-GOV-0181 / ATM-BUG-2026-07-12-147
// Abandon → next-task commit must not inherit orphan bundle-manifest /
// foreign-staged blockers, while the abandon audit trail stays admissible.
//
//   node --strip-types tests/cli/abandon-residue-governed-disposition.test.ts

import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { inspectAutoGeneratedResidue } from '../../packages/cli/src/commands/framework-development.ts';
import { resolveTaskScopedCommitBundle } from '../../packages/cli/src/commands/git-governance.ts';
import { applyAbandonedResidueDisposition } from '../../packages/cli/src/commands/tasks/close-orchestrator/close-write.ts';

function runGit(cwd: string, args: string[]) {
  return execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
}

function writeJson(filePath: string, value: unknown) {
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

function stagedNames(cwd: string): string[] {
  const out = runGit(cwd, ['diff', '--cached', '--name-only']);
  return out.split(/\r?\n/).map((line) => line.trim().replace(/\\/g, '/')).filter(Boolean);
}

{
  // Test A — classifier SSOT: abandoned owner bundle-manifest is auto-clean;
  // abandoned closure-packet / close-event are admissible (null); active foreign
  // closure-packet stays fail-closed block-and-explain.
  const tempRoot = mkdtempSync(path.join(os.tmpdir(), 'atm-abandon-residue-classify-'));
  try {
    const abandonedId = 'TASK-ABANDON-0001';
    const activeForeignId = 'TASK-ACTIVE-0002';
    writeJson(path.join(tempRoot, `.atm/history/tasks/${abandonedId}.json`), {
      workItemId: abandonedId,
      status: 'abandoned'
    });
    writeJson(path.join(tempRoot, `.atm/history/tasks/${activeForeignId}.json`), {
      workItemId: activeForeignId,
      status: 'running'
    });

    const abandonedBundle = `.atm/history/evidence/${abandonedId}.bundle-manifest.json`;
    const abandonedPacket = `.atm/history/evidence/${abandonedId}.closure-packet.json`;
    const abandonedEvent = `.atm/history/task-events/${abandonedId}/2026-07-12T00-00-00-000Z-close-fixture.json`;
    const activeForeignPacket = `.atm/history/evidence/${activeForeignId}.closure-packet.json`;
    for (const rel of [abandonedBundle, abandonedPacket, abandonedEvent, activeForeignPacket]) {
      writeJson(path.join(tempRoot, rel), { fixture: true });
    }

    const nextTaskId = 'TASK-NEXT-0003';
    const report = inspectAutoGeneratedResidue(nextTaskId, [
      abandonedBundle,
      abandonedPacket,
      abandonedEvent,
      activeForeignPacket
    ], tempRoot);

    assert.equal(report.autoCleanSafe.length, 1, 'exactly one auto-clean finding expected');
    assert.equal(report.autoCleanSafe[0]?.path, abandonedBundle);
    assert.equal(report.autoCleanSafe[0]?.cleanupAction, 'remove');
    assert.equal(
      report.blockAndExplain.some((entry) => entry.path === abandonedPacket),
      false,
      'abandoned closure-packet must be admissible (not block-and-explain)'
    );
    assert.equal(
      report.blockAndExplain.some((entry) => entry.path === abandonedEvent),
      false,
      'abandoned close-event must be admissible (not block-and-explain)'
    );
    assert.ok(
      report.blockAndExplain.some((entry) => entry.path === activeForeignPacket),
      'active foreign closure-packet must remain fail-closed'
    );
    console.log('Test A classifier abandoned vs active foreign: PASS');
  } finally {
    rmSync(tempRoot, { recursive: true, force: true });
  }
}

{
  // Test B — abandon disposition removes disposable bundle-manifest, unstages
  // abandoned ownership paths, and keeps the audit trail on disk.
  const tempRoot = mkdtempSync(path.join(os.tmpdir(), 'atm-abandon-residue-disp-'));
  const repo = path.join(tempRoot, 'repo');
  try {
    mkdirSync(repo, { recursive: true });
    runGit(repo, ['init']);
    runGit(repo, ['config', 'user.name', 'ATM Validator']);
    runGit(repo, ['config', 'user.email', 'validator@example.invalid']);
    runGit(repo, ['commit', '--allow-empty', '-m', 'bootstrap']);

    const abandonedId = 'TASK-AAO-0165';
    const taskRel = `.atm/history/tasks/${abandonedId}.json`;
    const evidenceRel = `.atm/history/evidence/${abandonedId}.json`;
    const eventRel = `.atm/history/task-events/${abandonedId}/2026-07-12T00-00-00-000Z-abandon-fixture.json`;
    const bundleRel = `.atm/history/evidence/${abandonedId}.bundle-manifest.json`;

    writeJson(path.join(repo, taskRel), {
      workItemId: abandonedId,
      status: 'running',
      title: 'malformed fixture'
    });
    writeJson(path.join(repo, evidenceRel), { workItemId: abandonedId, notes: 'audit' });
    writeJson(path.join(repo, eventRel), { action: 'close', taskId: abandonedId });
    writeJson(path.join(repo, bundleRel), { schemaId: 'atm.evidenceBundleManifest.v1', taskId: abandonedId });

    runGit(repo, ['add', taskRel, evidenceRel, eventRel, bundleRel]);
    assert.ok(stagedNames(repo).includes(bundleRel), 'fixture must stage bundle-manifest');

    const disposition = applyAbandonedResidueDisposition({
      cwd: repo,
      taskId: abandonedId,
      actorId: 'cursor-gov-0181',
      reason: 'malformed task; abandon with governed residue disposition'
    });

    assert.equal(disposition.disposition, 'remove-evidence');
    assert.ok(disposition.removed.includes(bundleRel), 'disposition must remove disposable bundle-manifest');
    assert.equal(existsSync(path.join(repo, bundleRel)), false, 'bundle-manifest must be gone from worktree');
    assert.equal(existsSync(path.join(repo, taskRel)), true, 'task ledger audit trail must remain');
    assert.equal(existsSync(path.join(repo, evidenceRel)), true, 'evidence audit trail must remain');
    assert.equal(existsSync(path.join(repo, eventRel)), true, 'task-event audit trail must remain');
    assert.ok(existsSync(path.join(repo, disposition.dispositionPath)), 'disposition packet must be written');
    assert.equal(
      stagedNames(repo).some((entry) => entry === bundleRel || entry.startsWith(`.atm/history/evidence/${abandonedId}.`) || entry === taskRel || entry.startsWith(`.atm/history/task-events/${abandonedId}/`)),
      false,
      `abandoned ownership paths must be unstaged; still staged=${JSON.stringify(stagedNames(repo))}`
    );

    const packet = JSON.parse(readFileSync(path.join(repo, disposition.dispositionPath), 'utf8')) as {
      schemaId: string;
      disposition: string;
      classes: Record<string, string[]>;
    };
    assert.equal(packet.schemaId, 'atm.abandonResidueDisposition.v1');
    assert.ok(packet.classes['remove-evidence']?.includes(bundleRel));
    assert.ok(packet.classes['keep-diagnostic']?.includes(taskRel));
    console.log('Test B abandon disposition triad + unstage: PASS');
  } finally {
    rmSync(tempRoot, { recursive: true, force: true });
  }
}

{
  // Test C — next-task commit admission: orphan abandoned bundle-manifest is
  // auto-cleaned without --defer-foreign-staged; audit trail is not deleted.
  const tempRoot = mkdtempSync(path.join(os.tmpdir(), 'atm-abandon-residue-next-'));
  const repo = path.join(tempRoot, 'repo');
  try {
    mkdirSync(repo, { recursive: true });
    runGit(repo, ['init']);
    runGit(repo, ['config', 'user.name', 'ATM Validator']);
    runGit(repo, ['config', 'user.email', 'validator@example.invalid']);
    runGit(repo, ['commit', '--allow-empty', '-m', 'bootstrap']);

    const abandonedId = 'TASK-AAO-0165';
    const nextTaskId = 'TASK-AAO-0166';
    const abandonedBundle = `.atm/history/evidence/${abandonedId}.bundle-manifest.json`;
    const abandonedTask = `.atm/history/tasks/${abandonedId}.json`;
    const abandonedEvidence = `.atm/history/evidence/${abandonedId}.json`;
    const nextFile = 'packages/cli/src/commands/fixture-next.ts';

    writeJson(path.join(repo, abandonedTask), {
      workItemId: abandonedId,
      status: 'abandoned',
      abandonResidueDisposition: `.atm/history/evidence/${abandonedId}.abandon-residue-disposition.json`
    });
    writeJson(path.join(repo, abandonedEvidence), { workItemId: abandonedId, notes: 'kept audit' });
    writeJson(path.join(repo, abandonedBundle), { schemaId: 'atm.evidenceBundleManifest.v1', taskId: abandonedId });
    writeJson(path.join(repo, `.atm/history/evidence/${abandonedId}.abandon-residue-disposition.json`), {
      schemaId: 'atm.abandonResidueDisposition.v1',
      taskId: abandonedId,
      disposition: 'remove-evidence'
    });

    mkdirSync(path.join(repo, path.dirname(nextFile)), { recursive: true });
    writeFileSync(path.join(repo, nextFile), 'export const next = 1;\n', 'utf8');
    writeJson(path.join(repo, `.atm/history/tasks/${nextTaskId}.json`), {
      workItemId: nextTaskId,
      status: 'running',
      taskDirectionLock: { allowedFiles: [nextFile] }
    });

    // Leave orphan abandoned bundle-manifest as untracked dirty (the
    // GENERATED_RESIDUE candidate path uses worktree dirty + untracked).
    assert.equal(existsSync(path.join(repo, abandonedBundle)), true);

    const report = resolveTaskScopedCommitBundle({
      cwd: repo,
      taskId: nextTaskId,
      taskDocument: {
        taskDirectionLock: { allowedFiles: [nextFile] }
      },
      apply: true,
      autoStage: true,
      deferForeignStaged: false,
      message: 'fix: next task after abandon',
      actorId: 'next-actor',
      trailers: []
    });

    assert.equal(
      report.ok,
      true,
      `next-task commit must admit without defer: ${JSON.stringify({
        blockedCode: report.blockedCode,
        blockedSummary: report.blockedSummary,
        blockedResidue: report.blockedResidue
      })}`
    );
    assert.ok(
      report.autoCleanedResidue.some((entry) => entry.path === abandonedBundle),
      `orphan abandoned bundle-manifest must be auto-cleaned: ${JSON.stringify(report.autoCleanedResidue)}`
    );
    assert.equal(existsSync(path.join(repo, abandonedBundle)), false, 'orphan bundle-manifest must be removed');
    assert.equal(existsSync(path.join(repo, abandonedTask)), true, 'abandoned task ledger must survive');
    assert.equal(existsSync(path.join(repo, abandonedEvidence)), true, 'abandoned evidence must survive');
    assert.ok(
      report.blockedResidue.every((entry) => entry.path !== abandonedBundle),
      'cleaned abandoned bundle-manifest must not remain in blockedResidue'
    );
    console.log('Test C next-task commit admission after abandon residue: PASS');
  } finally {
    rmSync(tempRoot, { recursive: true, force: true });
  }
}

console.log(JSON.stringify({ ok: true, suite: 'abandon-residue-governed-disposition' }, null, 2));
