import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtempSync, mkdirSync, readFileSync, renameSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { runSetup } from '../../packages/cli/src/commands/setup.ts';
import { governanceCommandPrefix } from '../../packages/cli/src/commands/shared/atm-cli-entrypoint.ts';
import { inspectAutoGeneratedResidue } from '../../packages/cli/src/commands/framework-development/closure-packet-schema.ts';
import { verifiedBootstrapReportOwner } from '../../packages/cli/src/commands/shared/bootstrap-report-provenance.ts';
import { selectActionableResidueFindings } from '../../packages/cli/src/commands/hook/pre-commit/failure-envelope.ts';
import { resolveTaskScopedCommitBundle } from '../../packages/cli/src/commands/git-governance.ts';
import { adoptLocalGovernanceBundle } from '../../packages/plugin-governance-local/src/bootstrap/bootstrap.ts';

test('shared npm command runs offline from a consumer with no package dependency', t => {
  const root = mkdtempSync(path.join(tmpdir(), "atm shared '$() command "));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const entry = path.join(root, 'shared/node_modules/@ai-atomic-framework/cli/dist/npm-runtime/atm.mjs');
  const consumer = path.join(root, 'consumer');
  mkdirSync(path.dirname(entry), { recursive: true }); mkdirSync(consumer);
  writeFileSync(entry, 'console.log(JSON.stringify(process.argv.slice(2)))');
  const command = `${governanceCommandPrefix(entry)} guide --goal "inspect" --cwd . --json`;
  assert.ok(!command.includes('npm exec'));
  const result = spawnSync(command, { shell: true, cwd: consumer, encoding: 'utf8', env: { ...process.env, npm_config_offline: 'true' } });
  assert.equal(result.status, 0, result.stderr);
  assert.deepEqual(JSON.parse(result.stdout), ['guide', '--goal', 'inspect', '--cwd', '.', '--json']);
});

test('official setup bootstrap reports retain their provenance and bytes', async t => {
  const root = mkdtempSync(path.join(tmpdir(), 'atm-bootstrap-residue-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const project = path.join(root, 'project'), homeDir = path.join(root, 'home');
  mkdirSync(project); mkdirSync(homeDir);
  const git = (...args: string[]) => execFileSync('git', args, { cwd: project, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  git('init'); git('config', 'user.name', 'ATM Test'); git('config', 'user.email', 'test@example.invalid');
  writeFileSync(path.join(project, 'app.txt'), 'before\n');
  git('add', 'app.txt'); git('commit', '-m', 'fixture');
  assert.equal((await runSetup(['--cwd', project, '--agents', 'none', '--json'], { interactive: false, detection: { homeDir, env: {} } })).ok, true);
  const reports = ['.atm/history/reports/context-budget/bootstrap-bootstrap-BOOTSTRAP-0001.json', '.atm/history/reports/continuation/BOOTSTRAP-0001.json'];
  const before = reports.map(file => readFileSync(path.join(project, file)));
  const findings = inspectAutoGeneratedResidue('TASK-OTHER-0001', reports, project);
  assert.equal(findings.manualReview.length, 0);
  assert.equal(findings.autoCleanSafe.length, 0);
  assert.equal(findings.blockAndExplain.length, 2);
  for (const finding of findings.blockAndExplain) {
    assert.equal(finding.ownerTaskId, 'BOOTSTRAP-0001');
    assert.equal(finding.cleanupAction, null);
  }
  reports.forEach((file, i) => assert.deepEqual(readFileSync(path.join(project, file)), before[i]));
  const hookInput = { cwd: project, findings: findings.blockAndExplain, stagedFiles: [], committingTaskId: 'TASK-OTHER-0001', activeLockTaskIds: new Set(), hasActiveClaim: () => false, hasTerminalOwner: () => false };
  assert.equal(selectActionableResidueFindings(hookInput).length, 0);
  assert.equal(selectActionableResidueFindings({ ...hookInput, stagedFiles: reports }).length, 2);
  assert.equal(selectActionableResidueFindings({ ...hookInput, committingTaskId: 'BOOTSTRAP-0001' }).length, 2);
  const taskDocument = { workItemId: 'TASK-OTHER-0001', status: 'running', scopePaths: ['app.txt'], deliverables: ['app.txt'], taskDirectionLock: { allowedFiles: ['app.txt'] } };
  writeFileSync(path.join(project, 'app.txt'), 'after\n');
  const bundleInput = { cwd: project, taskId: 'TASK-OTHER-0001', taskDocument, apply: false, autoStage: true, deferForeignStaged: false, message: 'fixture', actorId: 'fixture', trailers: [], wip: true };
  const bundle = resolveTaskScopedCommitBundle(bundleInput);
  assert.equal(bundle.ok, true, bundle.blockedSummary ?? undefined);
  assert.deepEqual(bundle.commitFiles, ['app.txt']);
  assert.equal(bundle.blockedResidue?.length ?? 0, 0);
  assert.equal(bundle.manualReviewResidue?.length ?? 0, 0);
  assert.ok(!bundle.commitFiles?.some((file: string) => reports.includes(file)));
  git('add', '-f', '--', ...reports);
  const indexBefore = git('ls-files', '--stage');
  const stagedBundle = resolveTaskScopedCommitBundle({ ...bundleInput, apply: true });
  assert.equal(stagedBundle.ok, false);
  assert.equal(git('ls-files', '--stage'), indexBefore);
  git('reset', '--', ...reports);
  const unknown = '.atm/history/reports/unknown.json';
  writeFileSync(path.join(project, unknown), '{}');
  git('add', '-f', '--', unknown);
  const unknownIndex = git('ls-files', '--stage');
  assert.equal(resolveTaskScopedCommitBundle({ ...bundleInput, apply: true }).ok, false);
  assert.equal(git('ls-files', '--stage'), unknownIndex);
  assert.equal(selectActionableResidueFindings({ ...hookInput, findings: inspectAutoGeneratedResidue('TASK-OTHER-0001', [unknown], project).manualReview }).length, 1);
  git('reset', '--', unknown);
  rmSync(path.join(project, unknown));
  const mutations: [string, (value: any) => void][] = [
    [reports[0], value => { value.estimatedTokens++; }],
    [reports[0], value => { value.reason = 'changed'; }],
    [reports[1], value => { value.workItemId = 'TASK-OTHER-0001'; }],
    [reports[1], value => { value.handoffKind = 'continuation'; }],
    [reports[1], value => { value.summary = 'changed'; }],
    ['.atm/runtime/evidence-ledger/bundles/BOOTSTRAP-0001.json', value => { value.contextBudgetReportPath = 'other'; }],
    ['.atm/history/tasks/BOOTSTRAP-0001.json', value => { value.taskKind = 'implementation'; }]
  ];
  for (const [file, mutate] of mutations) {
    const location = path.join(project, file), saved = readFileSync(location);
    const value = JSON.parse(saved.toString()); mutate(value); writeFileSync(location, JSON.stringify(value));
    assert.equal(verifiedBootstrapReportOwner(project, reports[0]), null, file);
    assert.equal(verifiedBootstrapReportOwner(project, reports[1]), null, file);
    const invalid = inspectAutoGeneratedResidue('TASK-OTHER-0001', reports, project).manualReview;
    assert.equal(invalid.length, 2);
    assert.equal(selectActionableResidueFindings({ ...hookInput, findings: invalid }).length, 2);
    writeFileSync(location, saved);
  }
  writeFileSync(path.join(project, reports[1]), '{');
  assert.equal(verifiedBootstrapReportOwner(project, reports[0]), null);
  writeFileSync(path.join(project, reports[1]), before[1]);
  writeFileSync(path.join(project, reports[1]), `\uFEFF${before[1].toString()}`);
  assert.equal(verifiedBootstrapReportOwner(project, reports[1]), null);
  writeFileSync(path.join(project, reports[1]), before[1]);
  const reportFile = path.join(project, reports[1]), backup = `${reportFile}.saved`;
  renameSync(reportFile, backup); symlinkSync(backup, reportFile);
  assert.equal(verifiedBootstrapReportOwner(project, reports[1]), null);
  rmSync(reportFile); renameSync(backup, reportFile);
  assert.equal(verifiedBootstrapReportOwner(project, '.atm/history/reports/continuation/../BOOTSTRAP-0001.json'), null);
  assert.equal(verifiedBootstrapReportOwner(project, '.atm/history/reports/unknown.json'), null);
  reports.forEach((file, i) => assert.deepEqual(readFileSync(path.join(project, file)), before[i]));
});

test('producer-supported custom bootstrap owner is preserved without relabeling', t => {
  const root = mkdtempSync(path.join(tmpdir(), 'atm-custom-bootstrap-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  adoptLocalGovernanceBundle(root, { taskId: 'BOOTSTRAP-CUSTOM_42' });
  assert.equal(verifiedBootstrapReportOwner(root, '.atm/history/reports/continuation/BOOTSTRAP-CUSTOM_42.json'), 'BOOTSTRAP-CUSTOM_42');
});
