import { createHash } from 'node:crypto';
export const DEPENDENCY_GRAPH_BYPASS_GATE_SCHEMA_ID='atm.dependencyGraphBypassGate.v1' as const;
export type DependencyGateStatus='proven'|'blocked'|'stale'|'contradictory';
export interface DependencyGateInput{readonly runId:string;readonly authority:{readonly authorityId:string;readonly digest:string;readonly sealed:true};readonly observedAuthorityDigest:string;readonly nodes:readonly string[];readonly edges:readonly (readonly[string,string])[];readonly forbiddenEdges?:readonly (readonly[string,string])[];readonly publicInterfaces?:readonly string[];}
export interface DependencyGateResult{readonly schemaId:typeof DEPENDENCY_GRAPH_BYPASS_GATE_SCHEMA_ID;readonly specVersion:'0.1.0';readonly runId:string;readonly authority:DependencyGateInput['authority'];readonly nodes:readonly string[];readonly edges:readonly (readonly[string,string])[];readonly violations:readonly string[];readonly status:DependencyGateStatus;readonly diagnostics:readonly string[];readonly resultDigest:string;}
export function compileDependencyGraphBypassGate(i:DependencyGateInput):DependencyGateResult{const n={runId:String(i.runId??'').trim(),authority:i.authority,observed:String(i.observedAuthorityDigest??''),nodes:[...(i.nodes??[])].map(String).sort(),edges:[...(i.edges??[])].map(e=>[String(e[0]),String(e[1])] as const).sort(),forbidden:[...(i.forbiddenEdges??[])].map(e=>[String(e[0]),String(e[1])] as const),publicInterfaces:[...(i.publicInterfaces??[])].map(String)};const d:string[]=[];if(!n.authority?.sealed||n.observed!==n.authority?.digest)d.push('authority-digest-mismatch');const nodeSet=new Set(n.nodes);for(const [a,b] of n.edges)if(!nodeSet.has(a)||!nodeSet.has(b))d.push(`unknown-node:${!nodeSet.has(a)?a:b}`);const f=new Set(n.forbidden.map(e=>e.join('->'))),v=n.edges.filter(e=>f.has(e.join('->'))).map(e=>e.join('->'));if(v.length)d.push('forbidden-edge');const status:DependencyGateStatus=d.some(x=>x.startsWith('unknown-'))?'contradictory':d.some(x=>x.includes('authority'))?'stale':d.length?'blocked':'proven';return{schemaId:DEPENDENCY_GRAPH_BYPASS_GATE_SCHEMA_ID,specVersion:'0.1.0',runId:n.runId,authority:n.authority,nodes:n.nodes,edges:n.edges,violations:v,status,diagnostics:d,resultDigest:`sha256:${createHash('sha256').update(JSON.stringify({n,v,status,d})).digest('hex')}`};}
export const createDependencyGraphBypassGate=compileDependencyGraphBypassGate;
export function replayDependencyGraphBypassGate(r:DependencyGateResult){return compileDependencyGraphBypassGate({runId:r.runId,authority:r.authority,observedAuthorityDigest:r.authority.digest,nodes:r.nodes,edges:r.edges,forbiddenEdges:r.violations.map(x=>x.split('->') as [string,string])});}
export function validateDependencyGraphBypassGate(r:DependencyGateResult){const x=replayDependencyGraphBypassGate(r),d=[...r.diagnostics];if(x.resultDigest!==r.resultDigest)d.push('result-digest-mismatch');return{ok:d.length===0&&r.status==='proven',diagnostics:[...new Set(d)]};}
