import { createHash } from 'node:crypto';

export const PERFORMANCE_RESILIENCE_RATCHET_SCHEMA_ID = 'atm.performanceResilienceRatchet.v1' as const;
export const PERFORMANCE_RESILIENCE_RATCHET_COMPILER_ID = 'atm.performance-resilience-ratchet.compiler.v1' as const;
export type PerformanceResilienceStatus = 'proven' | 'blocked' | 'stale' | 'contradictory';
export type PerformanceMetric = 'latencyMs' | 'memoryBytes' | 'successRate' | 'resilienceRate';
export interface PerformanceResilienceAuthority { readonly authorityId: string; readonly digest: string; readonly sealed: true; }
export interface PerformanceBenchmark { readonly benchmarkId: string; readonly latencyMs: number; readonly memoryBytes: number; readonly successRate: number; readonly resilienceRate: number; readonly digest: string; }
export interface PerformanceResilienceLimits { readonly maxLatencyRegressionMs: number; readonly maxMemoryRegressionBytes: number; readonly minSuccessRate: number; readonly minResilienceRate: number; }
export interface PerformanceResilienceInput { readonly ratchetId: string; readonly generatedAt: string; readonly authority: PerformanceResilienceAuthority; readonly observedAuthorityDigest: string; readonly baselines: readonly PerformanceBenchmark[]; readonly observations: readonly PerformanceBenchmark[]; readonly limits: PerformanceResilienceLimits; readonly metrics?: readonly string[]; readonly provenance?: Readonly<Record<string, unknown>>; }
export interface PerformanceResilienceResult { readonly schemaId: typeof PERFORMANCE_RESILIENCE_RATCHET_SCHEMA_ID; readonly specVersion: '0.1.0'; readonly compilerId: typeof PERFORMANCE_RESILIENCE_RATCHET_COMPILER_ID; readonly ratchetId: string; readonly generatedAt: string; readonly authority: PerformanceResilienceAuthority; readonly limits: PerformanceResilienceLimits; readonly baselines: readonly PerformanceBenchmark[]; readonly observations: readonly PerformanceBenchmark[]; readonly projection: { readonly benchmarkCount: number; readonly regressions: readonly string[]; readonly passed: readonly string[]; }; readonly status: PerformanceResilienceStatus; readonly diagnostics: readonly string[]; readonly repairCommand: string | null; readonly provenance: Readonly<Record<string, unknown>>; readonly resultDigest: string; }

const supportedMetrics: readonly PerformanceMetric[] = ['latencyMs', 'memoryBytes', 'successRate', 'resilienceRate'];
export function compilePerformanceResilienceRatchet(input: PerformanceResilienceInput): PerformanceResilienceResult {
  const authorityWasSealed = input.authority?.sealed === true, n = normalize(input), diagnostics: string[] = [];
  if (!n.ratchetId || !n.generatedAt || !n.baselines.length || !n.observations.length) diagnostics.push('receipt-incomplete');
  if (!n.authority.authorityId || !n.authority.digest || !authorityWasSealed) diagnostics.push('authority-incomplete');
  if (n.observedAuthorityDigest !== n.authority.digest) diagnostics.push('authority-digest-mismatch');
  if (!validLimits(n.limits)) diagnostics.push('invalid-limits');
  for (const metric of n.metrics) if (!supportedMetrics.includes(metric as PerformanceMetric)) diagnostics.push(`unsupported-metric:${metric}`);
  const baselines = new Map<string, PerformanceBenchmark>();
  for (const benchmark of n.baselines) { if (baselines.has(benchmark.benchmarkId)) diagnostics.push(`duplicate-baseline:${benchmark.benchmarkId}`); baselines.set(benchmark.benchmarkId, benchmark); validateBenchmark(benchmark, diagnostics, 'baseline'); }
  const observationIds = new Set<string>(), regressions: string[] = [], passed: string[] = [];
  for (const observation of n.observations) {
    if (observationIds.has(observation.benchmarkId)) diagnostics.push(`duplicate-observation:${observation.benchmarkId}`); observationIds.add(observation.benchmarkId); validateBenchmark(observation, diagnostics, 'observation');
    const baseline = baselines.get(observation.benchmarkId); if (!baseline) { diagnostics.push(`missing-baseline:${observation.benchmarkId}`); continue; }
    const failed = metricRegressions(observation, baseline, n.limits, n.metrics); if (failed.length) regressions.push(...failed); else passed.push(observation.benchmarkId);
  }
  for (const benchmarkId of baselines.keys()) if (!observationIds.has(benchmarkId)) diagnostics.push(`missing-observation:${benchmarkId}`);
  if (regressions.length) diagnostics.push('ratchet-regression');
  const status: PerformanceResilienceStatus = diagnostics.some(code => code.startsWith('duplicate-') || code.startsWith('invalid-') || code.startsWith('missing-') || code.startsWith('unsupported-') || code === 'receipt-incomplete' || code === 'authority-incomplete') ? 'contradictory' : diagnostics.some(code => code.includes('authority')) ? 'stale' : diagnostics.length ? 'blocked' : 'proven';
  const projection = { benchmarkCount: n.observations.length, regressions: regressions.sort(), passed: passed.sort() }, repairCommand = status === 'proven' ? null : 'rebuild the sealed benchmark baseline and rerun the ratchet compiler';
  return seal({ schemaId: PERFORMANCE_RESILIENCE_RATCHET_SCHEMA_ID, specVersion: '0.1.0', compilerId: PERFORMANCE_RESILIENCE_RATCHET_COMPILER_ID, ratchetId: n.ratchetId, generatedAt: n.generatedAt, authority: n.authority, limits: n.limits, baselines: n.baselines, observations: n.observations, projection, status, diagnostics, repairCommand, provenance: n.provenance });
}

export const createPerformanceResilienceRatchet = compilePerformanceResilienceRatchet;
export function replayPerformanceResilienceRatchet(result: PerformanceResilienceResult): PerformanceResilienceResult { return compilePerformanceResilienceRatchet({ ratchetId: result.ratchetId, generatedAt: result.generatedAt, authority: result.authority, observedAuthorityDigest: result.authority.digest, baselines: result.baselines, observations: result.observations, limits: result.limits, metrics: supportedMetrics, provenance: result.provenance }); }
export function validatePerformanceResilienceRatchet(result: PerformanceResilienceResult) { const replay = replayPerformanceResilienceRatchet(result), diagnostics = [...result.diagnostics], actual = digest(unsigned(result)); if (actual !== result.resultDigest || replay.resultDigest !== result.resultDigest) diagnostics.push('result-digest-mismatch'); return { ok: diagnostics.length === 0 && result.status === 'proven', diagnostics: [...new Set(diagnostics)] }; }

function metricRegressions(observation: PerformanceBenchmark, baseline: PerformanceBenchmark, limits: PerformanceResilienceLimits, metrics: readonly string[]) { const checks: Readonly<Record<PerformanceMetric, boolean>> = { latencyMs: observation.latencyMs - baseline.latencyMs > limits.maxLatencyRegressionMs, memoryBytes: observation.memoryBytes - baseline.memoryBytes > limits.maxMemoryRegressionBytes, successRate: observation.successRate < limits.minSuccessRate, resilienceRate: observation.resilienceRate < limits.minResilienceRate }; return supportedMetrics.filter(metric => metrics.includes(metric) && checks[metric]).map(metric => `${observation.benchmarkId}:${metric}`); }
function validLimits(limits: PerformanceResilienceLimits) { return Number.isFinite(limits.maxLatencyRegressionMs) && limits.maxLatencyRegressionMs >= 0 && Number.isFinite(limits.maxMemoryRegressionBytes) && limits.maxMemoryRegressionBytes >= 0 && [limits.minSuccessRate, limits.minResilienceRate].every(value => Number.isFinite(value) && value >= 0 && value <= 1); }
function validateBenchmark(benchmark: PerformanceBenchmark, diagnostics: string[], kind: string) { if (!benchmark.benchmarkId || !benchmark.digest || ![benchmark.latencyMs, benchmark.memoryBytes, benchmark.successRate, benchmark.resilienceRate].every(Number.isFinite) || benchmark.latencyMs < 0 || benchmark.memoryBytes < 0 || benchmark.successRate < 0 || benchmark.successRate > 1 || benchmark.resilienceRate < 0 || benchmark.resilienceRate > 1) diagnostics.push(`invalid-${kind}:${benchmark.benchmarkId}`); }
function normalize(input: PerformanceResilienceInput) { const benchmark = (value: PerformanceBenchmark) => ({ benchmarkId: String(value?.benchmarkId ?? '').trim(), latencyMs: Number(value?.latencyMs), memoryBytes: Number(value?.memoryBytes), successRate: Number(value?.successRate), resilienceRate: Number(value?.resilienceRate), digest: String(value?.digest ?? '').trim() }); return { ratchetId: String(input.ratchetId ?? '').trim(), generatedAt: String(input.generatedAt ?? '').trim(), authority: { authorityId: String(input.authority?.authorityId ?? '').trim(), digest: String(input.authority?.digest ?? '').trim(), sealed: true as const }, observedAuthorityDigest: String(input.observedAuthorityDigest ?? '').trim(), metrics: [...(input.metrics ?? supportedMetrics)].map(String).sort(), limits: { maxLatencyRegressionMs: Number(input.limits?.maxLatencyRegressionMs), maxMemoryRegressionBytes: Number(input.limits?.maxMemoryRegressionBytes), minSuccessRate: Number(input.limits?.minSuccessRate), minResilienceRate: Number(input.limits?.minResilienceRate) }, baselines: [...(input.baselines ?? [])].map(benchmark).sort((left, right) => left.benchmarkId.localeCompare(right.benchmarkId)), observations: [...(input.observations ?? [])].map(benchmark).sort((left, right) => left.benchmarkId.localeCompare(right.benchmarkId)), provenance: input.provenance ?? {} }; }
function seal<T extends Omit<PerformanceResilienceResult, 'resultDigest'>>(value: T): PerformanceResilienceResult { return { ...value, resultDigest: digest(value) }; }
function unsigned(result: PerformanceResilienceResult): Omit<PerformanceResilienceResult, 'resultDigest'> { const { resultDigest: _ignored, ...value } = result; return value; }
function digest(value: unknown) { return `sha256:${createHash('sha256').update(JSON.stringify(value, (_, item) => item && typeof item === 'object' && !Array.isArray(item) ? Object.fromEntries(Object.entries(item).sort(([left], [right]) => left.localeCompare(right))) : item)).digest('hex')}`; }
