import { createHash } from 'node:crypto';
export const PROPERTY_METAMORPHIC_GENERATORS_SCHEMA_ID='atm.propertyMetamorphicGenerators.v1' as const;
export type PropertyMetamorphicStatus='proven'|'blocked'|'stale'|'contradictory';
export interface PropertyAuthority{readonly authorityId:string;readonly digest:string;readonly sealed:boolean;}
export interface PropertyRelation{readonly relationId:string;readonly inputDigest:string;readonly transformedDigest:string;readonly expectedRelation:'equal'|'subset'|'superset'|'different'|string;readonly observedRelation?:string;}
export interface PropertyGeneratorInput{readonly authority:PropertyAuthority;readonly generatorId:string;readonly relations:readonly PropertyRelation[];readonly sourceDigest:string;readonly provenance?:Readonly<Record<string,unknown>>;}
export interface PropertyGeneratorResult{readonly schemaId:typeof PROPERTY_METAMORPHIC_GENERATORS_SCHEMA_ID;readonly specVersion:'0.1.0';readonly generatorId:string;readonly authority:PropertyAuthority;readonly relations:readonly PropertyRelation[];readonly generatedCaseIds:readonly string[];readonly status:PropertyMetamorphicStatus;readonly diagnostics:readonly string[];readonly repairCommand:string|null;readonly provenance:Readonly<Record<string,unknown>>;readonly resultDigest:string;}
export function compilePropertyMetamorphicGenerators(i:PropertyGeneratorInput):PropertyGeneratorResult{const n=norm(i),d:string[]=[];if(!n.authority.authorityId||!n.authority.digest||!n.authority.sealed)d.push('authority-incomplete');if(!n.generatorId||!n.sourceDigest||!n.relations.length)d.push('generator-incomplete');if(n.sourceDigest!==n.authority.digest)d.push('source-authority-drift');const seen=new Set<string>();for(const r of n.relations){if(seen.has(r.relationId))d.push(`duplicate-relation:${r.relationId}`);seen.add(r.relationId);if(!r.relationId||!r.inputDigest||!r.transformedDigest)d.push(`invalid-relation:${r.relationId}`);if(!['equal','subset','superset','different'].includes(r.expectedRelation))d.push(`unsupported-relation:${r.relationId}`);if(r.observedRelation&&r.observedRelation!==r.expectedRelation)d.push(`relation-mismatch:${r.relationId}`);}const ids=n.relations.map(r=>`case:${sha(`${n.generatorId}|${r.relationId}`)}`);const status:PropertyMetamorphicStatus=d.some(x=>x.startsWith('duplicate-')||x.startsWith('invalid-')||x==='authority-incomplete'||x==='generator-incomplete')?'contradictory':d.some(x=>x==='source-authority-drift')?'stale':d.some(x=>x.startsWith('unsupported-')||x.startsWith('relation-mismatch'))?'blocked':'proven';return{schemaId:PROPERTY_METAMORPHIC_GENERATORS_SCHEMA_ID,specVersion:'0.1.0',generatorId:n.generatorId,authority:n.authority,relations:n.relations,generatedCaseIds:ids,status,diagnostics:d,repairCommand:status==='proven'?null:'restore the sealed property authority and supported relation evidence, then regenerate',provenance:n.provenance,resultDigest:digest({generatorId:n.generatorId,authority:n.authority,relations:n.relations,generatedCaseIds:ids,status,diagnostics:d})};}
export const createPropertyMetamorphicGenerators=compilePropertyMetamorphicGenerators;export function replayPropertyMetamorphicGenerators(r:PropertyGeneratorResult){return compilePropertyMetamorphicGenerators({authority:r.authority,generatorId:r.generatorId,relations:r.relations,sourceDigest:r.authority.digest,provenance:r.provenance});}export function validatePropertyMetamorphicGenerators(r:PropertyGeneratorResult){const x=replayPropertyMetamorphicGenerators(r),d=[...r.diagnostics];if(x.resultDigest!==r.resultDigest)d.push('result-digest-mismatch');return{ok:d.length===0&&r.status==='proven',diagnostics:[...new Set(d)]};}
function norm(i:PropertyGeneratorInput){return{authority:i.authority,generatorId:String(i.generatorId??'').trim(),sourceDigest:String(i.sourceDigest??'').trim(),relations:[...(i.relations??[])].map(r=>({...r,relationId:String(r.relationId??'').trim(),inputDigest:String(r.inputDigest??'').trim(),transformedDigest:String(r.transformedDigest??'').trim(),expectedRelation:String(r.expectedRelation??'').trim(),observedRelation:r.observedRelation==null?undefined:String(r.observedRelation).trim()})).sort((a,b)=>a.relationId.localeCompare(b.relationId)),provenance:i.provenance??{}};}function sha(v:string){return createHash('sha256').update(v).digest('hex');}function digest(v:unknown){return`sha256:${sha(JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x))}`;}
