import { createHash } from 'node:crypto';
export const SECURITY_QUALITY_RECEIPTS_SCHEMA_ID='atm.securityQualityReceipts.v1' as const;
export type SecurityQualityStatus='proven'|'blocked'|'stale'|'contradictory';
export interface SecurityAuthority{readonly authorityId:string;readonly digest:string;readonly sealed:true;}
export interface SecurityFinding{readonly findingId:string;readonly surface:string;readonly severity:'low'|'medium'|'high'|'critical';readonly status:'pass'|'risk-accepted'|'fail';readonly digest:string;}
export interface RiskAcceptance{readonly findingId:string;readonly rationale:string;readonly authorityDigest:string;readonly approved:true;}
export interface SecurityQualityInput{readonly runId:string;readonly generatedAt:string;readonly authority:SecurityAuthority;readonly observedAuthorityDigest:string;readonly findings:readonly SecurityFinding[];readonly riskAcceptances?:readonly RiskAcceptance[];readonly requiredSurfaces?:readonly string[];readonly supportedSeverities?:readonly string[];}
export interface SecurityQualityResult{readonly schemaId:typeof SECURITY_QUALITY_RECEIPTS_SCHEMA_ID;readonly specVersion:'0.1.0';readonly runId:string;readonly generatedAt:string;readonly authority:SecurityAuthority;readonly findings:readonly SecurityFinding[];readonly riskAcceptances:readonly RiskAcceptance[];readonly projection:{readonly findingCount:number;readonly failed:readonly string[];readonly accepted:readonly string[];readonly requiredSurfaces:readonly string[];readonly missingSurfaces:readonly string[]};readonly status:SecurityQualityStatus;readonly diagnostics:readonly string[];readonly repairCommand:string|null;readonly resultDigest:string;}
export function compileSecurityQualityReceipts(input:SecurityQualityInput):SecurityQualityResult{const n=normalize(input),d:string[]=[];if(!n.authority.sealed||!n.authority.digest||n.observedAuthorityDigest!==n.authority.digest)d.push('authority-digest-mismatch');const seen=new Set<string>();for(const f of n.findings){if(seen.has(f.findingId))d.push(`duplicate-finding:${f.findingId}`);seen.add(f.findingId);if(!n.supportedSeverities.includes(f.severity))d.push(`unsupported-severity:${f.severity}`);if(!f.findingId||!f.surface||!f.digest)d.push(`incomplete-finding:${f.findingId}`);}const accepted=new Set(n.riskAcceptances.filter(a=>a.approved&&a.authorityDigest===n.authority.digest).map(a=>a.findingId));for(const a of n.riskAcceptances)if(a.authorityDigest!==n.authority.digest)d.push(`stale-risk-acceptance:${a.findingId}`);const failed=n.findings.filter(f=>f.status==='fail'&&!accepted.has(f.findingId)).map(f=>f.findingId);if(failed.length)d.push('unaccepted-security-finding');const missingSurfaces=n.requiredSurfaces.filter(s=>!n.findings.some(f=>f.surface===s));for(const s of missingSurfaces)d.push(`missing-surface:${s}`);const status:SecurityQualityStatus=d.some(x=>x.startsWith('duplicate-')||x.startsWith('unsupported-')||x.startsWith('incomplete-'))?'contradictory':d.some(x=>x.includes('authority')||x.startsWith('stale-'))?'stale':d.length?'blocked':'proven';const projection={findingCount:n.findings.length,failed,accepted:[...accepted].sort(),requiredSurfaces:n.requiredSurfaces,missingSurfaces};const repairCommand=status==='proven'?null:'repair the sealed security authority, complete required surfaces, and reissue risk acceptance receipts';return{schemaId:SECURITY_QUALITY_RECEIPTS_SCHEMA_ID,specVersion:'0.1.0',runId:n.runId,generatedAt:n.generatedAt,authority:n.authority,findings:n.findings,riskAcceptances:n.riskAcceptances,projection,status,diagnostics:d,repairCommand,resultDigest:digest({n,projection,status,diagnostics:d,repairCommand})};}
export const createSecurityQualityReceipts=compileSecurityQualityReceipts;
export function replaySecurityQualityReceipts(r:SecurityQualityResult){return compileSecurityQualityReceipts({runId:r.runId,generatedAt:r.generatedAt,authority:r.authority,observedAuthorityDigest:r.authority.digest,findings:r.findings,riskAcceptances:r.riskAcceptances,requiredSurfaces:r.projection.requiredSurfaces,supportedSeverities:['low','medium','high','critical']});}
export function validateSecurityQualityReceipts(r:SecurityQualityResult){const x=replaySecurityQualityReceipts(r),d=[...r.diagnostics];if(x.resultDigest!==r.resultDigest)d.push('result-digest-mismatch');return{ok:d.length===0&&r.status==='proven',diagnostics:[...new Set(d)]};}
function normalize(i:SecurityQualityInput){return{runId:String(i.runId??'').trim(),generatedAt:String(i.generatedAt??'').trim(),authority:{authorityId:String(i.authority?.authorityId??'').trim(),digest:String(i.authority?.digest??'').trim(),sealed:true as const},observedAuthorityDigest:String(i.observedAuthorityDigest??'').trim(),supportedSeverities:[...(i.supportedSeverities??['low','medium','high','critical'])].map(String).sort(),requiredSurfaces:[...(i.requiredSurfaces??[])].map(String).sort(),findings:[...(i.findings??[])].map(f=>({findingId:String(f?.findingId??'').trim(),surface:String(f?.surface??'').trim(),severity:f?.severity,status:f?.status,digest:String(f?.digest??'').trim()} as SecurityFinding)).sort((a,b)=>a.findingId.localeCompare(b.findingId)),riskAcceptances:[...(i.riskAcceptances??[])].map(a=>({findingId:String(a?.findingId??'').trim(),rationale:String(a?.rationale??'').trim(),authorityDigest:String(a?.authorityDigest??'').trim(),approved:true as const})).sort((a,b)=>a.findingId.localeCompare(b.findingId))};}
function digest(v:unknown){return`sha256:${createHash('sha256').update(JSON.stringify(v)).digest('hex')}`;}
