import { createHash } from 'node:crypto';
export const SHADOW_COMPARISON_SCHEMA_ID = 'atm.shadowComparison.v1' as const;
export interface ShadowCase { readonly caseId: string; readonly selected: boolean; readonly legacy: 'pass' | 'fail' | 'unknown'; readonly selectedResult: 'pass' | 'fail' | 'unknown'; readonly latencyMs: number; readonly cached?: boolean; }
export interface ShadowComparisonResult { readonly schemaId: typeof SHADOW_COMPARISON_SCHEMA_ID; readonly status: 'proven' | 'blocked'; readonly policyEpoch: string; readonly policyEpochValid: boolean; readonly selected: readonly string[]; readonly skipped: readonly string[]; readonly falseBlocks: readonly string[]; readonly escapedDefects: readonly string[]; readonly unknown: readonly string[]; readonly latency: { readonly selectedMs: number; readonly legacyMs: number }; readonly cache: { readonly hits: number; readonly misses: number; readonly invalidated: boolean }; readonly legacyAuthority: readonly { readonly caseId: string; readonly result: string }[]; readonly diagnostics: readonly string[]; readonly resultDigest: string; }
const digest = (v: unknown) => `sha256:${createHash('sha256').update(JSON.stringify(v)).digest('hex')}`;
export function compareShadow(input: { readonly authorityDigest: string; readonly policyEpoch: string; readonly cases?: readonly ShadowCase[]; readonly legacyLatencyMs?: number }): ShadowComparisonResult {
  const cases = [...(input?.cases ?? [])].sort((a, b) => String(a.caseId).localeCompare(String(b.caseId))); const selected = cases.filter((x) => x.selected).map((x) => x.caseId); const skipped = cases.filter((x) => !x.selected).map((x) => x.caseId); const falseBlocks = cases.filter((x) => !x.selected && x.legacy === 'pass' && x.selectedResult === 'fail').map((x) => x.caseId); const escapedDefects = cases.filter((x) => x.legacy === 'fail' && x.selectedResult === 'pass').map((x) => x.caseId); const unknown = cases.filter((x) => x.legacy === 'unknown' || x.selectedResult === 'unknown').map((x) => x.caseId); const diagnostics: string[] = []; if (!input?.authorityDigest) diagnostics.push('authority-missing'); if (!input?.policyEpoch) diagnostics.push('policy-epoch-missing'); if (escapedDefects.length) diagnostics.push('escaped-defect-invalidates-policy-epoch'); if (unknown.length) diagnostics.push('unknown-shadow-data'); const status = diagnostics.length ? 'blocked' : 'proven'; const policyEpochValid = status === 'proven'; return { schemaId: SHADOW_COMPARISON_SCHEMA_ID, status, policyEpoch: String(input?.policyEpoch ?? ''), policyEpochValid, selected, skipped, falseBlocks, escapedDefects, unknown, latency: { selectedMs: cases.filter((x) => x.selected).reduce((sum, x) => sum + Math.max(0, Number(x.latencyMs) || 0), 0), legacyMs: Math.max(0, Number(input?.legacyLatencyMs) || 0) }, cache: { hits: cases.filter((x) => x.cached === true).length, misses: cases.filter((x) => x.cached !== true).length, invalidated: !policyEpochValid }, legacyAuthority: cases.map((x) => ({ caseId: x.caseId, result: x.legacy })), diagnostics, resultDigest: digest({ authorityDigest: input?.authorityDigest ?? '', policyEpoch: input?.policyEpoch ?? '', cases, status, diagnostics }) };
}
export const compileShadowComparison = compareShadow;
export function validateShadowComparison(result: ShadowComparisonResult) { const diagnostics: string[] = []; if (result.schemaId !== SHADOW_COMPARISON_SCHEMA_ID) diagnostics.push('invalid-schema'); if (result.status === 'proven' && (!result.policyEpochValid || result.cache.invalidated || result.escapedDefects.length || result.unknown.length || result.diagnostics.length)) diagnostics.push('invalid-proven-verdict'); if (result.status === 'blocked' && (result.policyEpochValid || !result.cache.invalidated || !result.diagnostics.length)) diagnostics.push('invalid-blocked-verdict'); if (result.escapedDefects.length && !result.diagnostics.includes('escaped-defect-invalidates-policy-epoch')) diagnostics.push('escaped-defect-diagnostic-missing'); return { ok: diagnostics.length === 0, diagnostics }; }
