import { createHash } from 'node:crypto';
export const STATE_REPLAY_SCHEMA_ID = 'atm.stateReplay.v1' as const;
export type ReplayVerdict = 'repaired' | 'regressed' | 'stale' | 'forged' | 'missing' | 'unsupported';
export interface ReplayObservation { readonly incidentId: string; readonly family: string; readonly sourceCommit: string; readonly runnerDigest: string; readonly treeDigest: string; readonly provenanceDigest: string; readonly fixtureDigest: string; readonly realDogfood: boolean; readonly historical: boolean; readonly observedSourceCommit?: string; readonly observedRunnerDigest?: string; readonly observedTreeDigest?: string; readonly observedProvenanceDigest?: string; readonly observedFixtureDigest?: string; readonly supported?: boolean; }
export interface StateReplayResult { readonly schemaId: typeof STATE_REPLAY_SCHEMA_ID; readonly status: 'proven' | 'blocked'; readonly verdicts: readonly { readonly incidentId: string; readonly family: string; readonly verdict: ReplayVerdict; readonly diagnostics: readonly string[] }[]; readonly nonClaims: readonly string[]; readonly historicalIncidentIds: readonly string[]; readonly resultDigest: string; }
const digest = (value: unknown) => `sha256:${createHash('sha256').update(JSON.stringify(value)).digest('hex')}`;
const text = (value: unknown) => String(value ?? '').trim();
export function replayState(input: { readonly authorityDigest: string; readonly observations?: readonly ReplayObservation[]; readonly requiredFamilies?: readonly string[] }): StateReplayResult {
  const observations = [...(input?.observations ?? [])].sort((a, b) => text(a.incidentId).localeCompare(text(b.incidentId))); const required = [...new Set((input?.requiredFamilies ?? []).map(text).filter(Boolean))].sort();
  const verdicts = observations.map((item) => { const diagnostics: string[] = []; if (!text(item.incidentId) || !text(item.family)) diagnostics.push('missing-identity'); if (!item.supported) diagnostics.push('unsupported-family'); const fields: Array<[string, string, string]> = [['source-commit', item.sourceCommit, item.observedSourceCommit ?? ''], ['runner-digest', item.runnerDigest, item.observedRunnerDigest ?? ''], ['tree-digest', item.treeDigest, item.observedTreeDigest ?? ''], ['provenance-digest', item.provenanceDigest, item.observedProvenanceDigest ?? ''], ['fixture-digest', item.fixtureDigest, item.observedFixtureDigest ?? '']]; for (const [name, expected, observed] of fields) { if (!text(expected) || !text(observed)) diagnostics.push(`missing-${name}`); else if (expected !== observed) diagnostics.push(`mismatch-${name}`); } let verdict: ReplayVerdict = 'repaired'; if (diagnostics.includes('unsupported-family')) verdict = 'unsupported'; else if (diagnostics.some((d) => d.startsWith('missing-'))) verdict = 'missing'; else if (diagnostics.some((d) => d.startsWith('mismatch-'))) verdict = item.historical ? 'stale' : 'forged'; else if (!item.realDogfood) diagnostics.push('fixture-only-replay'); if (diagnostics.includes('fixture-only-replay')) verdict = 'unsupported'; return { incidentId: text(item.incidentId), family: text(item.family), verdict, diagnostics }; });
  const seen = new Set(observations.map((item) => text(item.family))); const missingFamilies = required.filter((family) => !seen.has(family)); for (const family of missingFamilies) verdicts.push({ incidentId: `missing-family-${family}`, family, verdict: 'missing', diagnostics: ['required-family-missing'] }); const historicalIncidentIds = observations.filter((item) => item.historical).map((item) => text(item.incidentId)).filter(Boolean).sort(); const diagnostics = verdicts.flatMap((item) => item.diagnostics); if (!text(input?.authorityDigest)) diagnostics.push('authority-missing'); const status = diagnostics.length || missingFamilies.length ? 'blocked' : 'proven'; const nonClaims = ['replay-is-not-close-authority', 'replay-does-not-authorize-plan4-close', 'fixture-only-replay-cannot-prove-dogfood']; return { schemaId: STATE_REPLAY_SCHEMA_ID, status, verdicts, nonClaims, historicalIncidentIds, resultDigest: digest({ authorityDigest: text(input?.authorityDigest), required, verdicts, historicalIncidentIds, status }) };
}
export const replayStateReplay = replayState;
export function validateStateReplay(result: StateReplayResult) { return { ok: result.schemaId === STATE_REPLAY_SCHEMA_ID && result.nonClaims.includes('replay-does-not-authorize-plan4-close') && result.historicalIncidentIds.every(Boolean), diagnostics: result.schemaId !== STATE_REPLAY_SCHEMA_ID ? ['invalid-schema'] : [] }; }
